import type { EntityId } from "./ids.js";
import type { FootballStaffRole, ISODate } from "./domain.js";

/**
 * Long-term world regeneration and football workforce supply, Phase A.
 *
 * Everything generated by this layer is a simulation person, never a claim
 * about a real 2026 individual, so generated records always carry
 * SIMULATION_ONLY provenance. Real imported people keep their own provenance
 * and simply retire naturally.
 */
export type WorkforceProvenance = "SIMULATION_ONLY";

export type WorkforcePopulation = "MEN_PLAYERS" | "WOMEN_PLAYERS" | "STAFF" | "REFEREES";

/** One demand line: what the world needs versus what it currently has. */
export type WorkforceDemandLine = {
  population: WorkforcePopulation;
  /** Role or cohort this line covers ("SQUAD", a staff role, an official role). */
  segment: string;
  /** Slots the active world structurally needs. */
  required: number;
  /** People currently able to fill them. */
  available: number;
  /** Forecast losses over the coming season (retirement, ageing out). */
  projectedExits: number;
  /** available - required - projectedExits; negative means a shortage. */
  balance: number;
  /** Bounded number this system may generate now to prevent collapse. */
  correction: number;
};

export type WorkforceDemandSnapshot = {
  date: ISODate;
  seasonLabel: string;
  activeClubs: number;
  activeWomensTeams: number;
  scheduledFixtures: number;
  lines: WorkforceDemandLine[];
  provenanceStatus: WorkforceProvenance;
};

/**
 * Simulation-side officiating record. The imported `referee_profiles` table
 * keeps real officials' identity; this carries the evolving career state that
 * long saves need (level, experience, retirement).
 */
export type OfficialSimulationProfile = {
  personId: EntityId;
  refereeProfileId: EntityId;
  countryId: EntityId;
  role: "REFEREE" | "ASSISTANT_REFEREE" | "FOURTH_OFFICIAL" | "VAR_OFFICIAL" | "REFEREE_INSTRUCTOR";
  gender: "male" | "female";
  /** 1 = top domestic list, 2 = second tier, 3 = entry/regional. */
  level: number;
  /** Bounded 0..100. */
  quality: number;
  potential: number;
  experience: number;
  fitness: number;
  /** Matches officiated in the current season, for workload awareness. */
  seasonAppointments: number;
  careerAppointments: number;
  debutOn: ISODate;
  retiredOn?: ISODate;
  status: "ACTIVE" | "RETIRED" | "INSTRUCTOR";
  locationId?: EntityId;
  provenanceStatus: WorkforceProvenance;
};

/** Idempotency ledger: one row per (season, kind, context) generation event. */
export type WorkforceIntakeEvent = {
  id: EntityId;
  seasonLabel: string;
  kind: string;
  contextKey: string;
  generatedOn: ISODate;
  generatedCount: number;
  provenanceStatus: WorkforceProvenance;
};

export type WorkforceRoleCount = { role: FootballStaffRole | string; count: number };

/** Machine-readable answer to "can this world sustain itself?". */
export type WorldSustainabilityReport = {
  date: ISODate;
  seasonLabel: string;
  activeMalePlayers: number;
  activeFemalePlayers: number;
  youthCohort: number;
  freeAgents: number;
  averagePlayerAge: number;
  ageBands: Record<string, number>;
  realActivePeople: number;
  generatedActivePeople: number;
  activeManagers: number;
  activeStaff: number;
  staffByRole: WorkforceRoleCount[];
  activeReferees: number;
  activeAssistantReferees: number;
  retirementsThisSeason: number;
  generatedEntrantsThisSeason: number;
  leagueDistribution: Array<{ competition: string; clubs: number; players: number }>;
  districtOrigins: Array<{ district: string; players: number }>;
  demand: WorkforceDemandSnapshot;
  /** Invariant violations that would make a long save structurally invalid. */
  violations: string[];
  sustainable: boolean;
};

export type LowerLeagueClubCoverage = {
  clubId: EntityId;
  division: "B" | "C";
  realPlayers: number;
  generatedStartingPlayers: number;
  realStaff: number;
  generatedStaff: number;
  playableSquad: boolean;
};

export type LowerLeagueCoverageReport = {
  generatedOn: ISODate;
  realPlayers: number;
  bDivisionRealPlayers: number;
  cDivisionRealPlayers: number;
  generatedStartingPlayers: number;
  freeAgents: number;
  unknownClub: number;
  realStaff: number;
  bDivisionHeadCoaches: number;
  cDivisionHeadCoaches: number;
  generatedLowerLeagueManagers: number;
  clubs: LowerLeagueClubCoverage[];
  provenanceStatus: WorkforceProvenance;
};
