import { createStableEntityId, type ClubNetworkConflict, type EntityId, type InternationalClubPartnership, type InternationalClubPartnershipType, type MultiClubOwnershipRecord, type OwnershipNetworkStrategy } from "@nepal-football-sim/shared-types";
import { ClubNetworkRepository, type GameDatabase } from "@nepal-football-sim/database";

const control=(stake:number):MultiClubOwnershipRecord["controlLevel"]=>stake>=51?"MAJORITY":stake>=25?"JOINT":stake>0?"MINORITY":"NONE";
export const createNetworkOwnership=(db:GameDatabase,input:{ownerGroupId:EntityId;clubId:EntityId;stakePercentage:number;acquisitionDate:string;strategy:OwnershipNetworkStrategy;boardInfluence?:number}):MultiClubOwnershipRecord=>{if(input.stakePercentage<=0||input.stakePercentage>100)throw new Error("Network stake must be between 0 and 100");const record:MultiClubOwnershipRecord={id:createStableEntityId("network-ownership",`${input.ownerGroupId}:${input.clubId}`),ownerGroupId:input.ownerGroupId,clubId:input.clubId,stakePercentage:input.stakePercentage,controlLevel:control(input.stakePercentage),acquisitionDate:input.acquisitionDate,boardInfluence:Math.max(0,Math.min(100,input.boardInfluence??input.stakePercentage)),strategy:input.strategy,relationshipStatus:"ACTIVE",provenanceStatus:"SIMULATION_ONLY"};new ClubNetworkRepository(db).upsertOwnership(record);return record;};
export const createClubPartnership=(db:GameDatabase,input:Omit<InternationalClubPartnership,"id"|"status"|"provenanceStatus">):InternationalClubPartnership=>{if(input.fromClubId===input.toClubId)throw new Error("A club cannot partner with itself");const value={...input,id:createStableEntityId("club-partnership",`${input.fromClubId}:${input.toClubId}:${input.partnershipType}`),status:"PROPOSED" as const,provenanceStatus:"SIMULATION_ONLY" as const};new ClubNetworkRepository(db).upsertPartnership(value);return value;};
export const assessClubNetworkConflicts=(records:readonly MultiClubOwnershipRecord[],competitionByClub:ReadonlyMap<EntityId,EntityId>,relatedTransfersByClub:ReadonlyMap<EntityId,number>):ClubNetworkConflict[]=>{const result:ClubNetworkConflict[]=[];const groups=new Map<EntityId,MultiClubOwnershipRecord[]>();for(const record of records)groups.set(record.ownerGroupId,[...(groups.get(record.ownerGroupId)??[]),record]);for(const group of groups.values()){if(group.length<2)continue;const clubIds=group.map((item)=>item.clubId).sort();result.push({type:"RELATED_OWNERSHIP",clubIds,severity:"MEDIUM",reason:"One owner group has stakes in multiple clubs",provenanceStatus:"SIMULATION_ONLY"});const competitions=new Map<EntityId,EntityId[]>();for(const item of group){const competition=competitionByClub.get(item.clubId);if(competition)competitions.set(competition,[...(competitions.get(competition)??[]),item.clubId]);}for(const clubIds of competitions.values())if(clubIds.length>1)result.push({type:"SAME_COMPETITION",clubIds:clubIds.sort(),severity:"HIGH",reason:"Linked clubs share a competition",provenanceStatus:"SIMULATION_ONLY"});}for(const [clubId,count] of relatedTransfersByClub)if(count>=3)result.push({type:"TRANSFER_DEPENDENCY",clubIds:[clubId],severity:count>=6?"HIGH":"MEDIUM",reason:"Related-party transfer activity is becoming dependent",provenanceStatus:"SIMULATION_ONLY"});return result;};
export const evaluateRelatedPartyTransfer=(input:{fee:number;askingRange:{min:number;max:number};playerKnownToBuyer:boolean;registrationAllowed:boolean}):{allowed:boolean;relatedParty:true;reason:string}=>{const within=input.fee>=input.askingRange.min*.85&&input.fee<=input.askingRange.max*1.1;const allowed=within&&input.playerKnownToBuyer&&input.registrationAllowed;return {allowed,relatedParty:true,reason:allowed?"Market-value range and normal registration checks passed":"Normal valuation, knowledge, or registration checks failed"};};
export const evaluatePartnershipPathway=(input:{relationshipStrength:number;playerQuality:number;clubNeed:number;scoutingKnowledge:number;registrationAllowed:boolean}):{eligible:boolean;reason:string}=>{const score=input.relationshipStrength*.25+input.playerQuality*.25+input.clubNeed*.2+input.scoutingKnowledge*.3;const eligible=input.registrationAllowed&&score>=55;return {eligible,reason:eligible?"Existing relationship, knowledge, need, and quality support a pathway":"Pathway requires stronger knowledge, need, quality, or registration compliance"};};
export const recommendNetworkStrategy=(input:{wealth:number;footballReputation:number;commercialAccess:number;developmentNeed:number;distanceFactor:number}):OwnershipNetworkStrategy=>input.developmentNeed>=70?"DEVELOPMENT_CLUB":input.commercialAccess>=70?"COMMERCIAL_MARKET_CLUB":input.wealth>=70&&input.footballReputation>=60?"FLAGSHIP_CLUB":input.distanceFactor<=40?"PATHWAY_CLUB":"ACADEMY_TECHNICAL_PARTNER";

export const evaluateInternationalPartnership=(input:{nepalClubReputation:number;academyQuality:number;continentalExposure:number;commercialReach:number;foreignClubReputation:number;relationshipHistory:number}):{eligible:boolean;score:number;reason:string}=>{
  const score=Math.max(0,Math.min(100,input.nepalClubReputation*.2+input.academyQuality*.2+input.continentalExposure*.18+input.commercialReach*.12+input.foreignClubReputation*.18+input.relationshipHistory*.12));
  return {eligible:score>=52,score,reason:score>=52?"The clubs have a credible sporting, commercial, and relationship fit":"The proposal needs stronger sporting or strategic fit"};
};

export const activateClubPartnership=(db:GameDatabase,partnershipId:EntityId,input:{date:string;eligibility:{eligible:boolean;score:number}}):InternationalClubPartnership=>{
  if(!input.eligibility.eligible) throw new Error("Partnership proposal is not eligible");
  const current=new ClubNetworkRepository(db).partnerships().find((value)=>value.id===partnershipId);
  if(!current) throw new Error("Partnership proposal does not exist");
  const strength=Math.max(0,Math.min(100,Math.round(input.eligibility.score)));
  db.prepare("UPDATE international_club_partnerships SET relationship_strength=?,status='ACTIVE',start_date=? WHERE id=?").run(strength,input.date,partnershipId);
  return {...current,relationshipStrength:strength,status:"ACTIVE",startDate:input.date};
};

export const boundedPartnershipBenefits=(partnership:InternationalClubPartnership):{scouting:number;development:number;loanPreference:number;commercial:number}=>{
  const strength=Math.max(0,Math.min(100,partnership.relationshipStrength))/100;
  return {scouting:partnership.partnershipType==="SCOUTING"?strength*.2:0,development:["ACADEMY","YOUTH_DEVELOPMENT","TECHNICAL","TRAINING"].includes(partnership.partnershipType)?strength*.12:0,loanPreference:["LOAN","LOAN_PLAYER_PATHWAY"].includes(partnership.partnershipType)?strength*.18:0,commercial:partnership.partnershipType==="COMMERCIAL"?strength*.08:0};
};
