import { createStableEntityId, type CompetitionDistributionPayment, type CompetitionDistributionPolicy, type EntityId } from "@nepal-football-sim/shared-types";
import { CompetitionDistributionRepository, FederationGovernanceRepository, type GameDatabase } from "@nepal-football-sim/database";
import { postClubTransaction } from "./club-economy.js";
import { postFederationTransaction } from "./federation-governance.js";

export type DistributionStanding = { clubId: EntityId; position: number; performance: number; audience?: number; youthEligible?: boolean; womensEligible?: boolean; infrastructureEligible?: boolean };
export type DistributionLine = { clubId: EntityId; amount: number; reason: string };
const components=(policy:CompetitionDistributionPolicy):number=>policy.championPrize+policy.runnerUpPrize+policy.placementPrizes+policy.participationPayments+policy.equalSharePayments+policy.performanceSharePayments+policy.audienceShare+policy.youthDevelopmentIncentives+policy.womensFootballIncentives+policy.infrastructureGrants;

export const validateDistributionPolicy=(policy:CompetitionDistributionPolicy):void=>{if(policy.poolAmount<0||components(policy)>1.0001)throw new Error("Distribution policy exceeds its available competition pool");if(policy.version<1)throw new Error("Distribution policy version must be positive");};

export const calculateCompetitionDistribution=(input:{policy:CompetitionDistributionPolicy;standings:readonly DistributionStanding[]}):DistributionLine[]=>{validateDistributionPolicy(input.policy);const rows=[...input.standings].sort((a,b)=>a.position-b.position||a.clubId.localeCompare(b.clubId));if(!rows.length)return[];const result=new Map<EntityId,number>();const reasons=new Map<EntityId,string[]>();const add=(clubId:EntityId,amount:number,reason:string)=>{if(amount<=0)return;result.set(clubId,(result.get(clubId)??0)+Math.round(amount));reasons.set(clubId,[...(reasons.get(clubId)??[]),reason]);};const p=input.policy;add(rows[0]!.clubId,p.poolAmount*p.championPrize,"champion prize");if(rows[1])add(rows[1].clubId,p.poolAmount*p.runnerUpPrize,"runner-up prize");const placement=rows.filter((row)=>row.position>2);for(const row of placement)add(row.clubId,p.poolAmount*p.placementPrizes/Math.max(1,placement.length),`placement ${row.position}`);for(const row of rows)add(row.clubId,p.poolAmount*p.participationPayments/rows.length,"participation payment");for(const row of rows)add(row.clubId,p.poolAmount*p.equalSharePayments/rows.length,"equal-share payment");const performanceTotal=rows.reduce((sum,row)=>sum+Math.max(0,row.performance),0);if(performanceTotal)for(const row of rows)add(row.clubId,p.poolAmount*p.performanceSharePayments*Math.max(0,row.performance)/performanceTotal,"performance share");const audienceTotal=rows.reduce((sum,row)=>sum+Math.max(0,row.audience??0),0);if(audienceTotal)for(const row of rows)add(row.clubId,p.poolAmount*p.audienceShare*Math.max(0,row.audience??0)/audienceTotal,"audience share");for(const row of rows){if(row.youthEligible)add(row.clubId,p.poolAmount*p.youthDevelopmentIncentives,"youth-development incentive");if(row.womensEligible)add(row.clubId,p.poolAmount*p.womensFootballIncentives,"women's-football incentive");if(row.infrastructureEligible)add(row.clubId,p.poolAmount*p.infrastructureGrants,"infrastructure incentive");}return [...result.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([clubId,amount])=>({clubId,amount,reason:(reasons.get(clubId)??[]).join(", ")}));};

export const createDistributionPolicy=(db:GameDatabase,input:Omit<CompetitionDistributionPolicy,"id"|"status"|"provenanceStatus">):CompetitionDistributionPolicy=>{const policy={...input,id:createStableEntityId("competition-distribution-policy",`${input.competitionSeasonId}:${input.version}`),status:"PROPOSED" as const,provenanceStatus:"SIMULATION_ONLY" as const};validateDistributionPolicy(policy);new CompetitionDistributionRepository(db).upsertPolicy(policy);return policy;};

export const applyCompetitionDistribution=(db:GameDatabase,input:{policy:CompetitionDistributionPolicy;date:string;standings:readonly DistributionStanding[]}):CompetitionDistributionPayment[]=>{validateDistributionPolicy(input.policy);const repo=new CompetitionDistributionRepository(db);if(input.policy.status!=="APPROVED"&&input.policy.status!=="APPLIED")throw new Error("Distribution policy is not approved");const lines=calculateCompetitionDistribution(input);const existing=repo.payments(input.policy.id);if(existing.length)return existing;const account=new FederationGovernanceRepository(db).financialAccount(input.policy.federationId);const total=lines.reduce((sum,line)=>sum+line.amount,0);if(!account||account.cashBalance<total)throw new Error("Federation cannot afford the approved competition distribution");const payments:CompetitionDistributionPayment[]=[];for(const line of lines){const federationEntry=postFederationTransaction(db,{federationId:input.policy.federationId,date:input.date,category:"PRIZE_DISTRIBUTION",direction:"DEBIT",amount:line.amount,description:`${line.reason} distribution`,relatedEntityId:line.clubId,idempotencyKey:`distribution:${input.policy.id}:${line.clubId}:${line.reason}`});const clubEntry=postClubTransaction(db,{clubId:line.clubId,date:input.date,category:"PRIZE_MONEY",direction:"CREDIT",amount:line.amount,description:`Competition distribution: ${line.reason}`,relatedEntityId:input.policy.competitionSeasonId,idempotencyKey:`distribution:${input.policy.id}:${line.clubId}:${line.reason}`});const payment={id:createStableEntityId("competition-distribution-payment",`${input.policy.id}:${line.clubId}:${line.reason}`),policyId:input.policy.id,competitionSeasonId:input.policy.competitionSeasonId,federationId:input.policy.federationId,clubId:line.clubId,amount:line.amount,reason:line.reason,paidOn:input.date,federationLedgerEntryId:federationEntry.id,clubLedgerEntryId:clubEntry.id,provenanceStatus:"SIMULATION_ONLY" as const};repo.insertPayment(payment);payments.push(payment);}repo.upsertPolicy({...input.policy,status:"APPLIED"});return payments;};
