import { createStableEntityId, type EntityId, type InsuranceClaim, type InsurancePolicy, type InsurerProfile } from "@nepal-football-sim/shared-types";
import { InsuranceRepository, type GameDatabase } from "@nepal-football-sim/database";
import { postClubTransaction } from "./club-economy.js";
import { postFederationTransaction } from "./federation-governance.js";

const covered=(policy:InsurancePolicy,event:InsuranceClaim["eventType"]):boolean=>({MATCH_INJURY:policy.coverage.matchInjury,TRAINING_INJURY:policy.coverage.trainingInjury,REHABILITATION:policy.coverage.rehabilitation,MAJOR_TREATMENT:policy.coverage.majorTreatment,TRAVEL:policy.coverage.travel,NATIONAL_TEAM_DUTY:policy.coverage.nationalTeamDuty,CAREER_ENDING:policy.coverage.careerEnding})[event];
export const quoteInsurancePolicy=(input:{ownerType:InsurancePolicy["ownerType"];ownerId:EntityId;insurer:InsurerProfile;coverage:InsurancePolicy["coverage"];startDate:string;endDate:string;riskScore:number}):InsurancePolicy=>{const coverageCount=Object.values(input.coverage).filter(Boolean).length;const premium=Math.round(Math.max(10000,coverageCount*input.insurer.premiumLevel*180+(input.riskScore*input.insurer.premiumLevel*12)));return {id:createStableEntityId("insurance-policy",`${input.ownerType}:${input.ownerId}:${input.insurer.id}:${input.startDate}`),ownerType:input.ownerType,ownerId:input.ownerId,insurerId:input.insurer.id,coverage:input.coverage,premium,deductible:Math.round(premium*.15),coverageCap:Math.round(premium*18),startDate:input.startDate,endDate:input.endDate,status:"QUOTED",provenanceStatus:"SIMULATION_ONLY"};};
export const saveInsurancePolicy=(db:GameDatabase,policy:InsurancePolicy):InsurancePolicy=>{new InsuranceRepository(db).upsertPolicy(policy);return policy;};
export const activateInsurancePolicy=(db:GameDatabase,policyId:EntityId):InsurancePolicy=>{const repo=new InsuranceRepository(db);const policy=repo.policy(policyId);if(!policy||!["QUOTED","NEGOTIATED","RENEWED"].includes(policy.status))throw new Error("Insurance policy is not ready for activation");if(policy.ownerType==="CLUB")postClubTransaction(db,{clubId:policy.ownerId,date:policy.startDate,category:"MEDICAL",direction:"DEBIT",amount:policy.premium,description:"Insurance premium",relatedEntityId:policy.id,idempotencyKey:`insurance-premium:${policy.id}`});else postFederationTransaction(db,{federationId:policy.ownerId,date:policy.startDate,category:"NATIONAL_TEAM_COST",direction:"DEBIT",amount:policy.premium,description:"Insurance premium",relatedEntityId:policy.id,idempotencyKey:`insurance-premium:${policy.id}`});const active={...policy,status:"ACTIVE" as const};repo.upsertPolicy(active);return active;};
export const openInsuranceClaim=(db:GameDatabase,input:{policyId:EntityId;injuryId:EntityId;eventType:InsuranceClaim["eventType"];incurredCost:number;openedOn:string}):InsuranceClaim=>{const repo=new InsuranceRepository(db);const policy=repo.policy(input.policyId);if(!policy||policy.status!=="ACTIVE"||input.openedOn<policy.startDate||input.openedOn>policy.endDate)throw new Error("Insurance policy is not active for this event");if(!db.prepare("SELECT id FROM injuries WHERE id=?").get(input.injuryId))throw new Error("Insurance claim requires a persisted injury event");if(!covered(policy,input.eventType))throw new Error("The policy does not cover this claim type");const person=(db.prepare("SELECT person_id FROM injuries WHERE id=?").get(input.injuryId) as {person_id?:EntityId});if(!person?.person_id)throw new Error("Injury claimant is missing");const claim:InsuranceClaim={id:createStableEntityId("insurance-claim",`${policy.id}:${input.injuryId}:${input.eventType}`),policyId:policy.id,injuryId:input.injuryId,personId:person.person_id,eventType:input.eventType,incurredCost:Math.max(0,Math.round(input.incurredCost)),eligibleAmount:0,status:"OPENED",openedOn:input.openedOn,provenanceStatus:"SIMULATION_ONLY"};repo.upsertClaim(claim);return claim;};
export const reviewInsuranceClaim=(db:GameDatabase,claimId:EntityId,reviewedOn:string):InsuranceClaim=>{const repo=new InsuranceRepository(db);const claim=repo.claims().find((item)=>item.id===claimId);if(!claim)throw new Error("Insurance claim missing");if(claim.status!=="OPENED")return claim;const policy=repo.policy(claim.policyId);if(!policy||!covered(policy,claim.eventType))throw new Error("Claim coverage is no longer valid");const eligible=Math.min(policy.coverageCap,Math.max(0,claim.incurredCost-policy.deductible));const status:InsuranceClaim["status"]=eligible<=0?"REJECTED":eligible<claim.incurredCost?"PARTIALLY_APPROVED":"APPROVED";const reviewed={...claim,eligibleAmount:eligible,status,reviewedOn,decisionReason:status==="REJECTED"?"Deductible exceeds covered cost":status==="PARTIALLY_APPROVED"?"Coverage cap or deductible limits settlement":"Covered injury event accepted"};repo.upsertClaim(reviewed);return reviewed;};
export const payInsuranceClaim=(db:GameDatabase,claimId:EntityId,paidOn:string):InsuranceClaim=>{const repo=new InsuranceRepository(db);const claim=repo.claims().find((item)=>item.id===claimId);if(!claim||!["APPROVED","PARTIALLY_APPROVED"].includes(claim.status))throw new Error("Insurance claim is not payable");if(claim.status==="PAID")return claim;const policy=repo.policy(claim.policyId);if(!policy)throw new Error("Insurance policy missing");let ledgerEntryId:EntityId;if(policy.ownerType==="CLUB")ledgerEntryId=postClubTransaction(db,{clubId:policy.ownerId,date:paidOn,category:"MEDICAL",direction:"CREDIT",amount:claim.eligibleAmount,description:"Insurance claim payout",relatedEntityId:claim.id,idempotencyKey:`insurance-claim:${claim.id}`}).id;else ledgerEntryId=postFederationTransaction(db,{federationId:policy.ownerId,date:paidOn,category:"NATIONAL_TEAM_COST",direction:"CREDIT",amount:claim.eligibleAmount,description:"Insurance claim payout",relatedEntityId:claim.id,idempotencyKey:`insurance-claim:${claim.id}`}).id;const paid={...claim,status:"PAID" as const,paidOn,ledgerEntryId};repo.upsertClaim(paid);return paid;};
