import { createStableEntityId, type EntityId, type InsuranceClaim, type InsurancePolicy, type InsurerProfile } from "@nepal-football-sim/shared-types";
import { ClubEconomyRepository, EventRepository, FederationGovernanceRepository, InsuranceRepository, type GameDatabase } from "@nepal-football-sim/database";
import type { InjuryRecord } from "@nepal-football-sim/shared-types";
import { postClubTransaction } from "./club-economy.js";
import { postFederationTransaction } from "./federation-governance.js";

const covered=(policy:InsurancePolicy,event:InsuranceClaim["eventType"]):boolean=>({MATCH_INJURY:policy.coverage.matchInjury,TRAINING_INJURY:policy.coverage.trainingInjury,REHABILITATION:policy.coverage.rehabilitation,MAJOR_TREATMENT:policy.coverage.majorTreatment,TRAVEL:policy.coverage.travel,NATIONAL_TEAM_DUTY:policy.coverage.nationalTeamDuty,CAREER_ENDING:policy.coverage.careerEnding})[event];
export const isInsurancePolicyActiveForDate=(policy:InsurancePolicy,date:string):boolean=>policy.status==="ACTIVE"&&policy.startDate<=date&&date<=policy.endDate;
export const quoteInsurancePolicy=(input:{ownerType:InsurancePolicy["ownerType"];ownerId:EntityId;insurer:InsurerProfile;coverage:InsurancePolicy["coverage"];startDate:string;endDate:string;riskScore:number}):InsurancePolicy=>{const coverageCount=Object.values(input.coverage).filter(Boolean).length;const premium=Math.round(Math.max(10000,coverageCount*input.insurer.premiumLevel*180+(input.riskScore*input.insurer.premiumLevel*12)));return {id:createStableEntityId("insurance-policy",`${input.ownerType}:${input.ownerId}:${input.insurer.id}:${input.startDate}`),ownerType:input.ownerType,ownerId:input.ownerId,insurerId:input.insurer.id,coverage:input.coverage,premium,deductible:Math.round(premium*.15),coverageCap:Math.round(premium*18),startDate:input.startDate,endDate:input.endDate,status:"QUOTED",provenanceStatus:"SIMULATION_ONLY"};};
export const saveInsurancePolicy=(db:GameDatabase,policy:InsurancePolicy):InsurancePolicy=>{new InsuranceRepository(db).upsertPolicy(policy);return policy;};
export const activateInsurancePolicy=(db:GameDatabase,policyId:EntityId):InsurancePolicy=>{const repo=new InsuranceRepository(db);const policy=repo.policy(policyId);if(!policy||!["QUOTED","NEGOTIATED","RENEWED"].includes(policy.status))throw new Error("Insurance policy is not ready for activation");if(policy.ownerType==="CLUB"){const economy=new ClubEconomyRepository(db);const account=economy.financialAccount(policy.ownerId);const reserve=account&&["DISTRESSED","INSOLVENT"].includes(account.financialHealth)?0:250000;if(!account||account.cashBalance-policy.premium<reserve)throw new Error("Club cannot afford insurance premium");const overlap=repo.policies(policy.ownerId).some((item)=>item.id!==policy.id&&["QUOTED","NEGOTIATED","ACTIVE","RENEWED"].includes(item.status)&&item.startDate<=policy.endDate&&policy.startDate<=item.endDate);if(overlap)throw new Error("Club already has overlapping insurance coverage");postClubTransaction(db,{clubId:policy.ownerId,date:policy.startDate,category:"MEDICAL",direction:"DEBIT",amount:policy.premium,description:"Insurance premium",relatedEntityId:policy.id,idempotencyKey:`insurance-premium:${policy.id}`});}else postFederationTransaction(db,{federationId:policy.ownerId,date:policy.startDate,category:"NATIONAL_TEAM_COST",direction:"DEBIT",amount:policy.premium,description:"Insurance premium",relatedEntityId:policy.id,idempotencyKey:`insurance-premium:${policy.id}`});const active={...policy,status:"ACTIVE" as const};repo.upsertPolicy(active);const historyId=createStableEntityId("historical-event",`insurance-policy:${active.id}:activated`);if(!db.prepare("SELECT 1 FROM historical_events WHERE id=?").get(historyId))new EventRepository(db).insertHistoricalEvent({id:historyId,occurredOn:policy.startDate,eventType:policy.status==="RENEWED"?"INSURANCE_POLICY_RENEWED":"INSURANCE_POLICY_ACTIVATED",involvedEntities:[{id:policy.ownerId,type:policy.ownerType==="CLUB"?"club":"federation"}],title:policy.status==="RENEWED"?"Insurance policy renewed":"Insurance policy activated",data:{policyId:policy.id,insurerId:policy.insurerId,premium:policy.premium,startDate:policy.startDate,endDate:policy.endDate},importance:"medium",scope:policy.ownerType==="CLUB"?"club":"federation"});return active;};
export const openInsuranceClaim=(db:GameDatabase,input:{policyId:EntityId;injuryId:EntityId;eventType:InsuranceClaim["eventType"];incurredCost:number;openedOn:string}):InsuranceClaim=>{const repo=new InsuranceRepository(db);const claimId=createStableEntityId("insurance-claim",`${input.policyId}:${input.injuryId}:${input.eventType}`);const existing=repo.claims().find((item)=>item.id===claimId);if(existing)return existing;const policy=repo.policy(input.policyId);if(!policy||!isInsurancePolicyActiveForDate(policy,input.openedOn))throw new Error("Insurance policy is not active for this event");if(!db.prepare("SELECT id FROM injuries WHERE id=?").get(input.injuryId))throw new Error("Insurance claim requires a persisted injury event");if(!covered(policy,input.eventType))throw new Error("The policy does not cover this claim type");const person=(db.prepare("SELECT person_id FROM injuries WHERE id=?").get(input.injuryId) as {person_id?:EntityId});if(!person?.person_id)throw new Error("Injury claimant is missing");const claim:InsuranceClaim={id:claimId,policyId:policy.id,injuryId:input.injuryId,personId:person.person_id,eventType:input.eventType,incurredCost:Math.max(0,Math.round(input.incurredCost)),eligibleAmount:0,status:"OPENED",openedOn:input.openedOn,provenanceStatus:"SIMULATION_ONLY"};repo.upsertClaim(claim);return claim;};
export const reviewInsuranceClaim=(db:GameDatabase,claimId:EntityId,reviewedOn:string):InsuranceClaim=>{const repo=new InsuranceRepository(db);const claim=repo.claims().find((item)=>item.id===claimId);if(!claim)throw new Error("Insurance claim missing");if(claim.status!=="OPENED")return claim;const policy=repo.policy(claim.policyId);if(!policy||!covered(policy,claim.eventType))throw new Error("Claim coverage is no longer valid");const eligible=Math.min(policy.coverageCap,Math.max(0,claim.incurredCost-policy.deductible));const status:InsuranceClaim["status"]=eligible<=0?"REJECTED":eligible<claim.incurredCost?"PARTIALLY_APPROVED":"APPROVED";const reviewed={...claim,eligibleAmount:eligible,status,reviewedOn,decisionReason:status==="REJECTED"?"Deductible exceeds covered cost":status==="PARTIALLY_APPROVED"?"Coverage cap or deductible limits settlement":"Covered injury event accepted"};repo.upsertClaim(reviewed);return reviewed;};
export const payInsuranceClaim=(db:GameDatabase,claimId:EntityId,paidOn:string):InsuranceClaim=>{const repo=new InsuranceRepository(db);const claim=repo.claims().find((item)=>item.id===claimId);if(!claim)throw new Error("Insurance claim is not payable");if(claim.status==="PAID")return claim;if(!["APPROVED","PARTIALLY_APPROVED"].includes(claim.status))throw new Error("Insurance claim is not payable");const policy=repo.policy(claim.policyId);if(!policy)throw new Error("Insurance policy missing");let ledgerEntryId:EntityId;if(policy.ownerType==="CLUB")ledgerEntryId=postClubTransaction(db,{clubId:policy.ownerId,date:paidOn,category:"MEDICAL",direction:"CREDIT",amount:claim.eligibleAmount,description:"Insurance claim payout",relatedEntityId:claim.id,idempotencyKey:`insurance-claim:${claim.id}`}).id;else ledgerEntryId=postFederationTransaction(db,{federationId:policy.ownerId,date:paidOn,category:"NATIONAL_TEAM_COST",direction:"CREDIT",amount:claim.eligibleAmount,description:"Insurance claim payout",relatedEntityId:claim.id,idempotencyKey:`insurance-claim:${claim.id}`}).id;const paid={...claim,status:"PAID" as const,paidOn,ledgerEntryId};repo.upsertClaim(paid);const historyId=createStableEntityId("historical-event",`insurance-claim:${claim.id}`);if(!db.prepare("SELECT 1 FROM historical_events WHERE id=?").get(historyId))new EventRepository(db).insertHistoricalEvent({id:historyId,occurredOn:paidOn,eventType:"INJURY_INSURANCE_CLAIM_SETTLED",involvedEntities:[{id:claim.personId,type:"person"},{id:policy.ownerId,type:policy.ownerType==="CLUB"?"club":"federation"}],title:"Injury insurance claim settled",data:{injuryId:claim.injuryId,policyId:policy.id,beneficiary:policy.ownerId,amount:claim.eligibleAmount},importance:"medium",scope:policy.ownerType==="CLUB"?"club":"federation"});return paid;};

const injuryDays=(injury:InjuryRecord):number=>Math.max(1,Math.round((Date.parse(`${injury.expectedRecoveryDate}T00:00:00Z`)-Date.parse(`${injury.dateOccurred}T00:00:00Z`))/86400000)+1);
const injuryCost=(injury:InjuryRecord):number=>injuryDays(injury)*({minor:1,moderate:2,major:3}[injury.severity]??1)*1500;

/** Settles only an existing club policy for a qualifying persisted match injury. */
export const settleMatchInjuryInsurance=(db:GameDatabase,input:{clubId:EntityId;injury:InjuryRecord;date:string}):InsuranceClaim|undefined=>{if(input.injury.severity==="minor")return undefined;const policy=new InsuranceRepository(db).policies(input.clubId).find((item)=>isInsurancePolicyActiveForDate(item,input.date)&&item.coverage.matchInjury);if(!policy)return undefined;const opened=openInsuranceClaim(db,{policyId:policy.id,injuryId:input.injury.id,eventType:"MATCH_INJURY",incurredCost:injuryCost(input.injury),openedOn:input.date});const reviewed=reviewInsuranceClaim(db,opened.id,input.date);return ["APPROVED","PARTIALLY_APPROVED"].includes(reviewed.status)?payInsuranceClaim(db,reviewed.id,input.date):reviewed;};

/** Federation medical assistance covers only the residual of a severe injury. */
export const settleFederationInjuryWelfare=(db:GameDatabase,input:{clubId:EntityId;injury:InjuryRecord;date:string;insuranceClaim?:InsuranceClaim}):number=>{if(input.injury.severity!=="major")return 0;const federation=(db.prepare("SELECT f.id FROM federations f JOIN clubs c ON c.country_id=f.country_id JOIN countries co ON co.id=c.country_id WHERE c.id=? AND co.id = (SELECT country_id FROM home_football_country LIMIT 1) ORDER BY f.id LIMIT 1").get(input.clubId) as {id?:EntityId}|undefined)?.id;if(!federation)return 0;const supportId=createStableEntityId("federation-welfare-support",`${federation}:${input.injury.id}:SEVERE_INJURY`);const existing=db.prepare("SELECT id,amount FROM federation_ledger_entries WHERE id=?").get(createStableEntityId("federation-ledger-entry",`${federation}:${input.date}:MEDICAL:DEBIT:federation-welfare:${supportId}`)) as {id?:EntityId;amount?:number}|undefined;if(existing?.id)return 0;const account=new FederationGovernanceRepository(db).financialAccount(federation);const basis=Math.max(0,injuryCost(input.injury)-(input.insuranceClaim?.eligibleAmount??0));const amount=Math.min(250000,basis);const reserve=account&&["DISTRESSED","INSOLVENT"].includes(account.financialHealth)?0:1500000;if(!account||amount<=0||account.cashBalance-amount<reserve)return 0;const federationEntry=postFederationTransaction(db,{federationId:federation,date:input.date,category:"MEDICAL",direction:"DEBIT",amount,description:"Federation severe-injury welfare support",relatedEntityId:input.clubId,idempotencyKey:`federation-welfare:${supportId}`});postClubTransaction(db,{clubId:input.clubId,date:input.date,category:"GRANT",direction:"CREDIT",amount,description:"Federation severe-injury welfare support",relatedEntityId:federation,idempotencyKey:`federation-welfare:${supportId}`});const historyId=createStableEntityId("historical-event",`federation-welfare:${supportId}`);if(!db.prepare("SELECT 1 FROM historical_events WHERE id=?").get(historyId))new EventRepository(db).insertHistoricalEvent({id:historyId,occurredOn:input.date,eventType:"FEDERATION_WELFARE_SUPPORT_GRANTED",involvedEntities:[{id:federation,type:"federation"},{id:input.clubId,type:"club"},{id:input.injury.personId,type:"person"}],title:"Federation severe-injury welfare support granted",data:{sourceEventId:input.injury.id,programme:"SEVERE_INJURY",beneficiary:input.clubId,amount,insuranceCovered:input.insuranceClaim?.eligibleAmount??0,federationLedgerEntryId:federationEntry.id},importance:"medium",scope:"federation"});return amount;};

const addDays=(date:string,days:number):string=>{const value=new Date(`${date}T00:00:00Z`);value.setUTCDate(value.getUTCDate()+days);return value.toISOString().slice(0,10);};
const policyHistory=(db:GameDatabase,policy:InsurancePolicy,date:string,eventType:"INSURANCE_POLICY_EXPIRED"):void=>{const id=createStableEntityId("historical-event",`insurance-policy:${policy.id}:${eventType}`);if(!db.prepare("SELECT 1 FROM historical_events WHERE id=?").get(id))new EventRepository(db).insertHistoricalEvent({id,occurredOn:date,eventType,involvedEntities:[{id:policy.ownerId,type:policy.ownerType==="CLUB"?"club":"federation"}],title:"Insurance policy expired",data:{policyId:policy.id,endDate:policy.endDate},importance:"medium",scope:policy.ownerType==="CLUB"?"club":"federation"});};

/** Annual club-planning lifecycle: expire old terms and make one bounded AI renewal decision. */
export const manageClubInsuranceForSeason=(db:GameDatabase,input:{clubId:EntityId;date:string}):InsurancePolicy|undefined=>{const repo=new InsuranceRepository(db);const policies=repo.policies(input.clubId);for(const policy of policies)if(policy.status==="ACTIVE"&&policy.endDate<input.date){const expired={...policy,status:"EXPIRED" as const};repo.upsertPolicy(expired);policyHistory(db,expired,input.date,"INSURANCE_POLICY_EXPIRED");}const current=repo.policies(input.clubId).find((policy)=>isInsurancePolicyActiveForDate(policy,input.date));if(current)return current;const account=new ClubEconomyRepository(db).financialAccount(input.clubId);if(!account||["DISTRESSED","INSOLVENT"].includes(account.financialHealth))return undefined;const insurer:InsurerProfile={id:createStableEntityId("insurer-profile","nepal-club-medical"),name:"Nepal Club Medical Pool",financialStrength:72,reliability:74,premiumLevel:100,coverageQuality:68,exclusions:[],claimReputation:70,provenanceStatus:"SIMULATION_ONLY"};repo.upsertInsurer(insurer);const previous=repo.policies(input.clubId).sort((a,b)=>b.startDate.localeCompare(a.startDate))[0];const quoted=quoteInsurancePolicy({ownerType:"CLUB",ownerId:input.clubId,insurer,coverage:{matchInjury:true,trainingInjury:false,rehabilitation:false,majorTreatment:false,travel:false,nationalTeamDuty:false,careerEnding:false},startDate:input.date,endDate:addDays(input.date,364),riskScore:40});const policy={...quoted,status:previous?.status==="EXPIRED"?"RENEWED" as const:"QUOTED" as const};saveInsurancePolicy(db,policy);try{return activateInsurancePolicy(db,policy.id);}catch{return undefined;}};
