import { createStableEntityId, type EntityId, type NationalTeamAppearance, type NationalTeamCallup, type NationalTeamCompensationPayment, type NationalTeamCompensationPolicy } from "@nepal-football-sim/shared-types";
import { FederationGovernanceRepository, NationalTeamCompensationRepository, type GameDatabase } from "@nepal-football-sim/database";
import { postFederationTransaction } from "./federation-governance.js";

export type CompensationEvent={eventId:EntityId;date:string;appearances:readonly NationalTeamAppearance[];callups:readonly NationalTeamCallup[];win:boolean;draw:boolean;qualified:boolean;tournamentPerformance?:number};
export const calculateNationalTeamCompensation=(policy:NationalTeamCompensationPolicy,event:CompensationEvent):Array<{playerId:EntityId;paymentType:string;amount:number}>=>(()=>{const selected=event.callups.filter((item)=>item.status==="CALLED_UP");const result:Array<{playerId:EntityId;paymentType:string;amount:number}>=[];for(const callup of selected){const appearance=event.appearances.find((item)=>item.playerId===callup.playerId);const add=(paymentType:string,amount:number)=>{if(amount>0)result.push({playerId:callup.playerId,paymentType,amount});};add("appearance_fee",appearance?policy.appearanceFee:0);add("win_bonus",event.win&&appearance?policy.winBonus:0);add("draw_bonus",event.draw&&appearance?policy.drawBonus:0);add("travel_allowance",policy.travelAllowance);add("camp_allowance",policy.campAllowance);add("qualification_bonus",event.qualified&&appearance?policy.qualificationBonus:0);add("tournament_participation_bonus",appearance&&policy.tournamentParticipationBonus>0?policy.tournamentParticipationBonus:0);add("tournament_performance_bonus",appearance?Math.round(policy.tournamentPerformanceBonus*(event.tournamentPerformance??0)/100):0);}return result;})();

export const createCompensationPolicy=(db:GameDatabase,input:Omit<NationalTeamCompensationPolicy,"id"|"status"|"provenanceStatus">):NationalTeamCompensationPolicy=>{if(Object.values(input).some((value)=>typeof value==="number"&&value<0))throw new Error("Compensation values cannot be negative");const policy={...input,id:createStableEntityId("national-team-compensation-policy",`${input.federationId}:${input.programme}:${input.version}`),status:"PROPOSED" as const,provenanceStatus:"SIMULATION_ONLY" as const};new NationalTeamCompensationRepository(db).upsertPolicy(policy);return policy;};
export const approveCompensationPolicy=(db:GameDatabase,policyId:EntityId,expectedPlayers:number,months:number):NationalTeamCompensationPolicy=>{const repo=new NationalTeamCompensationRepository(db);const policy=repo.policy(policyId);if(!policy)throw new Error("Compensation policy missing");const account=new FederationGovernanceRepository(db).financialAccount(policy.federationId);const estimate=expectedPlayers*(policy.monthlyRetainer*months+policy.travelAllowance+policy.campAllowance+policy.appearanceFee*4+policy.winBonus*2);if(!account||account.cashBalance<estimate)throw new Error("Federation cannot afford compensation policy");const approved={...policy,status:"APPROVED" as const};repo.upsertPolicy(approved);return approved;};
export const activateCompensationPolicy=(db:GameDatabase,policyId:EntityId):NationalTeamCompensationPolicy=>{const repo=new NationalTeamCompensationRepository(db);const policy=repo.policy(policyId);if(!policy||policy.status!=="APPROVED")throw new Error("Compensation policy is not approved");const active={...policy,status:"ACTIVE" as const};repo.upsertPolicy(active);return active;};
export const payNationalTeamCompensation=(db:GameDatabase,input:{policyId:EntityId;event:CompensationEvent}):NationalTeamCompensationPayment[]=>{const repo=new NationalTeamCompensationRepository(db);const policy=repo.policy(input.policyId);if(!policy||policy.status!=="ACTIVE")throw new Error("Compensation policy is not active");const lines=calculateNationalTeamCompensation(policy,input.event);if(repo.payments(policy.id).some((item)=>item.eventId===input.event.eventId))return repo.payments(policy.id).filter((item)=>item.eventId===input.event.eventId);const account=new FederationGovernanceRepository(db).financialAccount(policy.federationId);const total=lines.reduce((sum,line)=>sum+line.amount,0);const canPay=Boolean(account&&account.cashBalance>=total);const payments:NationalTeamCompensationPayment[]=[];for(const line of lines){let federationLedgerEntryId:EntityId|undefined;if(canPay)federationLedgerEntryId=postFederationTransaction(db,{federationId:policy.federationId,date:input.event.date,category:"PLAYER_ALLOWANCES",direction:"DEBIT",amount:line.amount,description:`National-team ${line.paymentType.replaceAll("_"," ")}`,relatedEntityId:input.event.eventId,idempotencyKey:`national-compensation:${policy.id}:${input.event.eventId}:${line.playerId}:${line.paymentType}`}).id;const payment={id:createStableEntityId("national-team-payment",`${policy.id}:${input.event.eventId}:${line.playerId}:${line.paymentType}`),policyId:policy.id,federationId:policy.federationId,nationalTeamId:input.event.callups.find((item)=>item.playerId===line.playerId)!.nationalTeamId,playerId:line.playerId,paymentType:line.paymentType,amount:line.amount,eventId:input.event.eventId,paidOn:input.event.date,status:canPay?"PAID" as const:"DEFERRED" as const,federationLedgerEntryId,provenanceStatus:"SIMULATION_ONLY" as const};repo.insertPayment(payment);payments.push(payment);}return payments;};
