import { ClubEconomyRepository, OwnershipRepository, type GameDatabase } from "@nepal-football-sim/database";
import { createStableEntityId, type ClubOwnershipModel, type ClubOwnershipStake, type EntityId, type OwnershipAcquisitionOffer, type OwnershipAcquisitionTransaction } from "@nepal-football-sim/shared-types";
import { calculateClubValuation } from "./club-economy.js";

const status = "SIMULATION_ONLY" as const;
const clamp = (value: number, low: number, high: number): number => Math.max(low, Math.min(high, value));

export const calculateAcquisitionValuation = (db: GameDatabase, clubId: EntityId, date: string) => {
  const base = calculateClubValuation(db, clubId, date).valuation; const economy = new ClubEconomyRepository(db); const supporters = economy.supporterProfile(clubId); const commercial = economy.commercialProfile(clubId); const facility = economy.facilityProfile(clubId); const competitions = Number((db.prepare("SELECT COUNT(*) AS count FROM club_memberships WHERE club_id = ? AND status IN ('ACTIVE','QUALIFIED','PROMOTED')").get(clubId) as { count?: number })?.count ?? 0); const supportValue = ((supporters?.coreSupporters ?? 0) + (supporters?.casualSupporters ?? 0) * 0.4 + (supporters?.diasporaSupport ?? 0) * 0.7) * 40; const commercialValue = ((commercial?.brandStrength ?? 0) + (commercial?.digitalReach ?? 0)) * 80000; const facilityValue = ((facility?.trainingFacilityQuality ?? 0) + (facility?.youthFacilityQuality ?? 0) + (facility?.medicalFacilityQuality ?? 0)) * 50000; return Math.max(250000, Math.round(base + supportValue + commercialValue + facilityValue + competitions * 100000));
};

export const createOwnershipEnquiry = (db: GameDatabase, input: { clubId: EntityId; buyerPersonId: EntityId; percentage: number; date: string }): OwnershipAcquisitionOffer => {
  if (input.percentage <= 0 || input.percentage > 100) throw new Error("Ownership percentage is invalid"); if (!db.prepare("SELECT 1 FROM clubs WHERE id = ?").get(input.clubId)) throw new Error("Club does not exist"); const value: OwnershipAcquisitionOffer = { id: createStableEntityId("ownership-offer", `${input.clubId}:${input.buyerPersonId}:${input.date}:${input.percentage}`), clubId: input.clubId, buyerPersonId: input.buyerPersonId, percentage: input.percentage, offerAmount: 0, status: "ENQUIRY", createdOn: input.date, provenanceStatus: status }; new OwnershipRepository(db).upsertOffer(value); return value;
};

export const submitOwnershipOffer = (db: GameDatabase, input: { enquiryId: EntityId; amount: number; date: string }): OwnershipAcquisitionOffer => {
  const repo = new OwnershipRepository(db); const enquiry = repo.offer(input.enquiryId); if (!enquiry || enquiry.status !== "ENQUIRY") throw new Error("Ownership enquiry is unavailable"); if (input.amount <= 0) throw new Error("Ownership offer must be positive"); const value = { ...enquiry, offerAmount: Math.round(input.amount), status: "OFFER" as const, createdOn: enquiry.createdOn }; repo.upsertOffer(value); return value;
};

export const counterOwnershipOffer = (db: GameDatabase, input: { offerId: EntityId; amount: number; date: string }): OwnershipAcquisitionOffer => {
  const repo = new OwnershipRepository(db); const current = repo.offer(input.offerId); if (!current || !["OFFER", "COUNTER"].includes(current.status)) throw new Error("Ownership offer is unavailable"); const next = { ...current, counterAmount: Math.round(input.amount), status: "COUNTER" as const, rationale: "Existing owners requested terms closer to the club valuation." }; repo.upsertOffer(next); return next;
};

export const decideOwnershipOffer = (db: GameDatabase, input: { offerId: EntityId; date: string; accept?: boolean }): OwnershipAcquisitionOffer => {
  const repo = new OwnershipRepository(db); const current = repo.offer(input.offerId); if (!current || !["OFFER", "COUNTER"].includes(current.status)) throw new Error("Ownership offer is unavailable"); const amount = current.counterAmount ?? current.offerAmount; const club = db.prepare("SELECT ownership_type FROM clubs WHERE id = ?").get(current.clubId) as { ownership_type?: string } | undefined; const valuation = calculateAcquisitionValuation(db, current.clubId, input.date); const personal = new ClubEconomyRepository(db).personalFinancialProfile(current.buyerPersonId); const offered = input.accept !== false && (personal?.cash ?? 0) >= amount && amount >= Math.round(valuation * 0.85) && !(current.percentage > 49 && ["DEPARTMENTAL", "MUNICIPALITY_BACKED"].includes(club?.ownership_type ?? "")); const next = { ...current, status: offered ? "ACCEPTED" as const : "REJECTED" as const, decidedOn: input.date, rationale: offered ? "Owners accepted a financially credible offer." : "Owners declined because value, control, or ownership restrictions were not met." }; repo.upsertOffer(next); if (offered) completeAcquisition(db, next, amount, input.date); return next;
};

const completeAcquisition = (db: GameDatabase, offer: OwnershipAcquisitionOffer, amount: number, date: string): OwnershipAcquisitionTransaction => {
  const economy = new ClubEconomyRepository(db); const personal = economy.personalFinancialProfile(offer.buyerPersonId); if (!personal || personal.cash < amount) throw new Error("Personal cash is insufficient for acquisition"); const active = economy.ownershipStakes(offer.clubId).filter((stake) => stake.status === "ACTIVE"); const existing = active.find((stake) => stake.holderId === offer.buyerPersonId); const definedTotal = active.reduce((sum, stake) => sum + (stake.percentage ?? 0), 0) - (existing?.percentage ?? 0); const totalPercentage = (existing?.percentage ?? 0) + offer.percentage; if (definedTotal + totalPercentage > 100) throw new Error("Ownership percentage exceeds available shares"); const person = db.prepare("SELECT display_name, full_name FROM persons WHERE id = ?").get(offer.buyerPersonId) as { display_name?: string; full_name: string } | undefined; const model: ClubOwnershipModel = totalPercentage >= 51 ? "BUYABLE" : "PARTIALLY_BUYABLE"; const stake: ClubOwnershipStake = { id: createStableEntityId("ownership-stake", `${offer.clubId}:${offer.buyerPersonId}`), clubId: offer.clubId, holderType: "PERSON", holderId: offer.buyerPersonId, holderName: person?.display_name ?? person?.full_name ?? offer.buyerPersonId, role: totalPercentage >= 51 ? "MAJORITY_OWNER" : "MINORITY_OWNER", percentage: totalPercentage, votingPercentage: totalPercentage, startDate: existing?.startDate ?? date, status: "ACTIVE", ownershipModel: model, provenanceStatus: status }; economy.updatePersonalCash(offer.buyerPersonId, -amount, date); economy.upsertOwnershipStake(stake); if (totalPercentage >= 51) db.prepare("UPDATE clubs SET ownership_type = 'PRIVATE' WHERE id = ?").run(offer.clubId); const transaction: OwnershipAcquisitionTransaction = { id: createStableEntityId("ownership-transaction", offer.id), offerId: offer.id, clubId: offer.clubId, buyerPersonId: offer.buyerPersonId, sellerHolderId: offer.sellerHolderId, date, amount, percentage: offer.percentage, status: "POSTED", provenanceStatus: status }; new OwnershipRepository(db).insertTransaction(transaction); return transaction;
};

export const withdrawOwnershipOffer = (db: GameDatabase, offerId: EntityId, date: string): OwnershipAcquisitionOffer => { const repo = new OwnershipRepository(db); const current = repo.offer(offerId); if (!current || ["ACCEPTED", "REJECTED", "WITHDRAWN"].includes(current.status)) throw new Error("Ownership offer is unavailable"); const next = { ...current, status: "WITHDRAWN" as const, decidedOn: date }; repo.upsertOffer(next); return next; };
