import { createStableEntityId, type EntityId, type RefereeDevelopmentPathway, type RefereeDevelopmentProfile, type VarProgramme } from "@nepal-football-sim/shared-types";
import { RefereeDevelopmentRepository, type GameDatabase } from "@nepal-football-sim/database";

const clamp=(value:number):number=>Math.max(0,Math.min(100,Math.round(value)));
export const advanceRefereeDevelopment=(profile:RefereeDevelopmentProfile,programme:RefereeDevelopmentPathway):RefereeDevelopmentProfile=>{if(programme.status!=="ACTIVE"||programme.funding<=0)return profile;const rate=Math.min(1.5,0.25+(programme.staffingQuality/100)*0.75);return {...profile,currentQuality:clamp(profile.currentQuality+Math.min(rate,Math.max(0,profile.developmentPotential-profile.currentQuality))),fitness:clamp(profile.fitness+(programme.programmeType==="FITNESS_TESTING"?rate:rate*.2)),experience:clamp(profile.experience+(programme.programmeType==="DOMESTIC_PROGRESSION"?rate*.6:rate*.15)),consistency:clamp(profile.consistency+rate*.3),updatedOn:programme.endDate};};
export const createRefereeProgramme=(db:GameDatabase,input:Omit<RefereeDevelopmentPathway,"id"|"status"|"provenanceStatus">):RefereeDevelopmentPathway=>{const value={...input,id:createStableEntityId("referee-development-programme",`${input.federationId}:${input.programmeType}:${input.startDate}`),status:"PLANNED" as const,provenanceStatus:"SIMULATION_ONLY" as const};new RefereeDevelopmentRepository(db).upsertProgramme(value);return value;};
export const progressRefereeProgramme=(db:GameDatabase,input:{programmeId:EntityId;date:string}):RefereeDevelopmentProfile[]=>{const repo=new RefereeDevelopmentRepository(db);const programme=repo.programmes().find((item)=>item.id===input.programmeId);if(!programme)throw new Error("Referee programme missing");const active={...programme,status:"ACTIVE" as const};repo.upsertProgramme(active);const changed:RefereeDevelopmentProfile[]=[];for(const id of active.refereeProfileIds){const current=repo.profiles().find((item)=>item.id===id);if(!current)continue;const next=advanceRefereeDevelopment(current,active);repo.upsertProfile(next);changed.push(next);}return changed;};

export const assessVarReadiness=(programme:Pick<VarProgramme,"funding"|"trainedOfficials"|"compatibleStadiums"|"operationsCapacity">):{ready:boolean;missing:string[]}=>{const missing:string[]=[];if(programme.funding<=0)missing.push("funding");if(programme.trainedOfficials<2)missing.push("trained officials");if(programme.compatibleStadiums<1)missing.push("compatible stadiums");if(programme.operationsCapacity<1)missing.push("operations capacity");return {ready:missing.length===0,missing};};
export const createVarProgramme=(db:GameDatabase,input:Omit<VarProgramme,"id"|"status"|"provenanceStatus">):VarProgramme=>{const value={...input,id:createStableEntityId("var-programme",`${input.federationId}:${input.name}`),status:"FEASIBILITY" as const,provenanceStatus:"SIMULATION_ONLY" as const};new RefereeDevelopmentRepository(db).upsertVar(value);return value;};
export const advanceVarProgramme=(db:GameDatabase,input:{programmeId:EntityId;date:string;nextStatus:VarProgramme["status"]}):VarProgramme=>{const repo=new RefereeDevelopmentRepository(db);const current=repo.var(input.programmeId);if(!current)throw new Error("VAR programme missing");const allowed:Record<VarProgramme["status"],VarProgramme["status"][]>={FEASIBILITY:["APPROVED","SUSPENDED"],APPROVED:["PROCUREMENT","SUSPENDED"],PROCUREMENT:["TRAINING","SUSPENDED"],TRAINING:["PILOT","SUSPENDED"],PILOT:["ACTIVE","SUSPENDED"],ACTIVE:["SUSPENDED"],SUSPENDED:["FEASIBILITY"]};if(!allowed[current.status].includes(input.nextStatus))throw new Error("Invalid VAR programme transition");if(["PILOT","ACTIVE"].includes(input.nextStatus)&&!assessVarReadiness(current).ready)throw new Error("VAR prerequisites are incomplete");const next={...current,status:input.nextStatus,updatedOn:input.date};repo.upsertVar(next);return next;};
export const varMatchContext=(programme:VarProgramme,input:{stadiumId?:EntityId;competitionId?:EntityId;isFinal?:boolean}):{available:boolean;programmeId?:EntityId}=>{if(programme.status!=="ACTIVE"&&programme.status!=="PILOT")return {available:false};const scope=programme.scope==="SELECTED_STADIUMS"?(!!input.stadiumId&&programme.stadiumIds.includes(input.stadiumId)):programme.scope==="SELECTED_COMPETITIONS"||programme.scope==="FULL_COMPETITION"?(!!input.competitionId&&programme.competitionIds.includes(input.competitionId)):programme.scope==="FINALS"?Boolean(input.isFinal):true;return scope?{available:true,programmeId:programme.id}:{available:false};};
