import { createStableEntityId, type DistrictDevelopmentProject, type DistrictFootballUnit, type EntityId, type ProvinceFootballUnit, type TerritorialRepresentativeTeam } from "@nepal-football-sim/shared-types";
import { TerritorialFootballRepository, type GameDatabase } from "@nepal-football-sim/database";

const provinces: Array<[string, string[]]> = [["Koshi", ["Taplejung","Panchthar","Ilam","Jhapa","Morang","Sunsari","Dhankuta","Terhathum","Sankhuwasabha","Bhojpur","Solukhumbu","Okhaldhunga","Khotang","Udayapur"]],["Madhesh",["Saptari","Siraha","Dhanusha","Mahottari","Sarlahi","Rautahat","Bara","Parsa"]],["Bagmati",["Dolakha","Ramechhap","Sindhuli","Kavrepalanchok","Sindhupalchok","Rasuwa","Nuwakot","Dhading","Kathmandu","Bhaktapur","Lalitpur","Makwanpur","Chitwan"]],["Gandaki",["Gorkha","Manang","Mustang","Myagdi","Kaski","Lamjung","Tanahun","Syangja","Parbat","Baglung","Nawalpur"]],["Lumbini",["Rupandehi","Kapilvastu","Palpa","Arghakhanchi","Gulmi","Dang","Pyuthan","Rolpa","Rukum East","Banke","Bardiya","Nawalparasi West"]],["Karnali",["Dolpa","Humla","Jumla","Kalikot","Mugu","Surkhet","Dailekh","Jajarkot","Salyan","Rukum West"]],["Sudurpashchim",["Bajura","Bajhang","Doti","Achham","Kailali","Kanchanpur","Dadeldhura","Baitadi","Darchula"]]];
const clean = (value:string) => value.toLowerCase().replace(/ district| province|\s+/g, "");
const clamp = (value:number) => Math.max(0, Math.min(100, Math.round(value)));

export const initializeNepalTerritorialStructure = (db:GameDatabase, date:string): { districts:DistrictFootballUnit[]; provinces:ProvinceFootballUnit[] } => {
  const repo = new TerritorialFootballRepository(db); const locations = db.prepare("SELECT id,name FROM locations WHERE kind='district'").all() as Array<{id:EntityId;name:string}>; const byName = new Map(locations.map((location) => [clean(location.name), location])); const result: DistrictFootballUnit[] = [];
  for (const [provinceName, names] of provinces) { const provinceId = createStableEntityId("nepal-province", provinceName); const districts = names.map((name) => { const location = byName.get(clean(name)); const remoteness = ["Manang","Mustang","Dolpa","Humla","Mugu","Jumla","Kalikot","Bajura","Bajhang","Darchula","Solukhumbu"].includes(name) ? 80 : 35; const district:DistrictFootballUnit = { id:createStableEntityId("nepal-district",name), name, provinceId, locationId:location?.id, remoteness, developmentStatus:"DEVELOPING", affiliationStatus:location ? "UNKNOWN" : "DEVELOPING", developmentReputation:20, registeredClubCount:0, schoolParticipation:10, girlsParticipation:8, youthParticipation:12, coachSupply:10, refereeSupply:10, groundAvailability:25, scoutingVisibility:10, governanceCompliance:60, history:[{date,event:"TERRITORIAL_UNIT_INITIALISED",indicators:{schoolParticipation:10,youthParticipation:12}}], provenanceStatus:"SIMULATION_ONLY" }; repo.upsertDistrict(district); result.push(district); return district; }); const provincial:ProvinceFootballUnit = { id:provinceId,name:provinceName,districtIds:districts.map((district)=>district.id),footballStrength:10,infrastructure:20,playerProduction:10,competitionPerformance:10,fundingReceived:0,fundingSpent:0,history:[{date,event:"PROVINCIAL_UNIT_INITIALISED"}],provenanceStatus:"SIMULATION_ONLY" }; repo.upsertProvince(provincial); }
  return { districts:repo.districts(), provinces:repo.provinces() };
};

export const createDistrictDevelopmentProject = (db:GameDatabase, input:Omit<DistrictDevelopmentProject,"id"|"status"|"reportingStatus"|"provenanceStatus">):DistrictDevelopmentProject => { const project:DistrictDevelopmentProject = { ...input, id:createStableEntityId("district-project",`${input.districtId}:${input.projectType}:${input.createdOn}`), status:"PROPOSED", reportingStatus:"NOT_DUE", provenanceStatus:"SIMULATION_ONLY" }; new TerritorialFootballRepository(db).upsertProject(project); return project; };

export const advanceDistrictDevelopmentProject = (db:GameDatabase, projectId:EntityId, input:{date:string;status:DistrictDevelopmentProject["status"];reportingStatus?:DistrictDevelopmentProject["reportingStatus"];outcome?:string}):DistrictDevelopmentProject => { const repo=new TerritorialFootballRepository(db); const current=repo.project(projectId); if(!current) throw new Error(`District project ${projectId} not found`); const next={...current,status:input.status,reportingStatus:input.reportingStatus??current.reportingStatus,outcome:input.outcome??current.outcome}; repo.upsertProject(next); return next; };

export const updateDistrictDevelopment = (db:GameDatabase, input:{districtId:EntityId;date:string;funding:number;reportedWell?:boolean}):DistrictFootballUnit => { const repo=new TerritorialFootballRepository(db); const current=repo.district(input.districtId); if(!current) throw new Error(`District ${input.districtId} not found`); const delivery=input.reportedWell===false? -2 : Math.min(5,input.funding/100000); const next:DistrictFootballUnit={...current,developmentReputation:clamp(current.developmentReputation+delivery),schoolParticipation:clamp(current.schoolParticipation+delivery*.8),girlsParticipation:clamp(current.girlsParticipation+delivery*.6),youthParticipation:clamp(current.youthParticipation+delivery),coachSupply:clamp(current.coachSupply+delivery*.5),refereeSupply:clamp(current.refereeSupply+delivery*.4),groundAvailability:clamp(current.groundAvailability+delivery*.5),scoutingVisibility:clamp(current.scoutingVisibility+delivery*.7),governanceCompliance:clamp(current.governanceCompliance+(input.reportedWell===false?-5:1)),developmentStatus:current.developmentReputation+delivery>35?"ESTABLISHED":"DEVELOPING",history:[...current.history,{date:input.date,event:"DEVELOPMENT_REVIEW",indicators:{funding:input.funding,delayedEffect:Math.max(0,delivery)}}]}; repo.upsertDistrict(next); return next; };

export const createTerritorialRepresentativeTeam = (db:GameDatabase,input:{territoryType:"DISTRICT"|"PROVINCE";territoryId:EntityId;name:string;date:string}):TerritorialRepresentativeTeam=>{const team:TerritorialRepresentativeTeam={id:createStableEntityId("territorial-team",`${input.territoryType}:${input.territoryId}`),name:input.name,territoryType:input.territoryType,territoryId:input.territoryId,playerIds:[],status:"SIMULATION_ONLY",history:[{date:input.date,event:"REPRESENTATIVE_TEAM_CREATED",playerIds:[]}]};new TerritorialFootballRepository(db).upsertTeam(team);return team;};

export const selectTerritorialRepresentativePlayers = (db:GameDatabase,input:{teamId:EntityId;date:string;candidates:Array<{playerId:EntityId;eligible:boolean;ability:number;form:number;available:boolean;known:boolean}>;limit:number}):TerritorialRepresentativeTeam=>{const repo=new TerritorialFootballRepository(db);const team=repo.team(input.teamId);if(!team)throw new Error(`Territorial team ${input.teamId} not found`);const playerIds=input.candidates.filter((candidate)=>candidate.eligible&&candidate.available&&candidate.known).sort((a,b)=>b.ability+b.form-a.ability-a.form||a.playerId.localeCompare(b.playerId)).slice(0,input.limit).map((candidate)=>candidate.playerId);const next={...team,playerIds,history:[...team.history,{date:input.date,event:"SQUAD_SELECTED",playerIds}]};repo.upsertTeam(next);return next;};
