import { createStableEntityId, type CampDestination, type EntityId, type TrainingCamp, type TrainingCampParticipant } from "@nepal-football-sim/shared-types";
import { ClubEconomyRepository, FederationGovernanceRepository, TrainingCampRepository, type GameDatabase } from "@nepal-football-sim/database";
import { postClubTransaction } from "./club-economy.js";
import { postFederationTransaction } from "./federation-governance.js";

export const CAMP_DESTINATION_PROFILES:Readonly<Record<CampDestination,{facilityQuality:number;climateFit:number;oppositionAccess:number;travelBurden:number;logisticsDifficulty:number;commercialExposure:number;scoutingExposure:number}>>={NEPAL:{facilityQuality:45,climateFit:90,oppositionAccess:35,travelBurden:10,logisticsDifficulty:20,commercialExposure:10,scoutingExposure:15},INDIA:{facilityQuality:58,climateFit:82,oppositionAccess:65,travelBurden:25,logisticsDifficulty:30,commercialExposure:35,scoutingExposure:40},THAILAND:{facilityQuality:70,climateFit:68,oppositionAccess:72,travelBurden:45,logisticsDifficulty:40,commercialExposure:48,scoutingExposure:52},JAPAN:{facilityQuality:88,climateFit:55,oppositionAccess:86,travelBurden:65,logisticsDifficulty:60,commercialExposure:55,scoutingExposure:68},SOUTH_KOREA:{facilityQuality:84,climateFit:52,oppositionAccess:82,travelBurden:68,logisticsDifficulty:62,commercialExposure:50,scoutingExposure:65},QATAR_UAE:{facilityQuality:90,climateFit:48,oppositionAccess:75,travelBurden:70,logisticsDifficulty:58,commercialExposure:72,scoutingExposure:60},AUSTRALIA:{facilityQuality:86,climateFit:45,oppositionAccess:78,travelBurden:82,logisticsDifficulty:72,commercialExposure:65,scoutingExposure:74},EUROPE:{facilityQuality:92,climateFit:38,oppositionAccess:95,travelBurden:90,logisticsDifficulty:82,commercialExposure:80,scoutingExposure:90}};
const clamp=(value:number):number=>Math.max(-100,Math.min(100,Math.round(value)));
export const calculateCampEffects=(camp:{facilityQuality:number;climateFit:number;oppositionAccess:number;travelBurden:number;scoutingExposure:number;commercialExposure:number;duration?:number}):Record<string,number>=>{const duration=Math.max(1,camp.duration??7);const burden=Math.max(0,camp.travelBurden-(camp.climateFit*.25));const quality=(camp.facilityQuality*.35+camp.oppositionAccess*.25+camp.climateFit*.2+Math.min(100,duration*6)*.2)/100;return {tacticalFamiliarity:Number((quality*duration*.012).toFixed(4)),preparation:Number((quality*duration*.018-burden*.0008).toFixed(4)),cohesion:Number((quality*duration*.01-burden*.0005).toFixed(4)),scoutingExposure:Number((camp.scoutingExposure*duration*.001).toFixed(4)),commercialExposure:Number((camp.commercialExposure*duration*.001).toFixed(4)),developmentSignal:Number((quality*duration*.004).toFixed(4)),fatigueLoad:Number((burden*.012+duration*.004).toFixed(4))};};
const days=(start:string,end:string):number=>Math.max(1,Math.round((Date.parse(`${end}T00:00:00Z`)-Date.parse(`${start}T00:00:00Z`))/86400000)+1);
export const hasCampFixtureOverlap=(camp:Pick<TrainingCamp,"startDate"|"endDate">,fixtureDates:readonly string[]):boolean=>fixtureDates.some((date)=>date>=camp.startDate&&date<=camp.endDate);
export const createTrainingCamp=(db:GameDatabase,input:{ownerType:TrainingCamp["ownerType"];ownerId:EntityId;programmeType:TrainingCamp["programmeType"];destination:CampDestination;startDate:string;endDate:string;participantIds?:EntityId[];cost?:number}):TrainingCamp=>{const profile=CAMP_DESTINATION_PROFILES[input.destination];const duration=days(input.startDate,input.endDate);const camp:TrainingCamp={id:createStableEntityId("training-camp",`${input.ownerType}:${input.ownerId}:${input.destination}:${input.startDate}`),ownerType:input.ownerType,ownerId:input.ownerId,programmeType:input.programmeType,destination:input.destination,startDate:input.startDate,endDate:input.endDate,cost:Math.round(input.cost??(input.destination==="NEPAL"?18000:45000+profile.travelBurden*1200+duration*2500)),...profile,status:"PROPOSED",participantIds:input.participantIds??[],provenanceStatus:"SIMULATION_ONLY"};new TrainingCampRepository(db).upsert(camp);return camp;};
export const bookTrainingCamp=(db:GameDatabase,campId:EntityId):TrainingCamp=>{const repo=new TrainingCampRepository(db);const camp=repo.camp(campId);if(!camp||camp.status!=="PROPOSED"&&camp.status!=="NEGOTIATED_PLANNED")throw new Error("Training camp is not ready to book");const affordable=camp.ownerType==="CLUB"?((new ClubEconomyRepository(db).financialAccount(camp.ownerId)?.cashBalance??0)>=camp.cost):((new FederationGovernanceRepository(db).financialAccount(camp.ownerId)?.cashBalance??0)>=camp.cost);if(!affordable)throw new Error("Owner cannot afford training camp");if(camp.ownerType==="CLUB")postClubTransaction(db,{clubId:camp.ownerId,date:camp.startDate,category:"TRAVEL",direction:"DEBIT",amount:camp.cost,description:`Training camp in ${camp.destination}`,relatedEntityId:camp.id,idempotencyKey:`training-camp:${camp.id}`});else postFederationTransaction(db,{federationId:camp.ownerId,date:camp.startDate,category:"TRAVEL",direction:"DEBIT",amount:camp.cost,description:`Training camp in ${camp.destination}`,relatedEntityId:camp.id,idempotencyKey:`training-camp:${camp.id}`});const booked={...camp,status:"BOOKED" as const};repo.upsert(booked);for(const participantId of camp.participantIds){const effect=calculateCampEffects({...camp,duration:days(camp.startDate,camp.endDate)});const participant:TrainingCampParticipant={id:createStableEntityId("training-camp-participant",`${camp.id}:${participantId}`),campId:camp.id,participantId,participantType:camp.programmeType==="CLUB"||camp.programmeType==="NATIONAL_TEAM"||camp.programmeType==="WOMENS_TEAM"||camp.programmeType==="YOUTH_TEAM"?"PLAYER":"PLAYER",effectSummary:effect,provenanceStatus:"SIMULATION_ONLY"};repo.insertParticipant(participant);}return booked;};
export const advanceTrainingCamp=(db:GameDatabase,campId:EntityId,status:TrainingCamp["status"]):TrainingCamp=>{const repo=new TrainingCampRepository(db);const camp=repo.camp(campId);if(!camp)throw new Error("Training camp missing");const allowed:Record<TrainingCamp["status"],TrainingCamp["status"][]>={PROPOSED:["NEGOTIATED_PLANNED","CANCELLED"],NEGOTIATED_PLANNED:["BOOKED","CANCELLED"],BOOKED:["TRAVELLING","CANCELLED"],TRAVELLING:["ACTIVE","CANCELLED"],ACTIVE:["COMPLETED","CANCELLED"],COMPLETED:[],CANCELLED:[]};if(!allowed[camp.status].includes(status))throw new Error("Invalid training camp lifecycle transition");const next={...camp,status};repo.upsert(next);return next;};
