import { createStableEntityId, type EntityId, type InteractionAction, type InteractionTone, type UniversalInteraction } from "@nepal-football-sim/shared-types";
import { UniversalInteractionRepository, type GameDatabase } from "@nepal-football-sim/database";
import { SeededRandom } from "./rng.js";

const terminal = new Set(["ACCEPTED", "REJECTED", "WALKED_AWAY", "COMPLETED", "CANCELLED"]);
const clamp = (value:number) => Math.max(0, Math.min(100, Math.round(value)));
const actionsFor = (stage:UniversalInteraction["stage"]): InteractionAction[] => stage === "OPENED" ? ["STATE_POSITION","OFFER","DEFER","WALK_AWAY"] : stage === "POSITION_STATED" || stage === "COUNTERED" || stage === "NEGOTIATING" ? ["OFFER","COUNTER","ACCEPT","REJECT","DEFER","WALK_AWAY"] : [];
const toneEffect = (tone:InteractionTone):number => ({ CALM:2, SUPPORTIVE:4, ASSERTIVE:0, DEMANDING:-4, PERSUASIVE:3, CONCILIATORY:5, PROFESSIONAL:2 }[tone]);
const entityExists = (db:GameDatabase, type:UniversalInteraction["initiator"]["type"], id:EntityId):boolean => { const table = type === "PLAYER" || type === "MANAGER" || type === "STAFF" || type === "CHAIRMAN" || type === "FEDERATION_OFFICIAL" || type === "GOVERNMENT" ? "persons" : type === "AGENT" ? "agents" : type === "BOARD" ? "clubs" : type === "SPONSOR" ? "sponsors" : "persons"; return Boolean(db.prepare(`SELECT 1 FROM ${table} WHERE id=? LIMIT 1`).get(id)); };

export const openUniversalInteraction = (db:GameDatabase, input:{saveId?:EntityId;interactionType:string;initiator:UniversalInteraction["initiator"];counterpart:UniversalInteraction["counterpart"];organisationId?:EntityId;worldDate:string;subject:string;demands?:UniversalInteraction["demands"];offers?:UniversalInteraction["offers"];relationshipState?:number;leverage?:number;trust?:number;pressure?:number;deadline?:string}):UniversalInteraction => { if(!entityExists(db,input.initiator.type,input.initiator.entityId)||!entityExists(db,input.counterpart.type,input.counterpart.entityId)) throw new Error("Interaction participant does not exist in the canonical world model"); const id=createStableEntityId("universal-interaction",`${input.saveId??"save"}:${input.initiator.entityId}:${input.counterpart.entityId}:${input.interactionType}:${input.worldDate}:${input.subject}`); const session:UniversalInteraction={id,...input,demands:input.demands??{},offers:input.offers??{},promiseIds:[],relationshipState:clamp(input.relationshipState??50),leverage:clamp(input.leverage??50),patience:100,trust:clamp(input.trust??50),pressure:clamp(input.pressure??0),stage:"OPENED",availableActions:actionsFor("OPENED"),history:[],provenanceStatus:"SIMULATION_ONLY"}; new UniversalInteractionRepository(db).upsert(session); return session; };

export const availableUniversalInteractionActions = (db:GameDatabase,id:EntityId):InteractionAction[] => { const session=new UniversalInteractionRepository(db).session(id); if(!session) throw new Error(`Interaction ${id} not found`); return [...session.availableActions]; };
export const universalInteraction = (db:GameDatabase,id:EntityId):UniversalInteraction|undefined => new UniversalInteractionRepository(db).session(id);

export const submitUniversalInteractionAction = (db:GameDatabase,input:{interactionId:EntityId;action:InteractionAction;tone:InteractionTone;date:string;seed:string;offer?:UniversalInteraction["offers"]}):UniversalInteraction => { const repo=new UniversalInteractionRepository(db); const current=repo.session(input.interactionId); if(!current) throw new Error(`Interaction ${input.interactionId} not found`); if(terminal.has(current.stage)) throw new Error("Interaction is already resolved"); if(!current.availableActions.includes(input.action)) throw new Error(`Action ${input.action} is not available at ${current.stage}`); if(current.deadline && input.date>current.deadline) { const expired={...current,stage:"DEFERRED" as const,availableActions:[],outcome:"Deadline expired",history:[...current.history,{date:input.date,stage:"DEFERRED" as const,action:"DEFER" as const,note:"Interaction deadline expired"}]}; repo.upsert(expired); return expired; }
  const proposed=input.offer??current.offers; const numericOffer=Object.values(proposed).find((value):value is number=>typeof value==="number"); const numericDemand=Object.values(current.demands).find((value):value is number=>typeof value==="number"); const lowball=numericOffer!==undefined&&numericDemand!==undefined&&numericOffer<numericDemand*0.85; let stage:UniversalInteraction["stage"]; let outcome:string|undefined; let patience=current.patience; let trust=current.trust; let pressure=current.pressure;
  if(input.action==="STATE_POSITION") stage="POSITION_STATED"; else if(input.action==="OFFER") { stage=lowball?"COUNTERED":"NEGOTIATING"; patience=clamp(patience-(lowball?12:3)); trust=clamp(trust+(lowball?-3:toneEffect(input.tone))); } else if(input.action==="COUNTER") { stage="COUNTERED"; patience=clamp(patience-(lowball?10:5)); trust=clamp(trust+toneEffect(input.tone)-2); } else if(input.action==="DEFER") { stage="DEFERRED"; outcome="Parties deferred the decision"; } else if(input.action==="WALK_AWAY") { stage="WALKED_AWAY"; outcome="Negotiation ended without agreement"; } else if(input.action==="REJECT") { stage="REJECTED"; outcome="Offer rejected"; } else { const rng=new SeededRandom(`${input.seed}:${current.id}:${current.history.length}`); const score=current.leverage*.45+current.trust*.25+current.relationshipState*.15+toneEffect(input.tone)+rng.next()*10; if(score>=55){stage="ACCEPTED";outcome="Terms accepted; authoritative contract or transfer system must execute them";}else{stage="COUNTERED";patience=clamp(patience-8);outcome="Counter-offer requested";} }
  if(patience<=0 && !terminal.has(stage)){stage="WALKED_AWAY";outcome="Negotiation fatigue ended the session";}
  const next:UniversalInteraction={...current,offers:proposed,stage,availableActions:actionsFor(stage),patience,trust,pressure:clamp(pressure),outcome,history:[...current.history,{date:input.date,stage,action:input.action,note:outcome??`Structured ${input.action.toLowerCase()} recorded`}]}; repo.upsert(next); if(terminal.has(stage)) repo.insertMemory({id:createStableEntityId("interaction-memory",`${next.id}:${stage}`),participantId:next.initiator.entityId,counterpartId:next.counterpart.entityId,interactionId:next.id,memoryType:stage,value:next.trust,occurredOn:input.date,note:outcome??"Interaction resolved",provenanceStatus:"SIMULATION_ONLY"}); return next; };
