import { ClubCreationRepository, ClubEconomyRepository, EventRepository, WorldRepository, YouthRepository, type GameDatabase } from "@nepal-football-sim/database";
import { createStableEntityId, type ClubDevelopmentProgramme, type EntityId, type Team, type VenueRelationship } from "@nepal-football-sim/shared-types";
import { runAnnualYouthAndRetirementCycle, type YouthAnnualReport } from "./youth-intake.js";

const status = "SIMULATION_ONLY" as const;
const season = (date: string): string => date.slice(0, 4);
const venueFor = (db: GameDatabase, clubId: EntityId): { id: EntityId } | undefined => (db.prepare("SELECT venue_id AS id FROM venue_relationships WHERE club_id = ? AND status != 'unavailable' ORDER BY id LIMIT 1").get(clubId) as { id: EntityId } | undefined) ?? (db.prepare("SELECT v.id FROM venues v JOIN clubs c ON c.country_id = v.country_id WHERE c.id = ? AND v.status != 'CLOSED' ORDER BY v.capacity DESC, v.id LIMIT 1").get(clubId) as { id: EntityId } | undefined);

export const createWomensFootballProgramme = (db: GameDatabase, input: { clubId: EntityId; date: string; annualBudget: number; competitionSeasonId?: EntityId }): ClubDevelopmentProgramme => {
  const club = db.prepare("SELECT name FROM clubs WHERE id = ?").get(input.clubId) as { name: string } | undefined; if (!club) throw new Error("Club does not exist");
  const facility = db.prepare("SELECT youth_facility_quality FROM club_facility_profiles WHERE club_id = ?").get(input.clubId) as { youth_facility_quality?: number } | undefined; const account = db.prepare("SELECT cash_balance FROM club_financial_accounts WHERE club_id = ?").get(input.clubId) as { cash_balance?: number } | undefined; const venue = venueFor(db, input.clubId);
  if (!venue || (facility?.youth_facility_quality ?? 0) < 1 || (account?.cash_balance ?? 0) < input.annualBudget) throw new Error("Women's programme lacks facility or budget support");
  const team: Team = { id: createStableEntityId("womens-team", `${input.clubId}:${input.date}`), clubId: input.clubId, name: `${club.name} Women`, level: "senior", gender: "women" }; const world = new WorldRepository(db); world.insertTeam(team);
  const relationship: VenueRelationship = { id: createStableEntityId("womens-venue-use", team.id), venueId: venue.id, clubId: input.clubId, teamId: team.id, relationshipType: "SHARED_USER", startDate: input.date, status: "available" }; world.insertVenueRelationship(relationship);
  if (input.competitionSeasonId) { const competition = db.prepare("SELECT c.id, c.category FROM competition_seasons cs JOIN competitions c ON c.id = cs.competition_id WHERE cs.id = ?").get(input.competitionSeasonId) as { id: EntityId; category: string } | undefined; if (!competition || competition.category !== "WOMENS_LEAGUE") throw new Error("Competition is not a women's competition"); world.insertClubMembership({ id: createStableEntityId("womens-membership", `${team.id}:${input.competitionSeasonId}`), clubId: input.clubId, teamId: team.id, competitionId: competition.id, competitionSeasonId: input.competitionSeasonId, membershipType: "WOMENS_COMPETITION", status: "ACTIVE" }); }
  const repo = new ClubCreationRepository(db); const programme: ClubDevelopmentProgramme = { id: createStableEntityId("club-programme", `${input.clubId}:WOMENS_SENIOR`), clubId: input.clubId, teamId: team.id, programmeType: "WOMENS_SENIOR", annualBudget: Math.round(input.annualBudget), annualOperatingCost: Math.round(input.annualBudget * 0.75), startedOn: input.date, status: "ACTIVE", provenanceStatus: status }; repo.upsertProgramme(programme);
  for (const role of ["HEAD_COACH", "FITNESS_COACH", "PHYSIO"] as const) world.insertStaffVacancy({ id: createStableEntityId("womens-vacancy", `${team.id}:${role}`), organisationType: "TEAM", teamId: team.id, clubId: input.clubId, organisationName: team.name, role, required: role === "HEAD_COACH", status: "VACANT", openedOn: input.date, reason: "NEW_ROLE" });
  new EventRepository(db).insertHistoricalEvent({ id: createStableEntityId("history", `WOMENS_PROGRAMME_STARTED:${programme.id}`), occurredOn: input.date, eventType: "WOMENS_PROGRAMME_STARTED", involvedEntities: [{ id: input.clubId, type: "club" }], title: "Women's football programme started", data: { annualBudget: programme.annualBudget, teamId: team.id }, importance: "medium", scope: "club" }); return programme;
};

export const establishYouthPathway = (db: GameDatabase, input: { clubId: EntityId; date: string; seed: string; competitionSeasonId?: EntityId }): { programmes: ClubDevelopmentProgramme[]; intake: YouthAnnualReport } => {
  const club = db.prepare("SELECT name, country_id, location_id FROM clubs WHERE id = ?").get(input.clubId) as { name: string; country_id: EntityId; location_id?: EntityId } | undefined; if (!club) throw new Error("Club does not exist"); const senior = db.prepare("SELECT id FROM teams WHERE club_id = ? AND level = 'senior' AND gender = 'men' ORDER BY id LIMIT 1").get(input.clubId) as { id: EntityId } | undefined; if (!senior) throw new Error("A senior club pathway is required");
  const world = new WorldRepository(db); const programmes: ClubDevelopmentProgramme[] = []; for (const level of ["u20", "u17"] as const) { const team: Team = { id: createStableEntityId("youth-team", `${input.clubId}:${level}`), clubId: input.clubId, name: `${club.name} ${level.toUpperCase()}`, level, gender: "men" }; world.insertTeam(team); if (level === "u20") { const programme: ClubDevelopmentProgramme = { id: createStableEntityId("club-programme", `${input.clubId}:YOUTH_PATHWAY`), clubId: input.clubId, teamId: team.id, programmeType: "YOUTH_PATHWAY", annualBudget: 300000, annualOperatingCost: 230000, startedOn: input.date, status: "ACTIVE", provenanceStatus: status }; new ClubCreationRepository(db).upsertProgramme(programme); programmes.push(programme); } world.insertStaffVacancy({ id: createStableEntityId("youth-vacancy", `${team.id}:YOUTH_COACH`), organisationType: "TEAM", teamId: team.id, clubId: input.clubId, organisationName: team.name, role: "YOUTH_COACH", required: false, status: "VACANT", openedOn: input.date, reason: "NEW_ROLE" }); }
  const academyId = createStableEntityId("club-academy", input.clubId); if (!db.prepare("SELECT 1 FROM academies WHERE id = ?").get(academyId)) { world.insertAcademy({ id: academyId, name: `${club.name} Academy`, countryId: club.country_id, locationId: club.location_id, parentClubId: input.clubId, academyType: "CLUB_ACADEMY" }); new YouthRepository(db).upsertAcademySimulationProfile({ id: createStableEntityId("academy-profile", academyId), academyId, clubId: input.clubId, countryId: club.country_id, youthRecruitmentQuality: 2, academyCoachingQuality: 2, academyFacilitiesQuality: 2, regionalReach: 2, talentIdentificationQuality: 2, status }); }
  const intake = runAnnualYouthAndRetirementCycle({ db, worldDate: input.date, seed: `${input.seed}:youth-pathway`, seasonLabel: season(input.date) }); return { programmes, intake };
};
