import { describe, expect, it } from "vitest";
import { calculateCommercialRightsOffer, rankCommercialRightsOffers } from "@nepal-football-sim/simulation";
import { createStableEntityId } from "@nepal-football-sim/shared-types";

const sponsor={id:createStableEntityId("sponsor","sponsor"),name:"SIMULATION_ONLY Telecom",sector:"telecom",financialStrength:70,strategicValue:80,reputation:75,domesticReach:85,internationalReach:35,reliability:90,provenanceStatus:"SIMULATION_ONLY"} as const;
const rightsPackage={id:createStableEntityId("rights-package","package"),federationId:createStableEntityId("federation","fed"),name:"League title",category:"LEAGUE_TITLE_SPONSOR",exclusivityGroup:"telecom",scope:"COMPETITION",availableFrom:"2027-01-01",availableTo:"2027-12-31",status:"AVAILABLE",retainedByFederation:false,provenanceStatus:"SIMULATION_ONLY"} as const;
const evidence={federationReputation:45,competitionReputation:60,nationalTeamPerformance:35,audienceScale:1000,mediaExposure:40,womenYouthGrowth:20};

describe("federation commercial rights phase A",()=>{it("creates deterministic offers and ranks strategic fit",()=>{const input={rightsPackage,sponsor,evidence,offeredOn:"2027-01-01"};const first=calculateCommercialRightsOffer(input);expect(first).toEqual(calculateCommercialRightsOffer(input));expect(first.annualValue).toBeGreaterThan(0);expect(rankCommercialRightsOffers([first])).toEqual([first]);});it("does not make highest cash the only decision input",()=>{const offer=calculateCommercialRightsOffer({rightsPackage,sponsor:{...sponsor,id:createStableEntityId("sponsor","cash"),financialStrength:100,strategicValue:20,reputation:20,domesticReach:20,reliability:30},evidence,offeredOn:"2027-01-01"});const fit=calculateCommercialRightsOffer({rightsPackage,sponsor,evidence,offeredOn:"2027-01-01"});expect(rankCommercialRightsOffers([offer,fit])[0]?.sponsorId).toBe(sponsor.id);});});
