import { describe, expect, it } from "vitest";
import { FederationComplianceRepository, FederationGovernanceRepository, migrateDatabase, openGameDatabase } from "@nepal-football-sim/database";
import { approveFederationGrant, completeCorrectiveAction, createFederationCorrectiveAction, createFederationGrant, disburseFederationGrant, federationAccessAllowed, issueComplianceSanction, recordFederationGrantReport, reviewComplianceAndIssueSanction, reviewFederationReinstatement, spendRestrictedFederationGrant } from "@nepal-football-sim/simulation";
import type { EntityId } from "@nepal-football-sim/shared-types";

const dimensions = (value: number) => ({ autonomy: value, statutoryCompliance: value, electionLegitimacy: value, financialControls: value, auditQuality: value, transparencyReporting: value, safeguarding: value, projectDelivery: value });
const grantInput = (federationId: EntityId) => ({ federationId, sourceInstitution: "AFC_DEVELOPMENT" as const, currency: "NPR", approvedAmount: 100000, approvalDate: undefined, fundingPeriodStart: "2027-01-01", fundingPeriodEnd: "2027-12-31", purpose: "district football support", restrictionType: "DISTRICT_DEVELOPMENT" as const, reportingRequirements: ["annual report"], auditRequired: true, milestones: [], conditions: [] });

const database = () => { const db = openGameDatabase(":memory:"); migrateDatabase(db); db.prepare("INSERT INTO countries (id,name,iso_code) VALUES (?,?,?)").run("country-1", "Nepal", "NPL"); db.prepare("INSERT INTO federations (id,country_id,name) VALUES (?,?,?)").run("fed-1", "country-1", "Simulation Federation"); db.prepare("INSERT INTO federation_financial_accounts (federation_id,currency,cash_balance,restricted_funds,receivables,payables,debt,season_revenue,season_expenses,season_profit_loss,financial_health,last_updated_at,status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)").run("fed-1", "NPR", 0, 0, 0, 0, 0, 0, 0, 0, "STABLE", "2027-01-01", "SIMULATION_ONLY"); return db; };

describe("federation funding and compliance phase A", () => {
  it("keeps restricted funding purpose-bound and supports staged disbursement", () => {
    const db = database(); const federationId = "fed-1" as EntityId; const grant = createFederationGrant(db, { ...grantInput(federationId), seed: "grant" }); approveFederationGrant(db, grant.id, { date: "2027-01-02", approvedAmount: 100000 }); disburseFederationGrant(db, grant.id, { date: "2027-01-03", amount: 60000 }); expect(() => spendRestrictedFederationGrant(db, grant.id, { federationId, date: "2027-01-04", amount: 1000, purpose: "WOMENS_FOOTBALL", description: "wrong purpose" })).toThrow(); const expenditure = spendRestrictedFederationGrant(db, grant.id, { federationId, date: "2027-01-04", amount: 1000, purpose: "DISTRICT_DEVELOPMENT", description: "district ground access" }); expect(expenditure.amount).toBe(1000); expect(new FederationGovernanceRepository(db).financialAccount(federationId)?.restrictedFunds).toBe(59000); db.close();
  });

  it("freezes a grant after failed reporting and records a compliance sanction", () => {
    const db = database(); const federationId = "fed-1" as EntityId; const grant = createFederationGrant(db, { ...grantInput(federationId), seed: "report" }); approveFederationGrant(db, grant.id, { date: "2027-01-02", approvedAmount: 100000 }); disburseFederationGrant(db, grant.id, { date: "2027-01-03", amount: 100000 }); expect(recordFederationGrantReport(db, grant.id, { date: "2027-06-01", accepted: false, note: "missing audit" }).status).toBe("FROZEN"); const result = reviewComplianceAndIssueSanction(db, { federationId, date: "2027-06-02", dimensions: dimensions(25), authority: "AFC" }); expect(result.sanction?.reviewState).toBe("ACTIVE"); expect(federationAccessAllowed(db, federationId, "CLUB_CONTINENTAL_PARTICIPATION_BLOCKED")).toBe(false); expect(new FederationComplianceRepository(db).sanctionsForFederation(federationId)).toHaveLength(1); db.close();
  });

  it("requires corrective evidence before reinstatement and persists the decision", () => {
    const db = database(); const federationId = "fed-1" as EntityId; const sanction = issueComplianceSanction(db, { federationId, date: "2027-01-01", authority: "FIFA", category: "FORMAL_REVIEW", reason: "low controls", requirementsForResolution: ["audit"], affectedProgrammes: ["GRASSROOTS"], consequences: ["FUNDING_FROZEN"] }); const action = createFederationCorrectiveAction(db, { federationId, sanctionId: sanction.id, description: "complete independent audit", category: "AUDIT", startedOn: "2027-02-01", targetCompletionOn: "2027-05-01" }); expect(reviewFederationReinstatement(db, sanction.id, { date: "2027-03-01", dimensions: dimensions(80), evidence: "partial" }).reviewState).toBe("UNDER_REVIEW"); completeCorrectiveAction(db, action.id, { date: "2027-05-02", evidence: "audit filed" }); expect(reviewFederationReinstatement(db, sanction.id, { date: "2027-05-03", dimensions: dimensions(80), evidence: "verified audit" }).reviewState).toBe("RESOLVED"); expect(new FederationComplianceRepository(db).sanction(sanction.id)?.reviewState).toBe("RESOLVED"); db.close();
  });
});
