import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import * as XLSX from "xlsx";
import { describe, expect, it } from "vitest";
import { applyGlobalFootballImport, classifyExternalIdentity, dryRunGlobalFootballImport, reconcileNepalField, validateGlobalFootballWorkbook } from "@nepal-football-sim/data-import";

const headers: Record<string, string[]> = {
  PLAYERS: ["player_external_id", "full_name", "common_name", "date_of_birth", "birth_year", "nationality", "second_nationality", "primary_position", "secondary_position", "preferred_foot", "height_cm", "current_club", "current_club_country", "current_league", "shirt_number", "national_team", "national_team_status", "is_nepal_connected", "nepal_connection_type", "provenance", "confidence", "source_1_id", "source_2_id", "last_verified_date", "notes"],
  CLUBS: ["club_external_id", "official_name", "common_name", "country", "city", "national_federation", "league", "division_level", "stadium", "stadium_capacity", "founded_year", "professional_status", "website", "is_nepal_club", "is_major_global_club", "is_relevant_to_nepal_market", "provenance", "confidence", "source_1_id", "source_2_id", "last_verified_date", "notes"],
  STAFF: ["staff_external_id", "full_name", "date_of_birth", "nationality", "role", "current_club_or_federation", "country", "previous_club_or_role", "coaching_licence", "is_nepal_connected", "nepal_connection", "provenance", "confidence", "source_1_id", "source_2_id", "last_verified_date", "notes"],
  LEAGUES: ["league_external_id", "official_name", "common_name", "country", "federation", "confederation", "tier", "number_of_clubs", "season_format", "professional_status", "is_playable_in_game", "simulation_depth", "provenance", "source_1_id", "last_verified_date", "notes"],
  COMPETITIONS: ["competition_external_id", "official_name", "country_or_region", "organiser", "confederation", "competition_type", "scope", "current_status", "is_playable_in_game", "simulation_depth", "provenance", "source_1_id", "last_verified_date", "notes"],
  FEDERATIONS: ["federation_external_id", "official_name", "abbreviation", "country", "confederation", "fifa_member", "official_website", "provenance", "source_1_id", "last_verified_date", "notes"],
  PLAYER_CLUB_HISTORY: ["history_external_id", "player_external_id", "player_name", "club_external_id", "club_name", "country", "start_date", "end_date", "season", "relationship_type", "provenance", "confidence", "source_1_id", "notes"],
  NEPAL_FOREIGN_PLAYERS: ["record_external_id", "player_external_id", "full_name", "nationality", "primary_position", "nepali_club", "competition", "season_or_year", "relationship_type", "previous_club", "next_club", "currently_in_nepal", "african_player", "african_country", "source_1_id", "source_2_id", "provenance", "confidence", "notes"],
  SOURCES: ["source_id", "publisher", "page_title", "url", "publication_date", "retrieval_date", "source_type", "source_quality", "notes"],
};

const fixture = (duplicate = false): string => {
  const directory = mkdtempSync(join(tmpdir(), "world-import-fixture-")); const path = join(directory, "fixture.xlsx"); const workbook = XLSX.utils.book_new();
  const rows: Record<string, unknown[]> = { SOURCES: [["SRC-1", "Test", "Test source", "https://example.com", "2026-01-01", "2026-01-01", "DATABASE", "PRIMARY", ""]], FEDERATIONS: [["FED-1", "ANFA", "ANFA", "Nepal", "AFC", "YES", "https://anfa.com", "VERIFIED", "SRC-1", "2026-01-01", ""]], LEAGUES: [["LGE-1", "A League", "A League", "Nepal", "ANFA", "AFC", "1", "1", "ROUND_ROBIN", "PROFESSIONAL", "YES", "FULL", "VERIFIED", "SRC-1", "2026-01-01", ""]], COMPETITIONS: [["CMP-1", "A League", "Nepal", "ANFA", "AFC", "LEAGUE", "NATIONAL", "ACTIVE", "YES", "FULL", "VERIFIED", "SRC-1", "2026-01-01", ""]], CLUBS: [["CLB-1", "Test Club", "Test", "Nepal", "Kathmandu", "ANFA", "A League", "1", "Ground", "1000", "2000", "PROFESSIONAL", "https://example.com", "YES", "NO", "YES", "VERIFIED", "HIGH", "SRC-1", "", "2026-01-01", ""]], PLAYERS: [["PLY-1", "Test Player", "Test", "2000-01-01", "2000", "Nepal", "UNKNOWN", "ST", "UNKNOWN", "Right", "180", "Test Club", "Nepal", "A League", "9", "Nepal", "ACTIVE", "YES", "LOCAL", "VERIFIED", "HIGH", "SRC-1", "", "2026-01-01", ""], ...(duplicate ? [["PLY-1", "Other", "Other", "2001-01-01", "2001", "Nepal", "UNKNOWN", "ST", "UNKNOWN", "Right", "180", "Test Club", "Nepal", "A League", "10", "Nepal", "ACTIVE", "NO", "UNKNOWN", "VERIFIED", "HIGH", "SRC-1", "", "2026-01-01", ""]] : [])], STAFF: [["STF-1", "Test Staff", "2000-01-01", "Nepal", "SCOUT", "Test Club", "Nepal", "", "A", "YES", "LOCAL", "VERIFIED", "HIGH", "SRC-1", "", "2026-01-01", ""]], PLAYER_CLUB_HISTORY: [["HIS-1", "PLY-1", "Test Player", "CLB-1", "Test", "Nepal", "2020-01-01", "2021-01-01", "2020", "TRIAL", "VERIFIED", "HIGH", "SRC-1", ""]], NEPAL_FOREIGN_PLAYERS: [["NFP-1", "PLY-1", "Test Player", "Nepal", "ST", "Test Club", "A League", "2020", "TRIAL", "", "", "NO", "NO", "", "SRC-1", "", "REPORTED", "MEDIUM", ""]] };
  for (const [sheet, columns] of Object.entries(headers)) XLSX.utils.book_append_sheet(workbook, XLSX.utils.aoa_to_sheet([columns, ...(rows[sheet] ?? [columns.map(() => "")]) as unknown[][]]), sheet);
  XLSX.writeFile(workbook, path); return path;
};

describe("global football workbook pipeline", () => {
  it("validates exact sheets, builds deterministic dry runs, and keeps APPLY explicit", () => { const path = fixture(); const validation = validateGlobalFootballWorkbook(path); const first = dryRunGlobalFootballImport(path); const second = dryRunGlobalFootballImport(path); expect(validation.statistics.players).toBe(1); expect(first.plan).toEqual(second.plan); expect(() => applyGlobalFootballImport(first, { persistValidatedPlan: () => undefined })).toThrow("APPLY requires explicit"); rmSync(path, { force: true }); });
  it("rejects duplicate IDs and preserves stronger Nepal facts", () => { const path = fixture(true); expect(validateGlobalFootballWorkbook(path).findings.some((finding) => finding.severity === "FATAL")).toBe(true); expect(reconcileNepalField({ value: "Old", provenance: "VERIFIED" }, { value: "New", provenance: "REPORTED" }).action).toBe("RETAIN_EXISTING"); expect(reconcileNepalField({ value: "Old", provenance: "VERIFIED" }, { value: "New", provenance: "VERIFIED" }).action).toBe("CONFLICT_REVIEW"); rmSync(path, { force: true }); });
  it("classifies identities without name-only merges", () => { expect(classifyExternalIdentity({ sameExternalId: false, sameName: true, sameDateOfBirth: false, sameNationality: false, sameClubOrHistory: false })).toBe("NEW_ENTITY"); expect(classifyExternalIdentity({ sameExternalId: false, sameName: true, sameDateOfBirth: true, sameNationality: true, sameClubOrHistory: false })).toBe("STRONG_MATCH"); });
});
