import React from "react";
import type {
  CareerOverviewView,
  FederationExternalContext,
  FederationExternalSanction,
  FederationPresidentDashboard,
  FederationTenureEntry,
  FederationTenureView,
} from "@nepal-football-sim/shared-types";
import type { DesktopRuntimeApi } from "../../appBridge.js";
import { humanizeToken } from "../storyHumanizer.js";
import { AsyncPanel, Badge, Metrics, Panel, useRuntimeData } from "../ui.js";

/**
 * Phase 9D: Tenure (President, read-only) and the external-bodies context.
 *
 * Everything is the recorded tenure and the public election record. Election
 * vote shares, candidate scores, committee influence and coalition support are
 * never shown, and no term-limit rule is claimed because the model defines none.
 * The "when the term ends" text describes the behaviour the domain applies:
 * the tenure closes and stays in history, every President authority is removed,
 * and the same person returns to the base career.
 */

export const tenureStatusLabel = (status: string): string =>
  status === "ACTIVE" ? "Active" : status === "INTERIM" ? "Interim" : status === "FORMER" ? "Ended" : humanizeToken(status);

export const tenureTone = (status: string): "ok" | "warn" | "info" =>
  status === "ACTIVE" ? "ok" : status === "INTERIM" ? "warn" : "info";

export const termRange = (entry: Pick<FederationTenureEntry, "termStart" | "termEnd">): string =>
  `${entry.termStart} – ${entry.termEnd ?? "no end date recorded"}`;

const roleName = (role: string): string =>
  role === "MANAGER" ? "Manager" : role === "CHAIRMAN_OWNER" ? "Club Owner" : humanizeToken(role);

/** The base career the presidency layers on, or an honest absence. */
export const baseCareerText = (overview: Pick<CareerOverviewView, "baseRole" | "heldRoles">): string => {
  if (!overview.baseRole) return "No base career is on record.";
  const held = overview.heldRoles.find((entry) => entry.role === overview.baseRole);
  return `${roleName(overview.baseRole)}${held?.organization?.label ? ` at ${held.organization.label}` : ""}`;
};

export const FederationTenureScreen = ({
  dashboard,
  bridge,
}: {
  dashboard: Pick<FederationPresidentDashboard, "federation" | "tenure">;
  bridge: Pick<DesktopRuntimeApi, "getFederationTenure" | "getCareerOverview">;
}): React.ReactElement => {
  const [tenure] = useRuntimeData(
    () =>
      bridge.getFederationTenure
        ? bridge.getFederationTenure()
        : Promise.resolve({
            ok: false as const,
            error: { code: "RUNTIME_UNAVAILABLE" as const, message: "Tenure is unavailable right now." },
          }),
    [],
  );
  const [career] = useRuntimeData(() => bridge.getCareerOverview(), []);
  const current = dashboard.tenure;
  return (
    <section className="role-detail">
      <Panel title="Presidency and tenure" className="panel-wide">
        <Metrics
          items={[
            { label: "Federation", value: dashboard.federation.name },
            { label: "Current term", value: current ? termRange(current) : "Not recorded" },
            {
              label: "Status",
              value: current ? <Badge tone={tenureTone(current.status)}>{tenureStatusLabel(current.status)}</Badge> : "Unknown",
            },
            { label: "Term ends", value: current?.termEnd ?? "No end date recorded" },
          ]}
        />
        {current?.status === "INTERIM" && (
          <p className="subtle">
            You hold this office on an interim basis. Interim presidents cannot implement governance proposals or set
            federation budgets.
          </p>
        )}
        <AsyncPanel state={career}>
          {(overview: CareerOverviewView) => (
            <p className="subtle">
              <strong>{overview.name}</strong> is the same person across every role. Base career:{" "}
              {baseCareerText(overview)}.
            </p>
          )}
        </AsyncPanel>
        <p className="subtle">
          <Badge tone="info">simulated</Badge> Tenure and election records are generated by the simulation.
        </p>
      </Panel>

      <Panel title="When the term ends" className="panel-wide">
        <ul className="report-list">
          <li>The presidency closes and stays in your presidency history.</li>
          <li>Every President office and action is removed.</li>
          <li>You return to your base career as the same person, with your club role unchanged.</li>
          <li>The seat is filled through the federation&rsquo;s election cycle.</li>
        </ul>
      </Panel>

      <AsyncPanel state={tenure}>
        {(view: FederationTenureView) => (
          <>
            <Panel title="Elections" className="panel-wide">
              {view.election.upcoming ? (
                <Metrics
                  items={[
                    { label: "Election date", value: view.election.upcoming.electionDate },
                    { label: "Nominations open", value: view.election.upcoming.nominationStart },
                    { label: "Stage", value: humanizeToken(view.election.upcoming.status) },
                  ]}
                />
              ) : (
                <p className="empty-state">
                  No election is scheduled.{" "}
                  {current?.termEnd ? `Your term ends ${current.termEnd}.` : "No term end date is recorded."}
                </p>
              )}
              {view.election.latest ? (
                <p>
                  Last election decided {view.election.latest.decidedAt}: {view.election.latest.winnerName}
                  {view.election.latest.youWon ? " (you)" : ""} was elected for {view.election.latest.termYears} years.
                </p>
              ) : (
                <p className="empty-state">No completed election is on record.</p>
              )}
              <p className="subtle">
                Whether you can stand is shown on Home under the presidency path. Vote shares and candidate
                assessments are not published.
              </p>
            </Panel>

            <Panel title="Presidency history" className="panel-wide">
              {view.history.length === 0 ? (
                <p className="empty-state">No presidency is on record for you.</p>
              ) : (
                <div className="table-scroll" role="region" aria-label="Presidency history" tabIndex={0}>
                  <table>
                    <caption className="visually-hidden">Your presidencies of this federation</caption>
                    <thead>
                      <tr>
                        <th scope="col">Term start</th>
                        <th scope="col">Term end</th>
                        <th scope="col">Status</th>
                      </tr>
                    </thead>
                    <tbody>
                      {view.history.map((entry) => (
                        <tr key={entry.id}>
                          <th scope="row">{entry.termStart}</th>
                          <td>{entry.termEnd ?? "No end date recorded"}</td>
                          <td>
                            <Badge tone={tenureTone(entry.status)}>{tenureStatusLabel(entry.status)}</Badge>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </Panel>
          </>
        )}
      </AsyncPanel>
    </section>
  );
};

export const complianceLabel = (status: string): string => humanizeToken(status);

export const activeSanctions = (sanctions: Array<Pick<FederationExternalSanction, "reviewState">>): number =>
  sanctions.filter((sanction) => sanction.reviewState !== "RESOLVED").length;

/** Compliance standing and sanctions from FIFA, AFC or domestic authorities. Names are context only. */
export const ExternalBodiesPanel = ({
  bridge,
  onNavigate,
}: {
  bridge: Pick<DesktopRuntimeApi, "getFederationExternalContext">;
  onNavigate: (target: "finance") => void;
}): React.ReactElement => {
  const [state] = useRuntimeData(
    () =>
      bridge.getFederationExternalContext
        ? bridge.getFederationExternalContext()
        : Promise.resolve({
            ok: false as const,
            error: { code: "RUNTIME_UNAVAILABLE" as const, message: "External context is unavailable right now." },
          }),
    [],
  );
  return (
    <Panel title="External bodies" className="panel-wide">
      <AsyncPanel state={state}>
        {(context: FederationExternalContext) => (
          <>
            <Metrics
              items={[
                {
                  label: "Compliance standing",
                  value: context.compliance
                    ? `${complianceLabel(context.compliance.status)} (reviewed ${context.compliance.lastReviewedOn})`
                    : "No compliance review is on record",
                },
                { label: "Open sanctions", value: activeSanctions(context.sanctions) },
              ]}
            />
            {context.sanctions.length === 0 ? (
              <p className="empty-state">No sanctions are on record from FIFA, the AFC or domestic authorities.</p>
            ) : (
              <div className="table-scroll" role="region" aria-label="Federation sanctions" tabIndex={0}>
                <table>
                  <caption className="visually-hidden">Sanctions imposed on the federation</caption>
                  <thead>
                    <tr>
                      <th scope="col">Authority</th>
                      <th scope="col">Reason</th>
                      <th scope="col">Since</th>
                      <th scope="col">Status</th>
                      <th scope="col">Consequences</th>
                      <th scope="col">To resolve</th>
                    </tr>
                  </thead>
                  <tbody>
                    {context.sanctions.map((sanction) => (
                      <tr key={sanction.id}>
                        <th scope="row">{sanction.authority}</th>
                        <td>{sanction.reason}</td>
                        <td>{sanction.startDate}</td>
                        <td>
                          <Badge tone={sanction.reviewState === "RESOLVED" ? "ok" : "bad"}>
                            {humanizeToken(sanction.reviewState)}
                            {sanction.resolvedOn ? ` (${sanction.resolvedOn})` : ""}
                          </Badge>
                        </td>
                        <td>{sanction.consequences.map(humanizeToken).join(", ") || "None"}</td>
                        <td>{sanction.requirementsForResolution.join("; ") || "None recorded"}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
            <p className="subtle">
              <Badge tone="info">simulated</Badge> FIFA and AFC are named as the imposing authority only. Grants from
              external bodies appear in Finance.
            </p>
            <div className="button-row">
              <button className="ghost small" onClick={() => onNavigate("finance")}>
                See grants in Finance
              </button>
            </div>
          </>
        )}
      </AsyncPanel>
    </Panel>
  );
};
