import type { ClubDevelopmentProgramme, EntityId, SimulationClubLifecycleEvent, SimulationClubRecord } from "@nepal-football-sim/shared-types";
import type { GameDatabase } from "./connection.js";

const map = (r: any): SimulationClubRecord => ({ id: r.id, clubId: r.club_id, locationId: r.location_id, foundedOn: r.founded_on, ownershipType: r.ownership_type, initialReputation: r.initial_reputation, supporterBase: r.supporter_base, status: r.status, admissionStatus: r.admission_status, venueId: r.venue_id ?? undefined, provenanceStatus: r.provenance_status });
export class ClubCreationRepository {
  constructor(private readonly db: GameDatabase) {}
  upsert(record: SimulationClubRecord): void { this.db.prepare(`INSERT INTO simulation_club_records (id,club_id,location_id,founded_on,ownership_type,initial_reputation,supporter_base,status,admission_status,venue_id,provenance_status) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(club_id) DO UPDATE SET status=excluded.status, admission_status=excluded.admission_status, venue_id=excluded.venue_id`).run(record.id,record.clubId,record.locationId,record.foundedOn,record.ownershipType,record.initialReputation,record.supporterBase,record.status,record.admissionStatus,record.venueId??null,record.provenanceStatus); }
  get(clubId: EntityId): SimulationClubRecord | undefined { const row = this.db.prepare("SELECT * FROM simulation_club_records WHERE club_id = ?").get(clubId) as any; return row ? map(row) : undefined; }
  all(): SimulationClubRecord[] { return (this.db.prepare("SELECT * FROM simulation_club_records ORDER BY founded_on,id").all() as any[]).map(map); }
  recordEvent(event: SimulationClubLifecycleEvent): void { this.db.prepare("INSERT OR REPLACE INTO simulation_club_lifecycle_events (id,club_id,event_type,occurred_on,reason,provenance_status) VALUES (?,?,?,?,?,?)").run(event.id,event.clubId,event.eventType,event.occurredOn,event.reason,event.provenanceStatus); }
  history(clubId?: EntityId): SimulationClubLifecycleEvent[] { const rows = (clubId ? this.db.prepare("SELECT * FROM simulation_club_lifecycle_events WHERE club_id = ? ORDER BY occurred_on,id").all(clubId) : this.db.prepare("SELECT * FROM simulation_club_lifecycle_events ORDER BY occurred_on,id").all()) as any[]; return rows.map((r) => ({ id: r.id, clubId: r.club_id, eventType: r.event_type, occurredOn: r.occurred_on, reason: r.reason, provenanceStatus: r.provenance_status })); }
  upsertProgramme(value: ClubDevelopmentProgramme): void { this.db.prepare(`INSERT INTO club_development_programmes (id,club_id,team_id,programme_type,annual_budget,annual_operating_cost,started_on,status,provenance_status) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(club_id,programme_type) DO UPDATE SET team_id=excluded.team_id,annual_budget=excluded.annual_budget,annual_operating_cost=excluded.annual_operating_cost,status=excluded.status`).run(value.id,value.clubId,value.teamId,value.programmeType,value.annualBudget,value.annualOperatingCost,value.startedOn,value.status,value.provenanceStatus); }
  programmes(clubId?: EntityId): ClubDevelopmentProgramme[] { const rows = (clubId ? this.db.prepare("SELECT * FROM club_development_programmes WHERE club_id = ? ORDER BY programme_type").all(clubId) : this.db.prepare("SELECT * FROM club_development_programmes ORDER BY club_id,programme_type").all()) as any[]; return rows.map((r) => ({ id:r.id,clubId:r.club_id,teamId:r.team_id,programmeType:r.programme_type,annualBudget:r.annual_budget,annualOperatingCost:r.annual_operating_cost,startedOn:r.started_on,status:r.status,provenanceStatus:r.provenance_status })); }
}
