import type { ClubNetworkConflict, EntityId, InternationalClubPartnership, MultiClubOwnershipRecord } from "@nepal-football-sim/shared-types";
import type { GameDatabase } from "./connection.js";
const network=(r:any):MultiClubOwnershipRecord=>({id:r.id,ownerGroupId:r.owner_group_id,clubId:r.club_id,stakePercentage:r.stake_percentage,controlLevel:r.control_level,acquisitionDate:r.acquisition_date,boardInfluence:r.board_influence,strategy:r.strategy,relationshipStatus:r.relationship_status,provenanceStatus:r.provenance_status});
const partnership=(r:any):InternationalClubPartnership=>({id:r.id,fromClubId:r.from_club_id,toClubId:r.to_club_id,partnershipType:r.partnership_type,relationshipStrength:r.relationship_strength,startDate:r.start_date,endDate:r.end_date??undefined,status:r.status,provenanceStatus:r.provenance_status});
const conflict=(r:any):ClubNetworkConflict=>({type:r.conflict_type,clubIds:JSON.parse(r.club_ids_json),severity:r.severity,reason:r.reason,provenanceStatus:r.provenance_status});
export class ClubNetworkRepository{constructor(private readonly db:GameDatabase){db.exec(`CREATE TABLE IF NOT EXISTS multi_club_ownership_network (id TEXT PRIMARY KEY,owner_group_id TEXT NOT NULL,club_id TEXT NOT NULL,stake_percentage REAL NOT NULL,control_level TEXT NOT NULL,acquisition_date TEXT NOT NULL,board_influence REAL NOT NULL,strategy TEXT NOT NULL,relationship_status TEXT NOT NULL,provenance_status TEXT NOT NULL,UNIQUE(owner_group_id,club_id));CREATE TABLE IF NOT EXISTS international_club_partnerships (id TEXT PRIMARY KEY,from_club_id TEXT NOT NULL,to_club_id TEXT NOT NULL,partnership_type TEXT NOT NULL,relationship_strength REAL NOT NULL,start_date TEXT NOT NULL,end_date TEXT,status TEXT NOT NULL,provenance_status TEXT NOT NULL,UNIQUE(from_club_id,to_club_id,partnership_type));CREATE TABLE IF NOT EXISTS club_network_conflicts (id TEXT PRIMARY KEY,conflict_type TEXT NOT NULL,club_ids_json TEXT NOT NULL,severity TEXT NOT NULL,reason TEXT NOT NULL,provenance_status TEXT NOT NULL);`);}
upsertOwnership(v:MultiClubOwnershipRecord):void{this.db.prepare(`INSERT INTO multi_club_ownership_network (id,owner_group_id,club_id,stake_percentage,control_level,acquisition_date,board_influence,strategy,relationship_status,provenance_status) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(owner_group_id,club_id) DO UPDATE SET stake_percentage=excluded.stake_percentage,control_level=excluded.control_level,board_influence=excluded.board_influence,strategy=excluded.strategy,relationship_status=excluded.relationship_status`).run(v.id,v.ownerGroupId,v.clubId,v.stakePercentage,v.controlLevel,v.acquisitionDate,v.boardInfluence,v.strategy,v.relationshipStatus,v.provenanceStatus);}
ownership(ownerGroupId?:EntityId):MultiClubOwnershipRecord[]{const rows=(ownerGroupId?this.db.prepare("SELECT * FROM multi_club_ownership_network WHERE owner_group_id=? ORDER BY club_id").all(ownerGroupId):this.db.prepare("SELECT * FROM multi_club_ownership_network ORDER BY owner_group_id,club_id").all()) as any[];return rows.map(network);}
upsertPartnership(v:InternationalClubPartnership):void{this.db.prepare(`INSERT INTO international_club_partnerships (id,from_club_id,to_club_id,partnership_type,relationship_strength,start_date,end_date,status,provenance_status) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(from_club_id,to_club_id,partnership_type) DO UPDATE SET relationship_strength=excluded.relationship_strength,end_date=excluded.end_date,status=excluded.status`).run(v.id,v.fromClubId,v.toClubId,v.partnershipType,v.relationshipStrength,v.startDate,v.endDate??null,v.status,v.provenanceStatus);}
partnerships(clubId?:EntityId):InternationalClubPartnership[]{const rows=(clubId?this.db.prepare("SELECT * FROM international_club_partnerships WHERE from_club_id=? OR to_club_id=? ORDER BY start_date,id").all(clubId,clubId):this.db.prepare("SELECT * FROM international_club_partnerships ORDER BY start_date,id").all()) as any[];return rows.map(partnership);}
activeScoutingPartnerships(clubId:EntityId,simulationDate:string):InternationalClubPartnership[]{const rows=this.db.prepare("SELECT * FROM international_club_partnerships WHERE from_club_id=? AND partnership_type='SCOUTING' AND status='ACTIVE' AND start_date<=? AND (end_date IS NULL OR end_date>=?) ORDER BY start_date,id").all(clubId,simulationDate,simulationDate) as any[];return rows.map(partnership);}
activeTechnicalPartnerships(clubId:EntityId,simulationDate:string):InternationalClubPartnership[]{const rows=this.db.prepare("SELECT * FROM international_club_partnerships WHERE from_club_id=? AND partnership_type='TECHNICAL' AND status='ACTIVE' AND start_date<=? AND (end_date IS NULL OR end_date>=?) ORDER BY start_date,id").all(clubId,simulationDate,simulationDate) as any[];return rows.map(partnership);}
activeYouthDevelopmentPartnerships(clubId:EntityId,simulationDate:string):InternationalClubPartnership[]{const rows=this.db.prepare("SELECT * FROM international_club_partnerships WHERE from_club_id=? AND partnership_type='YOUTH_DEVELOPMENT' AND status='ACTIVE' AND start_date<=? AND (end_date IS NULL OR end_date>=?) ORDER BY start_date,id").all(clubId,simulationDate,simulationDate) as any[];return rows.map(partnership);}
activeAcademyPartnerships(clubId:EntityId,simulationDate:string):InternationalClubPartnership[]{const rows=this.db.prepare("SELECT * FROM international_club_partnerships WHERE from_club_id=? AND partnership_type='ACADEMY' AND status='ACTIVE' AND start_date<=? AND (end_date IS NULL OR end_date>=?) ORDER BY start_date,id").all(clubId,simulationDate,simulationDate) as any[];return rows.map(partnership);}
activeLoanPartnerships(clubId:EntityId,simulationDate:string):InternationalClubPartnership[]{const rows=this.db.prepare("SELECT * FROM international_club_partnerships WHERE from_club_id=? AND partnership_type='LOAN' AND status='ACTIVE' AND start_date<=? AND (end_date IS NULL OR end_date>=?) ORDER BY start_date,id").all(clubId,simulationDate,simulationDate) as any[];return rows.map(partnership);}
activePreferredTransferPartnerships(clubId:EntityId,simulationDate:string):InternationalClubPartnership[]{const rows=this.db.prepare("SELECT * FROM international_club_partnerships WHERE from_club_id=? AND partnership_type='PREFERRED_TRANSFER' AND status='ACTIVE' AND start_date<=? AND (end_date IS NULL OR end_date>=?) ORDER BY start_date,id").all(clubId,simulationDate,simulationDate) as any[];return rows.map(partnership);}
activeCommercialPartnerships(clubId:EntityId,simulationDate:string):InternationalClubPartnership[]{const rows=this.db.prepare("SELECT * FROM international_club_partnerships WHERE from_club_id=? AND partnership_type='COMMERCIAL' AND status='ACTIVE' AND start_date<=? AND (end_date IS NULL OR end_date>=?) ORDER BY start_date,id").all(clubId,simulationDate,simulationDate) as any[];return rows.map(partnership);}
activeRelatedClubIds(clubId:EntityId,simulationDate:string):EntityId[]{const rows=this.db.prepare("SELECT related.club_id AS club_id FROM multi_club_ownership_network source JOIN multi_club_ownership_network related ON related.owner_group_id=source.owner_group_id WHERE source.club_id=? AND source.relationship_status='ACTIVE' AND source.acquisition_date<=? AND related.club_id<>source.club_id AND related.relationship_status='ACTIVE' AND related.acquisition_date<=? ORDER BY related.club_id").all(clubId,simulationDate,simulationDate) as Array<{club_id:EntityId}>;return rows.map((row)=>row.club_id);}
areRelatedClubs(firstClubId:EntityId,secondClubId:EntityId,simulationDate:string):boolean{return this.activeRelatedClubIds(firstClubId,simulationDate).includes(secondClubId);}
hasSameCompetitionConflict(firstClubId:EntityId,secondClubId:EntityId,simulationDate:string):boolean{if(!this.areRelatedClubs(firstClubId,secondClubId,simulationDate))return false;return Boolean(this.db.prepare("SELECT 1 FROM club_memberships first_membership JOIN club_memberships second_membership ON second_membership.competition_season_id=first_membership.competition_season_id JOIN competition_seasons season ON season.id=first_membership.competition_season_id WHERE first_membership.club_id=? AND second_membership.club_id=? AND first_membership.status IN ('ACTIVE','QUALIFIED','PROMOTED') AND second_membership.status IN ('ACTIVE','QUALIFIED','PROMOTED') AND season.start_date<=? AND season.end_date>=? LIMIT 1").get(firstClubId,secondClubId,simulationDate,simulationDate));}
insertConflict(v:ClubNetworkConflict):void{this.db.prepare("INSERT INTO club_network_conflicts (id,conflict_type,club_ids_json,severity,reason,provenance_status) VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING").run(`${v.type}:${[...v.clubIds].sort().join(":")}`,v.type,JSON.stringify(v.clubIds),v.severity,v.reason,v.provenanceStatus);}
conflicts():ClubNetworkConflict[]{return (this.db.prepare("SELECT * FROM club_network_conflicts ORDER BY conflict_type,id").all() as any[]).map(conflict);}}
