import type { CommercialSponsorProfile, EntityId, FederationCommercialRightsOffer, FederationCommercialRightsPackage } from "@nepal-football-sim/shared-types";
import type { GameDatabase } from "./connection.js";

const mapSponsor=(r:any):CommercialSponsorProfile=>({id:r.id,name:r.name,sector:r.sector,financialStrength:r.financial_strength,strategicValue:r.strategic_value,reputation:r.reputation,domesticReach:r.domestic_reach,internationalReach:r.international_reach,reliability:r.reliability,provenanceStatus:r.provenance_status});
const mapPackage=(r:any):FederationCommercialRightsPackage=>({id:r.id,federationId:r.federation_id,name:r.name,category:r.category,exclusivityGroup:r.exclusivity_group??undefined,scope:r.scope,availableFrom:r.available_from,availableTo:r.available_to,status:r.status,bundledWith:r.bundled_with_json?JSON.parse(r.bundled_with_json):undefined,provenanceStatus:r.provenance_status});
const mapOffer=(r:any):FederationCommercialRightsOffer=>({id:r.id,packageId:r.package_id,federationId:r.federation_id,sponsorId:r.sponsor_id,termYears:r.term_years,annualValue:r.annual_value,bonuses:r.bonuses_json?JSON.parse(r.bonuses_json):{},reachScore:r.reach_score,strategicFit:r.strategic_fit,relationshipValue:r.relationship_value,exclusivity:Boolean(r.exclusivity),scope:r.scope,status:r.status,offeredOn:r.offered_on,startDate:r.start_date??undefined,endDate:r.end_date??undefined,federationLedgerEntryId:r.federation_ledger_entry_id??undefined,provenanceStatus:r.provenance_status});

export class CommercialRightsRepository {
  constructor(private readonly db:GameDatabase){db.exec(`CREATE TABLE IF NOT EXISTS commercial_sponsor_profiles (id TEXT PRIMARY KEY,name TEXT NOT NULL,sector TEXT NOT NULL,financial_strength INTEGER NOT NULL,strategic_value INTEGER NOT NULL,reputation INTEGER NOT NULL,domestic_reach INTEGER NOT NULL,international_reach INTEGER NOT NULL,reliability INTEGER NOT NULL,provenance_status TEXT NOT NULL); CREATE TABLE IF NOT EXISTS federation_commercial_rights_packages (id TEXT PRIMARY KEY,federation_id TEXT NOT NULL,name TEXT NOT NULL,category TEXT NOT NULL,exclusivity_group TEXT,scope TEXT NOT NULL,available_from TEXT NOT NULL,available_to TEXT NOT NULL,status TEXT NOT NULL,bundled_with_json TEXT,provenance_status TEXT NOT NULL); CREATE TABLE IF NOT EXISTS federation_commercial_rights_offers (id TEXT PRIMARY KEY,package_id TEXT NOT NULL,federation_id TEXT NOT NULL,sponsor_id TEXT NOT NULL,term_years INTEGER NOT NULL,annual_value INTEGER NOT NULL,bonuses_json TEXT NOT NULL,reach_score INTEGER NOT NULL,strategic_fit INTEGER NOT NULL,relationship_value INTEGER NOT NULL,exclusivity INTEGER NOT NULL,scope TEXT NOT NULL,status TEXT NOT NULL,offered_on TEXT NOT NULL,start_date TEXT,end_date TEXT,federation_ledger_entry_id TEXT,provenance_status TEXT NOT NULL);`);}
  upsertSponsor(v:CommercialSponsorProfile):void{this.db.prepare(`INSERT INTO commercial_sponsor_profiles (id,name,sector,financial_strength,strategic_value,reputation,domestic_reach,international_reach,reliability,provenance_status) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,sector=excluded.sector,financial_strength=excluded.financial_strength,strategic_value=excluded.strategic_value,reputation=excluded.reputation,domestic_reach=excluded.domestic_reach,international_reach=excluded.international_reach,reliability=excluded.reliability`).run(v.id,v.name,v.sector,v.financialStrength,v.strategicValue,v.reputation,v.domesticReach,v.internationalReach,v.reliability,v.provenanceStatus);}
  sponsor(id:EntityId):CommercialSponsorProfile|undefined{const r=this.db.prepare("SELECT * FROM commercial_sponsor_profiles WHERE id=?").get(id) as any;return r?mapSponsor(r):undefined;}
  sponsors():CommercialSponsorProfile[]{return (this.db.prepare("SELECT * FROM commercial_sponsor_profiles ORDER BY id").all() as any[]).map(mapSponsor);}
  upsertPackage(v:FederationCommercialRightsPackage):void{this.db.prepare(`INSERT INTO federation_commercial_rights_packages (id,federation_id,name,category,exclusivity_group,scope,available_from,available_to,status,bundled_with_json,provenance_status) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=excluded.status,bundled_with_json=excluded.bundled_with_json`).run(v.id,v.federationId,v.name,v.category,v.exclusivityGroup??null,v.scope,v.availableFrom,v.availableTo,v.status,v.bundledWith?JSON.stringify(v.bundledWith):null,v.provenanceStatus);}
  packages(federationId?:EntityId):FederationCommercialRightsPackage[]{const rows=(federationId?this.db.prepare("SELECT * FROM federation_commercial_rights_packages WHERE federation_id=? ORDER BY available_from,id").all(federationId):this.db.prepare("SELECT * FROM federation_commercial_rights_packages ORDER BY federation_id,available_from,id").all()) as any[];return rows.map(mapPackage);}
  upsertOffer(v:FederationCommercialRightsOffer):void{this.db.prepare(`INSERT INTO federation_commercial_rights_offers (id,package_id,federation_id,sponsor_id,term_years,annual_value,bonuses_json,reach_score,strategic_fit,relationship_value,exclusivity,scope,status,offered_on,start_date,end_date,federation_ledger_entry_id,provenance_status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET term_years=excluded.term_years,annual_value=excluded.annual_value,bonuses_json=excluded.bonuses_json,reach_score=excluded.reach_score,strategic_fit=excluded.strategic_fit,relationship_value=excluded.relationship_value,status=excluded.status,start_date=excluded.start_date,end_date=excluded.end_date,federation_ledger_entry_id=excluded.federation_ledger_entry_id`).run(v.id,v.packageId,v.federationId,v.sponsorId,v.termYears,v.annualValue,JSON.stringify(v.bonuses),v.reachScore,v.strategicFit,v.relationshipValue,v.exclusivity?1:0,v.scope,v.status,v.offeredOn,v.startDate??null,v.endDate??null,v.federationLedgerEntryId??null,v.provenanceStatus);}
  offers(packageId?:EntityId):FederationCommercialRightsOffer[]{const rows=(packageId?this.db.prepare("SELECT * FROM federation_commercial_rights_offers WHERE package_id=? ORDER BY offered_on,id").all(packageId):this.db.prepare("SELECT * FROM federation_commercial_rights_offers ORDER BY package_id,offered_on,id").all()) as any[];return rows.map(mapOffer);}
}
