import type { CompetitionDistributionPayment, CompetitionDistributionPolicy, EntityId } from "@nepal-football-sim/shared-types";
import type { GameDatabase } from "./connection.js";

const mapPolicy=(r:any):CompetitionDistributionPolicy=>({id:r.id,federationId:r.federation_id,competitionSeasonId:r.competition_season_id,version:r.version,poolAmount:r.pool_amount,championPrize:r.champion_prize,runnerUpPrize:r.runner_up_prize,placementPrizes:r.placement_prizes,participationPayments:r.participation_payments,equalSharePayments:r.equal_share_payments,performanceSharePayments:r.performance_share_payments,audienceShare:r.audience_share,youthDevelopmentIncentives:r.youth_development_incentives,womensFootballIncentives:r.womens_football_incentives,infrastructureGrants:r.infrastructure_grants,status:r.status,provenanceStatus:r.provenance_status});
const mapPayment=(r:any):CompetitionDistributionPayment=>({id:r.id,policyId:r.policy_id,competitionSeasonId:r.competition_season_id,federationId:r.federation_id,clubId:r.club_id,amount:r.amount,reason:r.reason,paidOn:r.paid_on,federationLedgerEntryId:r.federation_ledger_entry_id,clubLedgerEntryId:r.club_ledger_entry_id,provenanceStatus:r.provenance_status});
export class CompetitionDistributionRepository { constructor(private readonly db:GameDatabase){db.exec(`CREATE TABLE IF NOT EXISTS competition_distribution_policies (id TEXT PRIMARY KEY,federation_id TEXT NOT NULL,competition_season_id TEXT NOT NULL,version INTEGER NOT NULL,pool_amount INTEGER NOT NULL,champion_prize INTEGER NOT NULL,runner_up_prize INTEGER NOT NULL,placement_prizes INTEGER NOT NULL,participation_payments INTEGER NOT NULL,equal_share_payments INTEGER NOT NULL,performance_share_payments INTEGER NOT NULL,audience_share INTEGER NOT NULL,youth_development_incentives INTEGER NOT NULL,womens_football_incentives INTEGER NOT NULL,infrastructure_grants INTEGER NOT NULL,status TEXT NOT NULL,provenance_status TEXT NOT NULL,UNIQUE(competition_season_id,version)); CREATE TABLE IF NOT EXISTS competition_distribution_payments (id TEXT PRIMARY KEY,policy_id TEXT NOT NULL,competition_season_id TEXT NOT NULL,federation_id TEXT NOT NULL,club_id TEXT NOT NULL,amount INTEGER NOT NULL,reason TEXT NOT NULL,paid_on TEXT NOT NULL,federation_ledger_entry_id TEXT NOT NULL,club_ledger_entry_id TEXT NOT NULL,provenance_status TEXT NOT NULL,UNIQUE(policy_id,club_id,reason));`);}
 upsertPolicy(v:CompetitionDistributionPolicy):void{this.db.prepare(`INSERT INTO competition_distribution_policies (id,federation_id,competition_season_id,version,pool_amount,champion_prize,runner_up_prize,placement_prizes,participation_payments,equal_share_payments,performance_share_payments,audience_share,youth_development_incentives,womens_football_incentives,infrastructure_grants,status,provenance_status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=excluded.status,pool_amount=excluded.pool_amount`).run(v.id,v.federationId,v.competitionSeasonId,v.version,v.poolAmount,v.championPrize,v.runnerUpPrize,v.placementPrizes,v.participationPayments,v.equalSharePayments,v.performanceSharePayments,v.audienceShare,v.youthDevelopmentIncentives,v.womensFootballIncentives,v.infrastructureGrants,v.status,v.provenanceStatus);}
 policy(id:EntityId):CompetitionDistributionPolicy|undefined{const r=this.db.prepare("SELECT * FROM competition_distribution_policies WHERE id=?").get(id) as any;return r?mapPolicy(r):undefined;}
 policies(competitionSeasonId?:EntityId):CompetitionDistributionPolicy[]{const rows=(competitionSeasonId?this.db.prepare("SELECT * FROM competition_distribution_policies WHERE competition_season_id=? ORDER BY version").all(competitionSeasonId):this.db.prepare("SELECT * FROM competition_distribution_policies ORDER BY competition_season_id,version").all()) as any[];return rows.map(mapPolicy);}
 insertPayment(v:CompetitionDistributionPayment):void{this.db.prepare(`INSERT INTO competition_distribution_payments (id,policy_id,competition_season_id,federation_id,club_id,amount,reason,paid_on,federation_ledger_entry_id,club_ledger_entry_id,provenance_status) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(policy_id,club_id,reason) DO NOTHING`).run(v.id,v.policyId,v.competitionSeasonId,v.federationId,v.clubId,v.amount,v.reason,v.paidOn,v.federationLedgerEntryId,v.clubLedgerEntryId,v.provenanceStatus);}
 payments(policyId?:EntityId):CompetitionDistributionPayment[]{const rows=(policyId?this.db.prepare("SELECT * FROM competition_distribution_payments WHERE policy_id=? ORDER BY club_id,reason").all(policyId):this.db.prepare("SELECT * FROM competition_distribution_payments ORDER BY policy_id,club_id,reason").all()) as any[];return rows.map(mapPayment);}
}
