import type { EntityId, FacilityProjectPlan, FacilitySiteOption } from "@nepal-football-sim/shared-types";
import type { GameDatabase } from "./connection.js";

const site = (row: any): FacilitySiteOption => ({ id: row.id, clubId: row.club_id, districtId: row.district_id, municipalityName: row.municipality_name, siteType: row.site_type, arrangement: row.arrangement, costBand: row.cost_band, accessibilityBand: row.accessibility_band, catchmentBand: row.catchment_band, communityValueBand: row.community_value_band, governmentConditions: JSON.parse(row.government_conditions_json), readiness: row.readiness, provenanceStatus: row.provenance_status });
const plan = (row: any): FacilityProjectPlan => ({ id: row.id, projectId: row.project_id, clubId: row.club_id, projectType: row.project_type, mode: row.mode, scope: row.scope, components: JSON.parse(row.components_json), siteOptionId: row.site_option_id ?? undefined, fundingSource: row.funding_source, governmentApplicationId: row.government_application_id ?? undefined, rationale: row.rationale, costBand: row.cost_band, durationBand: row.duration_band, expectedImprovement: JSON.parse(row.expected_improvement_json), createdOn: row.created_on, provenanceStatus: row.provenance_status });

export class FacilityPlanningRepository {
  constructor(private readonly db: GameDatabase) {
    db.exec(`CREATE TABLE IF NOT EXISTS facility_site_options (id TEXT PRIMARY KEY, club_id TEXT NOT NULL, district_id TEXT NOT NULL, municipality_name TEXT NOT NULL, site_type TEXT NOT NULL, arrangement TEXT NOT NULL, cost_band TEXT NOT NULL, accessibility_band TEXT NOT NULL, catchment_band TEXT NOT NULL, community_value_band TEXT NOT NULL, government_conditions_json TEXT NOT NULL, readiness TEXT NOT NULL, provenance_status TEXT NOT NULL); CREATE INDEX IF NOT EXISTS idx_facility_sites_club ON facility_site_options(club_id, district_id); CREATE TABLE IF NOT EXISTS facility_project_plans (id TEXT PRIMARY KEY, project_id TEXT NOT NULL UNIQUE, club_id TEXT NOT NULL, project_type TEXT NOT NULL, mode TEXT NOT NULL, scope TEXT NOT NULL, components_json TEXT NOT NULL, site_option_id TEXT, funding_source TEXT NOT NULL, government_application_id TEXT, rationale TEXT NOT NULL, cost_band TEXT NOT NULL, duration_band TEXT NOT NULL, expected_improvement_json TEXT NOT NULL, created_on TEXT NOT NULL, provenance_status TEXT NOT NULL); CREATE INDEX IF NOT EXISTS idx_facility_plans_club ON facility_project_plans(club_id, created_on);`);
  }
  upsertSiteOption(value: FacilitySiteOption): void { this.db.prepare(`INSERT INTO facility_site_options VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET municipality_name=excluded.municipality_name,arrangement=excluded.arrangement,cost_band=excluded.cost_band,accessibility_band=excluded.accessibility_band,catchment_band=excluded.catchment_band,community_value_band=excluded.community_value_band,government_conditions_json=excluded.government_conditions_json,readiness=excluded.readiness`).run(value.id,value.clubId,value.districtId,value.municipalityName,value.siteType,value.arrangement,value.costBand,value.accessibilityBand,value.catchmentBand,value.communityValueBand,JSON.stringify(value.governmentConditions),value.readiness,value.provenanceStatus); }
  siteOptions(clubId: EntityId, districtId?: EntityId): FacilitySiteOption[] { const rows=(districtId?this.db.prepare("SELECT * FROM facility_site_options WHERE club_id=? AND district_id=? ORDER BY id").all(clubId,districtId):this.db.prepare("SELECT * FROM facility_site_options WHERE club_id=? ORDER BY district_id,id").all(clubId)) as any[]; return rows.map(site); }
  upsertPlan(value: FacilityProjectPlan): void { this.db.prepare(`INSERT INTO facility_project_plans VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(project_id) DO UPDATE SET mode=excluded.mode,scope=excluded.scope,components_json=excluded.components_json,site_option_id=excluded.site_option_id,funding_source=excluded.funding_source,government_application_id=excluded.government_application_id,rationale=excluded.rationale,cost_band=excluded.cost_band,duration_band=excluded.duration_band,expected_improvement_json=excluded.expected_improvement_json`).run(value.id,value.projectId,value.clubId,value.projectType,value.mode,value.scope,JSON.stringify(value.components),value.siteOptionId??null,value.fundingSource,value.governmentApplicationId??null,value.rationale,value.costBand,value.durationBand,JSON.stringify(value.expectedImprovement),value.createdOn,value.provenanceStatus); }
  planByProject(projectId: EntityId): FacilityProjectPlan | undefined { const row=this.db.prepare("SELECT * FROM facility_project_plans WHERE project_id=?").get(projectId) as any; return row?plan(row):undefined; }
  plans(clubId?: EntityId): FacilityProjectPlan[] { const rows=(clubId?this.db.prepare("SELECT * FROM facility_project_plans WHERE club_id=? ORDER BY created_on,id").all(clubId):this.db.prepare("SELECT * FROM facility_project_plans ORDER BY club_id,created_on,id").all()) as any[]; return rows.map(plan); }
}
