import type { EntityId, FederationElectionCandidate, FederationElectionCycle, FederationElectionResult } from "@nepal-football-sim/shared-types";
import type { GameDatabase } from "./connection.js";

export class FederationPoliticsRepository {
  constructor(private readonly db: GameDatabase) {}
  upsertCycle(cycle: FederationElectionCycle): void { this.db.prepare(`INSERT INTO federation_election_cycles (id,federation_id,nomination_start,election_date,term_years,status,provenance_status) VALUES (?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=excluded.status`).run(cycle.id, cycle.federationId, cycle.nominationStart, cycle.electionDate, cycle.termYears, cycle.status, cycle.provenanceStatus); }
  cycles(federationId?: EntityId): FederationElectionCycle[] { const rows = (federationId ? this.db.prepare("SELECT * FROM federation_election_cycles WHERE federation_id=? ORDER BY election_date,id").all(federationId) : this.db.prepare("SELECT * FROM federation_election_cycles ORDER BY federation_id,election_date,id").all()) as any[]; return rows.map((r) => ({ id: r.id, federationId: r.federation_id, nominationStart: r.nomination_start, electionDate: r.election_date, termYears: r.term_years, status: r.status, provenanceStatus: r.provenance_status })); }
  upsertCandidate(candidate: FederationElectionCandidate): void { this.db.prepare(`INSERT INTO federation_election_candidates (id,cycle_id,federation_id,person_id,reputation,support_base,committee_influence,voting_blocs_json,manifesto_json,incumbent,status,provenance_status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=excluded.status`).run(candidate.id, candidate.cycleId, candidate.federationId, candidate.personId, candidate.reputation, candidate.supportBase, candidate.committeeInfluence, JSON.stringify(candidate.votingBlocs), JSON.stringify(candidate.manifesto), candidate.incumbent ? 1 : 0, candidate.status, candidate.provenanceStatus); }
  candidates(cycleId?: EntityId): FederationElectionCandidate[] { const rows = (cycleId ? this.db.prepare("SELECT * FROM federation_election_candidates WHERE cycle_id=? ORDER BY id").all(cycleId) : this.db.prepare("SELECT * FROM federation_election_candidates ORDER BY cycle_id,id").all()) as any[]; return rows.map((r) => ({ id: r.id, cycleId: r.cycle_id, federationId: r.federation_id, personId: r.person_id, reputation: r.reputation, supportBase: r.support_base, committeeInfluence: r.committee_influence, votingBlocs: JSON.parse(r.voting_blocs_json), manifesto: JSON.parse(r.manifesto_json), incumbent: Boolean(r.incumbent), status: r.status, provenanceStatus: r.provenance_status })); }
  upsertResult(result: FederationElectionResult): void { this.db.prepare(`INSERT INTO federation_election_results (id,cycle_id,federation_id,winner_candidate_id,elected_person_id,votes_json,decided_at,status,provenance_status) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING`).run(result.id, result.cycleId, result.federationId, result.winnerCandidateId, result.electedPersonId, JSON.stringify(result.votes), result.decidedAt, result.status, result.provenanceStatus); }
  results(federationId?: EntityId): FederationElectionResult[] { const rows = (federationId ? this.db.prepare("SELECT * FROM federation_election_results WHERE federation_id=? ORDER BY decided_at,id").all(federationId) : this.db.prepare("SELECT * FROM federation_election_results ORDER BY federation_id,decided_at,id").all()) as any[]; return rows.map((r) => ({ id: r.id, cycleId: r.cycle_id, federationId: r.federation_id, winnerCandidateId: r.winner_candidate_id, electedPersonId: r.elected_person_id, votes: JSON.parse(r.votes_json), decidedAt: r.decided_at, status: r.status, provenanceStatus: r.provenance_status })); }
}
