import type { EntityId, FederationCoalitionState, FederationCommitteeMembership, FederationGovernanceEvent, FederationGovernanceProposal, FederationManifestoCommitment } from "@nepal-football-sim/shared-types";
import type { GameDatabase } from "./connection.js";

export class FederationGovernancePhaseBRepository {
  constructor(private readonly db: GameDatabase) {}
  upsertMembership(x: FederationCommitteeMembership): void { this.db.prepare(`INSERT INTO federation_committee_memberships (id,federation_id,committee_id,person_id,influence,starts_on,ends_on,status,provenance_status) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET influence=excluded.influence,ends_on=excluded.ends_on,status=excluded.status`).run(x.id,x.federationId,x.committeeId,x.personId,x.influence,x.startsOn,x.endsOn??null,x.status,x.provenanceStatus); }
  memberships(federationId: EntityId, committeeId?: EntityId): FederationCommitteeMembership[] { const rows=(committeeId?this.db.prepare("SELECT * FROM federation_committee_memberships WHERE federation_id=? AND committee_id=? ORDER BY id").all(federationId,committeeId):this.db.prepare("SELECT * FROM federation_committee_memberships WHERE federation_id=? ORDER BY committee_id,id").all(federationId)) as any[]; return rows.map(r=>({id:r.id,federationId:r.federation_id,committeeId:r.committee_id,personId:r.person_id,influence:r.influence,startsOn:r.starts_on,endsOn:r.ends_on??undefined,status:r.status,provenanceStatus:r.provenance_status})); }
  upsertProposal(x: FederationGovernanceProposal): void { this.db.prepare(`INSERT INTO federation_governance_proposals (id,federation_id,proposed_by_person_id,title,policy_area,target_committee,payload_json,proposed_at,reviewed_at,decided_at,status,votes_json,provenance_status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET reviewed_at=excluded.reviewed_at,decided_at=excluded.decided_at,status=excluded.status,votes_json=excluded.votes_json`).run(x.id,x.federationId,x.proposedByPersonId,x.title,x.policyArea,x.targetCommittee,JSON.stringify(x.payload),x.proposedAt,x.reviewedAt??null,x.decidedAt??null,x.status,JSON.stringify(x.votes),x.provenanceStatus); }
  proposals(federationId?: EntityId): FederationGovernanceProposal[] { const rows=(federationId?this.db.prepare("SELECT * FROM federation_governance_proposals WHERE federation_id=? ORDER BY proposed_at,id").all(federationId):this.db.prepare("SELECT * FROM federation_governance_proposals ORDER BY federation_id,proposed_at,id").all()) as any[]; return rows.map(r=>({id:r.id,federationId:r.federation_id,proposedByPersonId:r.proposed_by_person_id,title:r.title,policyArea:r.policy_area,targetCommittee:r.target_committee,payload:JSON.parse(r.payload_json),proposedAt:r.proposed_at,reviewedAt:r.reviewed_at??undefined,decidedAt:r.decided_at??undefined,status:r.status,votes:JSON.parse(r.votes_json),provenanceStatus:r.provenance_status})); }
  upsertCommitment(x: FederationManifestoCommitment): void { this.db.prepare(`INSERT INTO federation_manifesto_commitments (id,federation_id,president_person_id,election_cycle_id,policy_area,promise,target_value,progress,due_date,status,last_updated,provenance_status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET progress=excluded.progress,status=excluded.status,last_updated=excluded.last_updated`).run(x.id,x.federationId,x.presidentPersonId,x.electionCycleId,x.policyArea,x.promise,x.targetValue,x.progress,x.dueDate,x.status,x.lastUpdated,x.provenanceStatus); }
  commitments(federationId: EntityId): FederationManifestoCommitment[] { const rows=this.db.prepare("SELECT * FROM federation_manifesto_commitments WHERE federation_id=? ORDER BY due_date,id").all(federationId) as any[]; return rows.map(r=>({id:r.id,federationId:r.federation_id,presidentPersonId:r.president_person_id,electionCycleId:r.election_cycle_id,policyArea:r.policy_area,promise:r.promise,targetValue:r.target_value,progress:r.progress,dueDate:r.due_date,status:r.status,lastUpdated:r.last_updated,provenanceStatus:r.provenance_status})); }
  upsertCoalition(x: FederationCoalitionState): void { this.db.prepare(`INSERT INTO federation_coalition_states (federation_id,president_person_id,confidence,coalition_support,no_confidence_threshold,last_updated,status,provenance_status) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(federation_id) DO UPDATE SET president_person_id=excluded.president_person_id,confidence=excluded.confidence,coalition_support=excluded.coalition_support,last_updated=excluded.last_updated,status=excluded.status`).run(x.federationId,x.presidentPersonId,x.confidence,x.coalitionSupport,x.noConfidenceThreshold,x.lastUpdated,x.status,x.provenanceStatus); }
  coalition(federationId: EntityId): FederationCoalitionState|undefined { const r=this.db.prepare("SELECT * FROM federation_coalition_states WHERE federation_id=?").get(federationId) as any; return r?{federationId:r.federation_id,presidentPersonId:r.president_person_id,confidence:r.confidence,coalitionSupport:r.coalition_support,noConfidenceThreshold:r.no_confidence_threshold,lastUpdated:r.last_updated,status:r.status,provenanceStatus:r.provenance_status}:undefined; }
  event(x: FederationGovernanceEvent): void { this.db.prepare(`INSERT INTO federation_governance_events (id,federation_id,event_date,event_type,subject_id,summary,payload_json,provenance_status) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING`).run(x.id,x.federationId,x.date,x.eventType,x.subjectId,x.summary,JSON.stringify(x.payload),x.provenanceStatus); }
  events(federationId: EntityId): FederationGovernanceEvent[] { const rows=this.db.prepare("SELECT * FROM federation_governance_events WHERE federation_id=? ORDER BY event_date,id").all(federationId) as any[]; return rows.map(r=>({id:r.id,federationId:r.federation_id,date:r.event_date,eventType:r.event_type,subjectId:r.subject_id,summary:r.summary,payload:JSON.parse(r.payload_json),provenanceStatus:r.provenance_status})); }
}
