import type {
  EntityId,
  ExternalClubContext,
  ExternalFederationContext,
  ExternalLeagueContext,
  ExternalLeagueSeason,
  ExternalPlayerContext,
  ForeignScoutingInterestRecord,
} from "@nepal-football-sim/shared-types";
import type { GameDatabase } from "./connection.js";

export class GlobalFootballContextRepository {
  constructor(private readonly db: GameDatabase) {}

  upsertFederation(value: ExternalFederationContext): void {
    this.db.prepare(`INSERT INTO external_federation_context (federation_id,country_id,confederation,reputation,simulation_depth,updated_on) VALUES (?,?,?,?,?,?) ON CONFLICT(federation_id) DO UPDATE SET reputation=excluded.reputation,updated_on=excluded.updated_on`).run(value.federationId, value.countryId, value.confederation, value.reputation, value.simulationDepth, value.updatedOn);
  }
  federations(): ExternalFederationContext[] { return (this.db.prepare("SELECT * FROM external_federation_context ORDER BY federation_id").all() as Array<Record<string, unknown>>).map((r) => ({ federationId: r.federation_id as EntityId, countryId: r.country_id as EntityId, confederation: r.confederation as ExternalFederationContext["confederation"], reputation: Number(r.reputation), simulationDepth: "CONTEXT_ONLY", updatedOn: String(r.updated_on) })); }
  upsertLeague(value: ExternalLeagueContext): void { this.db.prepare(`INSERT INTO external_league_context (league_id,federation_id,country_id,tier,reputation,simulation_depth,continental_qualification) VALUES (?,?,?,?,?,?,?) ON CONFLICT(league_id) DO UPDATE SET reputation=excluded.reputation,continental_qualification=excluded.continental_qualification`).run(value.leagueId,value.federationId,value.countryId,value.tier,value.reputation,value.simulationDepth,value.continentalQualification?1:0); }
  leagues(): ExternalLeagueContext[] { return (this.db.prepare("SELECT * FROM external_league_context ORDER BY league_id").all() as Array<Record<string, unknown>>).map((r) => ({ leagueId:r.league_id as EntityId,federationId:r.federation_id as EntityId,countryId:r.country_id as EntityId,tier:Number(r.tier),reputation:Number(r.reputation),simulationDepth:"CONTEXT_ONLY",continentalQualification:Boolean(r.continental_qualification) })); }
  upsertClub(value: ExternalClubContext): void { this.db.prepare(`INSERT INTO external_club_context (club_id,league_id,federation_id,country_id,reputation,financial_band,academy_strength,scouting_reach,recruitment_regions_json,simulation_depth) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(club_id) DO UPDATE SET reputation=excluded.reputation,academy_strength=excluded.academy_strength,scouting_reach=excluded.scouting_reach,recruitment_regions_json=excluded.recruitment_regions_json`).run(value.clubId,value.leagueId,value.federationId,value.countryId,value.reputation,value.financialBand,value.academyStrength,value.scoutingReach,JSON.stringify(value.recruitmentRegions),value.simulationDepth); }
  clubs(): ExternalClubContext[] { return (this.db.prepare("SELECT * FROM external_club_context ORDER BY club_id").all() as Array<Record<string, unknown>>).map((r) => ({ clubId:r.club_id as EntityId,leagueId:r.league_id as EntityId,federationId:r.federation_id as EntityId,countryId:r.country_id as EntityId,reputation:Number(r.reputation),financialBand:r.financial_band as ExternalClubContext["financialBand"],academyStrength:Number(r.academy_strength),scoutingReach:Number(r.scouting_reach),recruitmentRegions:JSON.parse(String(r.recruitment_regions_json)) as string[],simulationDepth:"CONTEXT_ONLY" })); }
  upsertSeason(value: ExternalLeagueSeason): void { this.db.prepare(`INSERT INTO external_league_seasons (id,league_id,season_label,champion_club_id,qualifier_club_ids_json,relegated_club_ids_json,completed_on,status,provenance_status) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(league_id,season_label) DO UPDATE SET champion_club_id=excluded.champion_club_id,qualifier_club_ids_json=excluded.qualifier_club_ids_json,relegated_club_ids_json=excluded.relegated_club_ids_json,completed_on=excluded.completed_on,status=excluded.status`).run(value.id,value.leagueId,value.seasonLabel,value.championClubId??null,JSON.stringify(value.continentalQualifierClubIds),JSON.stringify(value.relegatedClubIds),value.completedOn,value.status,value.provenanceStatus); }
  seasons(leagueId?: EntityId): ExternalLeagueSeason[] { const rows=(leagueId?this.db.prepare("SELECT * FROM external_league_seasons WHERE league_id=? ORDER BY season_label").all(leagueId):this.db.prepare("SELECT * FROM external_league_seasons ORDER BY season_label,league_id").all()) as Array<Record<string, unknown>>; return rows.map((r)=>({id:r.id as EntityId,leagueId:r.league_id as EntityId,seasonLabel:String(r.season_label),championClubId:(r.champion_club_id as EntityId|undefined)??undefined,continentalQualifierClubIds:JSON.parse(String(r.qualifier_club_ids_json)) as EntityId[],relegatedClubIds:JSON.parse(String(r.relegated_club_ids_json)) as EntityId[],completedOn:String(r.completed_on),status:"COMPLETED",provenanceStatus:"SIMULATION_ONLY"})); }
  upsertPlayer(value: ExternalPlayerContext): void { this.db.prepare(`INSERT INTO external_player_context (player_id,club_id,region,reputation,interest_level,career_state,available_on,updated_on) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(player_id) DO UPDATE SET club_id=excluded.club_id,reputation=excluded.reputation,interest_level=excluded.interest_level,career_state=excluded.career_state,available_on=excluded.available_on,updated_on=excluded.updated_on`).run(value.playerId,value.clubId??null,value.region,value.reputation,value.interestLevel,value.careerState,value.availableOn??null,value.updatedOn); }
  players(): ExternalPlayerContext[] { return (this.db.prepare("SELECT * FROM external_player_context ORDER BY player_id").all() as Array<Record<string, unknown>>).map((r)=>({playerId:r.player_id as EntityId,clubId:(r.club_id as EntityId|undefined)??undefined,region:String(r.region),reputation:Number(r.reputation),interestLevel:r.interest_level as ExternalPlayerContext["interestLevel"],careerState:r.career_state as ExternalPlayerContext["careerState"],availableOn:(r.available_on as string|undefined)??undefined,updatedOn:String(r.updated_on)})); }
  upsertInterest(value: ForeignScoutingInterestRecord): void { this.db.prepare(`INSERT INTO foreign_scouting_interest (id,external_club_id,target_player_id,level,score,first_observed_on,last_observed_on,provenance_status) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(external_club_id,target_player_id) DO UPDATE SET level=excluded.level,score=excluded.score,last_observed_on=excluded.last_observed_on`).run(value.id,value.externalClubId,value.targetPlayerId,value.level,value.score,value.firstObservedOn,value.lastObservedOn,value.provenanceStatus); }
  interests(targetPlayerId?: EntityId): ForeignScoutingInterestRecord[] { const rows=(targetPlayerId?this.db.prepare("SELECT * FROM foreign_scouting_interest WHERE target_player_id=? ORDER BY score DESC").all(targetPlayerId):this.db.prepare("SELECT * FROM foreign_scouting_interest ORDER BY score DESC").all()) as Array<Record<string, unknown>>; return rows.map((r)=>({id:r.id as EntityId,externalClubId:r.external_club_id as EntityId,targetPlayerId:r.target_player_id as EntityId,level:r.level as ForeignScoutingInterestRecord["level"],score:Number(r.score),firstObservedOn:String(r.first_observed_on),lastObservedOn:String(r.last_observed_on),provenanceStatus:"SIMULATION_ONLY"})); }
}
