import type { EntityId, GovernmentFundingApplication, GovernmentInstitution, GovernmentRelationship } from "@nepal-football-sim/shared-types";
import type { GameDatabase } from "./connection.js";

const mapInstitution = (r: any): GovernmentInstitution => ({ id: r.id, name: r.name, institutionType: r.institution_type, locationId: r.location_id ?? undefined, profile: JSON.parse(r.profile_json), provenanceStatus: r.provenance_status });
const mapApplication = (r: any): GovernmentFundingApplication => ({ id: r.id, institutionId: r.institution_id, federationId: r.federation_id ?? undefined, clubId: r.club_id ?? undefined, projectId: r.project_id ?? undefined, fundingType: r.funding_type, requestedAmount: r.requested_amount, approvedAmount: r.approved_amount ?? undefined, status: r.status, conditions: JSON.parse(r.conditions_json), proposedOn: r.proposed_on, decidedOn: r.decided_on ?? undefined, decisionReason: r.decision_reason ?? undefined, provenanceStatus: r.provenance_status });
const mapRelationship = (r: any): GovernmentRelationship => ({ id: r.id, institutionId: r.institution_id, entityId: r.entity_id, entityType: r.entity_type, trust: r.trust, lastInteractionOn: r.last_interaction_on ?? undefined, provenanceStatus: r.provenance_status });

export class GovernmentRepository {
  constructor(private readonly db: GameDatabase) {
    db.exec(`CREATE TABLE IF NOT EXISTS government_institutions (id TEXT PRIMARY KEY, name TEXT NOT NULL, institution_type TEXT NOT NULL, location_id TEXT, profile_json TEXT NOT NULL, provenance_status TEXT NOT NULL); CREATE TABLE IF NOT EXISTS government_funding_applications (id TEXT PRIMARY KEY, institution_id TEXT NOT NULL, federation_id TEXT, club_id TEXT, project_id TEXT, funding_type TEXT NOT NULL, requested_amount INTEGER NOT NULL, approved_amount INTEGER, status TEXT NOT NULL, conditions_json TEXT NOT NULL, proposed_on TEXT NOT NULL, decided_on TEXT, decision_reason TEXT, provenance_status TEXT NOT NULL); CREATE TABLE IF NOT EXISTS government_relationships (id TEXT PRIMARY KEY, institution_id TEXT NOT NULL, entity_id TEXT NOT NULL, entity_type TEXT NOT NULL, trust INTEGER NOT NULL, last_interaction_on TEXT, provenance_status TEXT NOT NULL, UNIQUE(institution_id, entity_id));`);
  }
  upsertInstitution(v: GovernmentInstitution): void { this.db.prepare(`INSERT INTO government_institutions (id,name,institution_type,location_id,profile_json,provenance_status) VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,institution_type=excluded.institution_type,location_id=excluded.location_id,profile_json=excluded.profile_json`).run(v.id,v.name,v.institutionType,v.locationId??null,JSON.stringify(v.profile),v.provenanceStatus); }
  institution(id: EntityId): GovernmentInstitution | undefined { const r=this.db.prepare("SELECT * FROM government_institutions WHERE id=?").get(id) as any; return r?mapInstitution(r):undefined; }
  institutions(type?: GovernmentInstitution["institutionType"]): GovernmentInstitution[] { const rows=(type?this.db.prepare("SELECT * FROM government_institutions WHERE institution_type=? ORDER BY id").all(type):this.db.prepare("SELECT * FROM government_institutions ORDER BY id").all()) as any[]; return rows.map(mapInstitution); }
  upsertApplication(v: GovernmentFundingApplication): void { this.db.prepare(`INSERT INTO government_funding_applications (id,institution_id,federation_id,club_id,project_id,funding_type,requested_amount,approved_amount,status,conditions_json,proposed_on,decided_on,decision_reason,provenance_status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET approved_amount=excluded.approved_amount,status=excluded.status,conditions_json=excluded.conditions_json,decided_on=excluded.decided_on,decision_reason=excluded.decision_reason`).run(v.id,v.institutionId,v.federationId??null,v.clubId??null,v.projectId??null,v.fundingType,v.requestedAmount,v.approvedAmount??null,v.status,JSON.stringify(v.conditions),v.proposedOn,v.decidedOn??null,v.decisionReason??null,v.provenanceStatus); }
  applications(institutionId?: EntityId): GovernmentFundingApplication[] { const rows=(institutionId?this.db.prepare("SELECT * FROM government_funding_applications WHERE institution_id=? ORDER BY proposed_on,id").all(institutionId):this.db.prepare("SELECT * FROM government_funding_applications ORDER BY proposed_on,id").all()) as any[]; return rows.map(mapApplication); }
  upsertRelationship(v: GovernmentRelationship): void { this.db.prepare(`INSERT INTO government_relationships (id,institution_id,entity_id,entity_type,trust,last_interaction_on,provenance_status) VALUES (?,?,?,?,?,?,?) ON CONFLICT(institution_id,entity_id) DO UPDATE SET trust=excluded.trust,last_interaction_on=excluded.last_interaction_on`).run(v.id,v.institutionId,v.entityId,v.entityType,v.trust,v.lastInteractionOn??null,v.provenanceStatus); }
  relationships(institutionId?: EntityId): GovernmentRelationship[] { const rows=(institutionId?this.db.prepare("SELECT * FROM government_relationships WHERE institution_id=? ORDER BY entity_id").all(institutionId):this.db.prepare("SELECT * FROM government_relationships ORDER BY institution_id,entity_id").all()) as any[]; return rows.map(mapRelationship); }
}
