import type { EntityId, GrassrootsProgramme, GrassrootsProgrammeHistory } from "@nepal-football-sim/shared-types";
import type { GameDatabase } from "./connection.js";

const mapProgramme = (r: any): GrassrootsProgramme => ({ id:r.id, name:r.name, programmeType:r.programme_type, locationId:r.location_id, locationKind:r.location_kind, federationId:r.federation_id ?? undefined, fundingApplicationId:r.funding_application_id ?? undefined, annualFunding:r.annual_funding, coachingAccess:r.coaching_access, facilityAccess:r.facility_access, regionalParticipation:r.regional_participation, localFootballPriority:r.local_football_priority, yearsActive:r.years_active, status:r.status, provenanceStatus:r.provenance_status });
const mapHistory = (r: any): GrassrootsProgrammeHistory => ({ id:r.id, programmeId:r.programme_id, date:r.event_date, eventType:r.event_type, quality:r.quality, delayedImpact:r.delayed_impact, provenanceStatus:r.provenance_status });

export class GrassrootsRepository {
  constructor(private readonly db: GameDatabase) { db.exec(`CREATE TABLE IF NOT EXISTS grassroots_programmes (id TEXT PRIMARY KEY, name TEXT NOT NULL, programme_type TEXT NOT NULL, location_id TEXT NOT NULL, location_kind TEXT NOT NULL, federation_id TEXT, funding_application_id TEXT, annual_funding INTEGER NOT NULL, coaching_access INTEGER NOT NULL, facility_access INTEGER NOT NULL, regional_participation INTEGER NOT NULL, local_football_priority INTEGER NOT NULL, years_active INTEGER NOT NULL, status TEXT NOT NULL, provenance_status TEXT NOT NULL); CREATE TABLE IF NOT EXISTS grassroots_programme_history (id TEXT PRIMARY KEY, programme_id TEXT NOT NULL, event_date TEXT NOT NULL, event_type TEXT NOT NULL, quality INTEGER NOT NULL, delayed_impact INTEGER NOT NULL, provenance_status TEXT NOT NULL);`); }
  upsertProgramme(v: GrassrootsProgramme): void { this.db.prepare(`INSERT INTO grassroots_programmes (id,name,programme_type,location_id,location_kind,federation_id,funding_application_id,annual_funding,coaching_access,facility_access,regional_participation,local_football_priority,years_active,status,provenance_status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,annual_funding=excluded.annual_funding,coaching_access=excluded.coaching_access,facility_access=excluded.facility_access,regional_participation=excluded.regional_participation,local_football_priority=excluded.local_football_priority,years_active=excluded.years_active,status=excluded.status,funding_application_id=excluded.funding_application_id`).run(v.id,v.name,v.programmeType,v.locationId,v.locationKind,v.federationId??null,v.fundingApplicationId??null,v.annualFunding,v.coachingAccess,v.facilityAccess,v.regionalParticipation,v.localFootballPriority,v.yearsActive,v.status,v.provenanceStatus); }
  programmes(locationId?: EntityId): GrassrootsProgramme[] { const rows=(locationId?this.db.prepare("SELECT * FROM grassroots_programmes WHERE location_id=? ORDER BY id").all(locationId):this.db.prepare("SELECT * FROM grassroots_programmes ORDER BY location_id,id").all()) as any[]; return rows.map(mapProgramme); }
  programme(id: EntityId): GrassrootsProgramme | undefined { const r=this.db.prepare("SELECT * FROM grassroots_programmes WHERE id=?").get(id) as any; return r?mapProgramme(r):undefined; }
  insertHistory(v: GrassrootsProgrammeHistory): void { this.db.prepare("INSERT INTO grassroots_programme_history (id,programme_id,event_date,event_type,quality,delayed_impact,provenance_status) VALUES (?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING").run(v.id,v.programmeId,v.date,v.eventType,v.quality,v.delayedImpact,v.provenanceStatus); }
  history(programmeId?: EntityId): GrassrootsProgrammeHistory[] { const rows=(programmeId?this.db.prepare("SELECT * FROM grassroots_programme_history WHERE programme_id=? ORDER BY event_date,id").all(programmeId):this.db.prepare("SELECT * FROM grassroots_programme_history ORDER BY event_date,programme_id,id").all()) as any[]; return rows.map(mapHistory); }
}
