import type { EntityId, InsuranceClaim, InsurancePolicy, InsurerProfile } from "@nepal-football-sim/shared-types";
import type { GameDatabase } from "./connection.js";
const insurer=(r:any):InsurerProfile=>({id:r.id,name:r.name,financialStrength:r.financial_strength,reliability:r.reliability,premiumLevel:r.premium_level,coverageQuality:r.coverage_quality,exclusions:JSON.parse(r.exclusions_json),claimReputation:r.claim_reputation,provenanceStatus:r.provenance_status});
const policy=(r:any):InsurancePolicy=>({id:r.id,ownerType:r.owner_type,ownerId:r.owner_id,insurerId:r.insurer_id,coverage:JSON.parse(r.coverage_json),premium:r.premium,deductible:r.deductible,coverageCap:r.coverage_cap,startDate:r.start_date,endDate:r.end_date,status:r.status,provenanceStatus:r.provenance_status});
const claim=(r:any):InsuranceClaim=>({id:r.id,policyId:r.policy_id,injuryId:r.injury_id,personId:r.person_id,eventType:r.event_type,incurredCost:r.incurred_cost,eligibleAmount:r.eligible_amount,status:r.status,openedOn:r.opened_on,reviewedOn:r.reviewed_on??undefined,paidOn:r.paid_on??undefined,decisionReason:r.decision_reason??undefined,ledgerEntryId:r.ledger_entry_id??undefined,provenanceStatus:r.provenance_status});
export class InsuranceRepository { constructor(private readonly db:GameDatabase){db.exec(`CREATE TABLE IF NOT EXISTS insurer_profiles (id TEXT PRIMARY KEY,name TEXT NOT NULL,financial_strength INTEGER NOT NULL,reliability INTEGER NOT NULL,premium_level INTEGER NOT NULL,coverage_quality INTEGER NOT NULL,exclusions_json TEXT NOT NULL,claim_reputation INTEGER NOT NULL,provenance_status TEXT NOT NULL); CREATE TABLE IF NOT EXISTS insurance_policies (id TEXT PRIMARY KEY,owner_type TEXT NOT NULL,owner_id TEXT NOT NULL,insurer_id TEXT NOT NULL,premium INTEGER NOT NULL,deductible INTEGER NOT NULL,coverage_cap INTEGER NOT NULL,coverage_json TEXT NOT NULL,start_date TEXT NOT NULL,end_date TEXT NOT NULL,status TEXT NOT NULL,provenance_status TEXT NOT NULL); CREATE TABLE IF NOT EXISTS insurance_claims (id TEXT PRIMARY KEY,policy_id TEXT NOT NULL,injury_id TEXT NOT NULL,person_id TEXT NOT NULL,event_type TEXT NOT NULL,incurred_cost INTEGER NOT NULL,eligible_amount INTEGER NOT NULL,status TEXT NOT NULL,opened_on TEXT NOT NULL,reviewed_on TEXT,paid_on TEXT,decision_reason TEXT,ledger_entry_id TEXT,provenance_status TEXT NOT NULL,UNIQUE(policy_id,injury_id,event_type));`);}
 upsertInsurer(v:InsurerProfile):void{this.db.prepare(`INSERT INTO insurer_profiles (id,name,financial_strength,reliability,premium_level,coverage_quality,exclusions_json,claim_reputation,provenance_status) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET financial_strength=excluded.financial_strength,reliability=excluded.reliability,premium_level=excluded.premium_level,coverage_quality=excluded.coverage_quality,exclusions_json=excluded.exclusions_json,claim_reputation=excluded.claim_reputation`).run(v.id,v.name,v.financialStrength,v.reliability,v.premiumLevel,v.coverageQuality,JSON.stringify(v.exclusions),v.claimReputation,v.provenanceStatus);}
 insurers():InsurerProfile[]{return (this.db.prepare("SELECT * FROM insurer_profiles ORDER BY id").all() as any[]).map(insurer);}
 insurer(id:EntityId):InsurerProfile|undefined{const r=this.db.prepare("SELECT * FROM insurer_profiles WHERE id=?").get(id) as any;return r?insurer(r):undefined;}
 upsertPolicy(v:InsurancePolicy):void{this.db.prepare(`INSERT INTO insurance_policies (id,owner_type,owner_id,insurer_id,premium,deductible,coverage_cap,coverage_json,start_date,end_date,status,provenance_status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET premium=excluded.premium,deductible=excluded.deductible,coverage_cap=excluded.coverage_cap,coverage_json=excluded.coverage_json,status=excluded.status`).run(v.id,v.ownerType,v.ownerId,v.insurerId,v.premium,v.deductible,v.coverageCap,JSON.stringify(v.coverage),v.startDate,v.endDate,v.status,v.provenanceStatus);}
 policies(ownerId?:EntityId):InsurancePolicy[]{const rows=(ownerId?this.db.prepare("SELECT * FROM insurance_policies WHERE owner_id=? ORDER BY start_date,id").all(ownerId):this.db.prepare("SELECT * FROM insurance_policies ORDER BY owner_id,start_date,id").all()) as any[];return rows.map(policy);}
 policy(id:EntityId):InsurancePolicy|undefined{const r=this.db.prepare("SELECT * FROM insurance_policies WHERE id=?").get(id) as any;return r?policy(r):undefined;}
 upsertClaim(v:InsuranceClaim):void{this.db.prepare(`INSERT INTO insurance_claims (id,policy_id,injury_id,person_id,event_type,incurred_cost,eligible_amount,status,opened_on,reviewed_on,paid_on,decision_reason,ledger_entry_id,provenance_status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET eligible_amount=excluded.eligible_amount,status=excluded.status,reviewed_on=excluded.reviewed_on,paid_on=excluded.paid_on,decision_reason=excluded.decision_reason,ledger_entry_id=excluded.ledger_entry_id`).run(v.id,v.policyId,v.injuryId,v.personId,v.eventType,v.incurredCost,v.eligibleAmount,v.status,v.openedOn,v.reviewedOn??null,v.paidOn??null,v.decisionReason??null,v.ledgerEntryId??null,v.provenanceStatus);}
 claims(policyId?:EntityId):InsuranceClaim[]{const rows=(policyId?this.db.prepare("SELECT * FROM insurance_claims WHERE policy_id=? ORDER BY opened_on,id").all(policyId):this.db.prepare("SELECT * FROM insurance_claims ORDER BY opened_on,id").all()) as any[];return rows.map(claim);}
}
