import type { BroadcasterProfile, EntityId, FederationMediaRightsOffer, FederationMediaRightsPackage } from "@nepal-football-sim/shared-types";
import type { GameDatabase } from "./connection.js";

const mapBroadcaster = (r: any): BroadcasterProfile => ({ id:r.id,name:r.name,marketReach:r.market_reach,reliability:r.reliability,financialStrength:r.financial_strength,productionCapability:r.production_capability,domesticReach:r.domestic_reach,internationalReach:r.international_reach,provenanceStatus:r.provenance_status });
const mapPackage = (r: any): FederationMediaRightsPackage => ({ id:r.id,federationId:r.federation_id,name:r.name,category:r.category,competitionId:r.competition_id??undefined,nationalTeamId:r.national_team_id??undefined,availableFrom:r.available_from,availableTo:r.available_to,status:r.status,retainedByFederation:Boolean(r.retained_by_federation),provenanceStatus:r.provenance_status });
const mapOffer = (r: any): FederationMediaRightsOffer => ({ id:r.id,packageId:r.package_id,federationId:r.federation_id,broadcasterId:r.broadcaster_id,value:r.value,reachScore:r.reach_score,strategicControl:r.strategic_control,productionQuality:r.production_quality,status:r.status,offeredOn:r.offered_on,startDate:r.start_date??undefined,endDate:r.end_date??undefined,federationLedgerEntryId:r.federation_ledger_entry_id??undefined,provenanceStatus:r.provenance_status });

export class MediaRightsRepository {
  constructor(private readonly db: GameDatabase) { db.exec(`CREATE TABLE IF NOT EXISTS broadcaster_profiles (id TEXT PRIMARY KEY,name TEXT NOT NULL,market_reach INTEGER NOT NULL,reliability INTEGER NOT NULL,financial_strength INTEGER NOT NULL,production_capability INTEGER NOT NULL,domestic_reach INTEGER NOT NULL,international_reach INTEGER NOT NULL,provenance_status TEXT NOT NULL); CREATE TABLE IF NOT EXISTS federation_media_rights_packages (id TEXT PRIMARY KEY,federation_id TEXT NOT NULL,name TEXT NOT NULL,category TEXT NOT NULL,competition_id TEXT,national_team_id TEXT,available_from TEXT NOT NULL,available_to TEXT NOT NULL,status TEXT NOT NULL,retained_by_federation INTEGER NOT NULL,provenance_status TEXT NOT NULL); CREATE TABLE IF NOT EXISTS federation_media_rights_offers (id TEXT PRIMARY KEY,package_id TEXT NOT NULL,federation_id TEXT NOT NULL,broadcaster_id TEXT NOT NULL,value INTEGER NOT NULL,reach_score INTEGER NOT NULL,strategic_control INTEGER NOT NULL,production_quality INTEGER NOT NULL,status TEXT NOT NULL,offered_on TEXT NOT NULL,start_date TEXT,end_date TEXT,federation_ledger_entry_id TEXT,provenance_status TEXT NOT NULL);`); }
  upsertBroadcaster(v: BroadcasterProfile): void { this.db.prepare(`INSERT INTO broadcaster_profiles (id,name,market_reach,reliability,financial_strength,production_capability,domestic_reach,international_reach,provenance_status) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,market_reach=excluded.market_reach,reliability=excluded.reliability,financial_strength=excluded.financial_strength,production_capability=excluded.production_capability,domestic_reach=excluded.domestic_reach,international_reach=excluded.international_reach`).run(v.id,v.name,v.marketReach,v.reliability,v.financialStrength,v.productionCapability,v.domesticReach,v.internationalReach,v.provenanceStatus); }
  broadcaster(id: EntityId): BroadcasterProfile | undefined { const r=this.db.prepare("SELECT * FROM broadcaster_profiles WHERE id=?").get(id) as any; return r?mapBroadcaster(r):undefined; }
  broadcasters(): BroadcasterProfile[] { return (this.db.prepare("SELECT * FROM broadcaster_profiles ORDER BY id").all() as any[]).map(mapBroadcaster); }
  upsertPackage(v: FederationMediaRightsPackage): void { this.db.prepare(`INSERT INTO federation_media_rights_packages (id,federation_id,name,category,competition_id,national_team_id,available_from,available_to,status,retained_by_federation,provenance_status) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=excluded.status,retained_by_federation=excluded.retained_by_federation,available_to=excluded.available_to`).run(v.id,v.federationId,v.name,v.category,v.competitionId??null,v.nationalTeamId??null,v.availableFrom,v.availableTo,v.status,v.retainedByFederation?1:0,v.provenanceStatus); }
  packages(federationId?: EntityId): FederationMediaRightsPackage[] { const rows=(federationId?this.db.prepare("SELECT * FROM federation_media_rights_packages WHERE federation_id=? ORDER BY available_from,id").all(federationId):this.db.prepare("SELECT * FROM federation_media_rights_packages ORDER BY federation_id,available_from,id").all()) as any[]; return rows.map(mapPackage); }
  upsertOffer(v: FederationMediaRightsOffer): void { this.db.prepare(`INSERT INTO federation_media_rights_offers (id,package_id,federation_id,broadcaster_id,value,reach_score,strategic_control,production_quality,status,offered_on,start_date,end_date,federation_ledger_entry_id,provenance_status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET value=excluded.value,reach_score=excluded.reach_score,strategic_control=excluded.strategic_control,production_quality=excluded.production_quality,status=excluded.status,start_date=excluded.start_date,end_date=excluded.end_date,federation_ledger_entry_id=excluded.federation_ledger_entry_id`).run(v.id,v.packageId,v.federationId,v.broadcasterId,v.value,v.reachScore,v.strategicControl,v.productionQuality,v.status,v.offeredOn,v.startDate??null,v.endDate??null,v.federationLedgerEntryId??null,v.provenanceStatus); }
  offers(packageId?: EntityId): FederationMediaRightsOffer[] { const rows=(packageId?this.db.prepare("SELECT * FROM federation_media_rights_offers WHERE package_id=? ORDER BY value DESC,id").all(packageId):this.db.prepare("SELECT * FROM federation_media_rights_offers ORDER BY package_id,value DESC,id").all()) as any[]; return rows.map(mapOffer); }
}
