import type { EntityId, MediaInterview, MediaJournalist, MediaJournalistRelationship } from "@nepal-football-sim/shared-types";
import type { GameDatabase } from "./connection.js";

const mapInterview=(r:any):MediaInterview=>({id:r.id,outletId:r.outlet_id,journalistId:r.journalist_id,sourceEntityId:r.source_entity_id,managerPersonId:r.manager_person_id??undefined,interviewDate:r.interview_date,context:r.context,importance:r.importance,questions:JSON.parse(r.questions_json),responses:JSON.parse(r.responses_json),summary:r.summary,managerReputationEffect:r.manager_reputation_effect,clubSupportEffect:r.club_support_effect,status:r.status,provenanceStatus:r.provenance_status,structuredQuestions:r.structured_questions_json?JSON.parse(r.structured_questions_json):undefined,structuredAnswers:r.structured_answers_json?JSON.parse(r.structured_answers_json):undefined,currentQuestionIndex:r.current_question_index??undefined});
export class MediaPhaseBRepository {
  constructor(private readonly db: GameDatabase) {}
  upsertJournalist(x: MediaJournalist): void { this.db.prepare(`INSERT INTO media_journalists (id,outlet_id,name,beat,temperament,reputation,status) VALUES (?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET reputation=excluded.reputation,temperament=excluded.temperament`).run(x.id,x.outletId,x.name,x.beat,x.temperament,x.reputation,x.status); }
  journalists(outletId?: EntityId): MediaJournalist[] { const rows=(outletId?this.db.prepare("SELECT * FROM media_journalists WHERE outlet_id=? ORDER BY id").all(outletId):this.db.prepare("SELECT * FROM media_journalists ORDER BY id").all()) as any[]; return rows.map(r=>({id:r.id,outletId:r.outlet_id,name:r.name,beat:r.beat,temperament:r.temperament,reputation:r.reputation,status:r.status})); }
  upsertRelationship(x: MediaJournalistRelationship): void { this.db.prepare(`INSERT INTO media_journalist_relationships (id,journalist_id,manager_person_id,trust,last_interaction,status) VALUES (?,?,?,?,?,?) ON CONFLICT(journalist_id,manager_person_id) DO UPDATE SET trust=excluded.trust,last_interaction=excluded.last_interaction`).run(x.id,x.journalistId,x.managerPersonId??null,x.trust,x.lastInteraction??null,x.status); }
  relationships(journalistId?: EntityId): MediaJournalistRelationship[] { const rows=(journalistId?this.db.prepare("SELECT * FROM media_journalist_relationships WHERE journalist_id=? ORDER BY id").all(journalistId):this.db.prepare("SELECT * FROM media_journalist_relationships ORDER BY journalist_id,id").all()) as any[]; return rows.map(r=>({id:r.id,journalistId:r.journalist_id,managerPersonId:r.manager_person_id??undefined,trust:r.trust,lastInteraction:r.last_interaction??undefined,status:r.status})); }
  upsertInterview(x: MediaInterview): void { this.db.prepare(`INSERT INTO media_interviews (id,outlet_id,journalist_id,source_entity_id,manager_person_id,interview_date,context,importance,questions_json,responses_json,summary,manager_reputation_effect,club_support_effect,status,provenance_status,structured_questions_json,structured_answers_json,current_question_index) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET responses_json=excluded.responses_json,summary=excluded.summary,manager_reputation_effect=excluded.manager_reputation_effect,club_support_effect=excluded.club_support_effect,status=excluded.status,structured_questions_json=excluded.structured_questions_json,structured_answers_json=excluded.structured_answers_json,current_question_index=excluded.current_question_index`).run(x.id,x.outletId,x.journalistId,x.sourceEntityId,x.managerPersonId??null,x.interviewDate,x.context,x.importance,JSON.stringify(x.questions),JSON.stringify(x.responses),x.summary,x.managerReputationEffect,x.clubSupportEffect,x.status,x.provenanceStatus,x.structuredQuestions?JSON.stringify(x.structuredQuestions):null,x.structuredAnswers?JSON.stringify(x.structuredAnswers):null,x.currentQuestionIndex??null); }
  interviews(managerPersonId?: EntityId): MediaInterview[] { const rows=(managerPersonId?this.db.prepare("SELECT * FROM media_interviews WHERE manager_person_id=? ORDER BY interview_date,id").all(managerPersonId):this.db.prepare("SELECT * FROM media_interviews ORDER BY interview_date,id").all()) as any[]; return rows.map(mapInterview); }
  interview(id: EntityId): MediaInterview | undefined { const row=this.db.prepare("SELECT * FROM media_interviews WHERE id=?").get(id) as any; return row?mapInterview(row):undefined; }
}
