import type { DiasporaRecruitment, EntityId, InternationalCommitment, NationalTeamCampaign, NationalTeamCampLifecycle, NationalTeamInternationalForm, NationalTeamManagementDecision, NationalTeamOperationalPlan, NationalTeamSquadRegistration, NationalTeamWatchlistItem } from "@nepal-football-sim/shared-types";
import type { GameDatabase } from "./connection.js";

export class NationalTeamManagementRepository {
  constructor(private readonly db: GameDatabase) {}
  upsertDecision(x: NationalTeamManagementDecision): void { this.db.prepare(`INSERT INTO national_team_management_decisions (id,federation_id,national_team_id,manager_person_id,decision_date,programme,selected_player_ids_json,captain_player_id,tactical_setup_id,tactical_style,competition_edition_id,status,provenance_status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET selected_player_ids_json=excluded.selected_player_ids_json,captain_player_id=excluded.captain_player_id,tactical_setup_id=excluded.tactical_setup_id,tactical_style=excluded.tactical_style,status=excluded.status`).run(x.id,x.federationId,x.nationalTeamId,x.managerPersonId??null,x.decisionDate,x.programme,JSON.stringify(x.selectedPlayerIds),x.captainPlayerId??null,x.tacticalSetupId??null,x.tacticalStyle??null,x.competitionEditionId??null,x.status,x.provenanceStatus); }
  decisions(nationalTeamId?: EntityId): NationalTeamManagementDecision[] { const rows=(nationalTeamId?this.db.prepare("SELECT * FROM national_team_management_decisions WHERE national_team_id=? ORDER BY decision_date,id").all(nationalTeamId):this.db.prepare("SELECT * FROM national_team_management_decisions ORDER BY national_team_id,decision_date,id").all()) as any[]; return rows.map(r=>({id:r.id,federationId:r.federation_id,nationalTeamId:r.national_team_id,managerPersonId:r.manager_person_id??undefined,decisionDate:r.decision_date,programme:r.programme,selectedPlayerIds:JSON.parse(r.selected_player_ids_json),captainPlayerId:r.captain_player_id??undefined,tacticalSetupId:r.tactical_setup_id??undefined,tacticalStyle:r.tactical_style??undefined,competitionEditionId:r.competition_edition_id??undefined,status:r.status,provenanceStatus:r.provenance_status})); }
  upsertCampaign(x: NationalTeamCampaign): void { this.db.prepare(`INSERT INTO national_team_campaigns (id,federation_id,national_team_id,competition_edition_id,name,started_on,matches_played,wins,draws,losses,qualification_status,objectives_json,status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET matches_played=excluded.matches_played,wins=excluded.wins,draws=excluded.draws,losses=excluded.losses,qualification_status=excluded.qualification_status,objectives_json=excluded.objectives_json`).run(x.id,x.federationId,x.nationalTeamId,x.competitionEditionId??null,x.name,x.startedOn,x.matchesPlayed,x.wins,x.draws,x.losses,x.qualificationStatus,JSON.stringify(x.objectives??{}),x.status); }
  campaigns(nationalTeamId?: EntityId): NationalTeamCampaign[] { const rows=(nationalTeamId?this.db.prepare("SELECT * FROM national_team_campaigns WHERE national_team_id=? ORDER BY started_on,id").all(nationalTeamId):this.db.prepare("SELECT * FROM national_team_campaigns ORDER BY national_team_id,started_on,id").all()) as any[]; return rows.map(r=>({id:r.id,federationId:r.federation_id,nationalTeamId:r.national_team_id,competitionEditionId:r.competition_edition_id??undefined,name:r.name,startedOn:r.started_on,matchesPlayed:r.matches_played,wins:r.wins,draws:r.draws,losses:r.losses,qualificationStatus:r.qualification_status,objectives:JSON.parse(r.objectives_json??"{}"),status:r.status})); }
  upsertRegistration(x: NationalTeamSquadRegistration): void { this.db.prepare(`INSERT INTO national_team_squad_registrations (id,federation_id,national_team_id,competition_edition_id,registration_deadline,provisional_player_ids_json,final_player_ids_json,status,provenance_status) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET provisional_player_ids_json=excluded.provisional_player_ids_json,final_player_ids_json=excluded.final_player_ids_json,status=excluded.status`).run(x.id,x.federationId,x.nationalTeamId,x.competitionEditionId,x.registrationDeadline,JSON.stringify(x.provisionalPlayerIds),x.finalPlayerIds?JSON.stringify(x.finalPlayerIds):null,x.status,x.provenanceStatus); }
  registrations(nationalTeamId?: EntityId): NationalTeamSquadRegistration[] { const rows=(nationalTeamId?this.db.prepare("SELECT * FROM national_team_squad_registrations WHERE national_team_id=? ORDER BY registration_deadline,id").all(nationalTeamId):this.db.prepare("SELECT * FROM national_team_squad_registrations ORDER BY registration_deadline,id").all()) as any[]; return rows.map(r=>({id:r.id,federationId:r.federation_id,nationalTeamId:r.national_team_id,competitionEditionId:r.competition_edition_id,registrationDeadline:r.registration_deadline,provisionalPlayerIds:JSON.parse(r.provisional_player_ids_json),finalPlayerIds:r.final_player_ids_json?JSON.parse(r.final_player_ids_json):undefined,status:r.status,provenanceStatus:r.provenance_status})); }
  upsertCampLifecycle(x: NationalTeamCampLifecycle): void { this.db.prepare(`INSERT INTO national_team_camp_lifecycles (id,federation_id,national_team_id,competition_edition_id,callup_date,arrival_date,training_start,match_date,release_date,status,player_ids_json,fitness_effect,provenance_status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET arrival_date=excluded.arrival_date,training_start=excluded.training_start,match_date=excluded.match_date,release_date=excluded.release_date,status=excluded.status,player_ids_json=excluded.player_ids_json`).run(x.id,x.federationId,x.nationalTeamId,x.competitionEditionId??null,x.callupDate,x.arrivalDate??null,x.trainingStart??null,x.matchDate??null,x.releaseDate??null,x.status,JSON.stringify(x.playerIds),x.fitnessEffect,x.provenanceStatus); }
  campLifecycles(nationalTeamId?: EntityId): NationalTeamCampLifecycle[] { const rows=(nationalTeamId?this.db.prepare("SELECT * FROM national_team_camp_lifecycles WHERE national_team_id=? ORDER BY callup_date,id").all(nationalTeamId):this.db.prepare("SELECT * FROM national_team_camp_lifecycles ORDER BY callup_date,id").all()) as any[]; return rows.map(r=>({id:r.id,federationId:r.federation_id,nationalTeamId:r.national_team_id,competitionEditionId:r.competition_edition_id??undefined,callupDate:r.callup_date,arrivalDate:r.arrival_date??undefined,trainingStart:r.training_start??undefined,matchDate:r.match_date??undefined,releaseDate:r.release_date??undefined,status:r.status,playerIds:JSON.parse(r.player_ids_json),fitnessEffect:r.fitness_effect,provenanceStatus:r.provenance_status})); }
  upsertCommitment(x: InternationalCommitment): void { this.db.prepare(`INSERT INTO international_commitments (player_id,federation_id,status,decided_on,reason,provenance_status) VALUES (?,?,?,?,?,?) ON CONFLICT(player_id,federation_id) DO UPDATE SET status=excluded.status,decided_on=excluded.decided_on,reason=excluded.reason`).run(x.playerId,x.federationId,x.status,x.decidedOn,x.reason??null,x.provenanceStatus); }
  commitments(federationId?: EntityId): InternationalCommitment[] { const rows=(federationId?this.db.prepare("SELECT * FROM international_commitments WHERE federation_id=? ORDER BY player_id").all(federationId):this.db.prepare("SELECT * FROM international_commitments ORDER BY federation_id,player_id").all()) as any[]; return rows.map(r=>({playerId:r.player_id,federationId:r.federation_id,status:r.status,decidedOn:r.decided_on,reason:r.reason??undefined,provenanceStatus:r.provenance_status})); }
  upsertDiaspora(x: DiasporaRecruitment): void { this.db.prepare(`INSERT INTO diaspora_recruitment (id,federation_id,player_id,status,last_updated,provenance_status) VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=excluded.status,last_updated=excluded.last_updated`).run(x.id,x.federationId,x.playerId,x.status,x.lastUpdated,x.provenanceStatus); }
  diaspora(federationId?: EntityId): DiasporaRecruitment[] { const rows=(federationId?this.db.prepare("SELECT * FROM diaspora_recruitment WHERE federation_id=? ORDER BY last_updated,id").all(federationId):this.db.prepare("SELECT * FROM diaspora_recruitment ORDER BY federation_id,last_updated,id").all()) as any[]; return rows.map(r=>({id:r.id,federationId:r.federation_id,playerId:r.player_id,status:r.status,lastUpdated:r.last_updated,provenanceStatus:r.provenance_status})); }
  upsertWatchlist(x: NationalTeamWatchlistItem): void { this.db.prepare(`INSERT INTO national_team_watchlist (id,federation_id,national_team_id,player_id,player_knowledge_level,reason,last_reviewed,status,provenance_status) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET player_knowledge_level=excluded.player_knowledge_level,reason=excluded.reason,last_reviewed=excluded.last_reviewed,status=excluded.status`).run(x.id,x.federationId,x.nationalTeamId,x.playerId,x.playerKnowledgeLevel,x.reason,x.lastReviewed,x.status,x.provenanceStatus); }
  watchlist(nationalTeamId?: EntityId): NationalTeamWatchlistItem[] { const rows=(nationalTeamId?this.db.prepare("SELECT * FROM national_team_watchlist WHERE national_team_id=? ORDER BY last_reviewed,id").all(nationalTeamId):this.db.prepare("SELECT * FROM national_team_watchlist ORDER BY national_team_id,last_reviewed,id").all()) as any[]; return rows.map(r=>({id:r.id,federationId:r.federation_id,nationalTeamId:r.national_team_id,playerId:r.player_id,playerKnowledgeLevel:r.player_knowledge_level,reason:r.reason,lastReviewed:r.last_reviewed,status:r.status,provenanceStatus:r.provenance_status})); }
  upsertOperationalPlan(x: NationalTeamOperationalPlan): void { this.db.prepare(`INSERT INTO national_team_operational_plans (id,federation_id,national_team_id,competition_edition_id,camp_start,camp_end,travel_plan,base_venue_id,registration_deadline,recovery_days,status,provenance_status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET camp_start=excluded.camp_start,camp_end=excluded.camp_end,travel_plan=excluded.travel_plan,base_venue_id=excluded.base_venue_id,registration_deadline=excluded.registration_deadline,recovery_days=excluded.recovery_days,status=excluded.status`).run(x.id,x.federationId,x.nationalTeamId,x.competitionEditionId??null,x.campStart,x.campEnd,x.travelPlan,x.baseVenue??null,x.registrationDeadline??null,x.recoveryDaysBetweenFixtures,x.status,x.provenanceStatus); }
  operationalPlans(nationalTeamId?: EntityId): NationalTeamOperationalPlan[] { const rows=(nationalTeamId?this.db.prepare("SELECT * FROM national_team_operational_plans WHERE national_team_id=? ORDER BY camp_start,id").all(nationalTeamId):this.db.prepare("SELECT * FROM national_team_operational_plans ORDER BY national_team_id,camp_start,id").all()) as any[]; return rows.map(r=>({id:r.id,federationId:r.federation_id,nationalTeamId:r.national_team_id,competitionEditionId:r.competition_edition_id??undefined,campStart:r.camp_start,campEnd:r.camp_end,travelPlan:r.travel_plan,baseVenue:r.base_venue_id??undefined,registrationDeadline:r.registration_deadline??undefined,recoveryDaysBetweenFixtures:r.recovery_days,status:r.status,provenanceStatus:r.provenance_status})); }
  upsertInternationalForm(x: NationalTeamInternationalForm): void { this.db.prepare(`INSERT INTO national_team_international_form (id,national_team_id,player_id,window_date,appearances,minutes,goals,form_rating,rationale,provenance_status) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET appearances=excluded.appearances,minutes=excluded.minutes,goals=excluded.goals,form_rating=excluded.form_rating,rationale=excluded.rationale`).run(x.id,x.nationalTeamId,x.playerId,x.windowDate,x.appearances,x.minutes,x.goals,x.formRating,x.rationale,x.provenanceStatus); }
  internationalForm(nationalTeamId?: EntityId): NationalTeamInternationalForm[] { const rows=(nationalTeamId?this.db.prepare("SELECT * FROM national_team_international_form WHERE national_team_id=? ORDER BY window_date,player_id").all(nationalTeamId):this.db.prepare("SELECT * FROM national_team_international_form ORDER BY national_team_id,window_date,player_id").all()) as any[]; return rows.map(r=>({id:r.id,nationalTeamId:r.national_team_id,playerId:r.player_id,windowDate:r.window_date,appearances:r.appearances,minutes:r.minutes,goals:r.goals,formRating:r.form_rating,rationale:r.rationale,provenanceStatus:r.provenance_status})); }
}
