import type { EntityId, NationalTeamCampaign, NationalTeamManagementDecision } from "@nepal-football-sim/shared-types";
import type { GameDatabase } from "./connection.js";

export class NationalTeamManagementRepository {
  constructor(private readonly db: GameDatabase) {}
  upsertDecision(x: NationalTeamManagementDecision): void { this.db.prepare(`INSERT INTO national_team_management_decisions (id,federation_id,national_team_id,manager_person_id,decision_date,programme,selected_player_ids_json,captain_player_id,tactical_setup_id,tactical_style,competition_edition_id,status,provenance_status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET selected_player_ids_json=excluded.selected_player_ids_json,captain_player_id=excluded.captain_player_id,tactical_setup_id=excluded.tactical_setup_id,tactical_style=excluded.tactical_style,status=excluded.status`).run(x.id,x.federationId,x.nationalTeamId,x.managerPersonId??null,x.decisionDate,x.programme,JSON.stringify(x.selectedPlayerIds),x.captainPlayerId??null,x.tacticalSetupId??null,x.tacticalStyle??null,x.competitionEditionId??null,x.status,x.provenanceStatus); }
  decisions(nationalTeamId?: EntityId): NationalTeamManagementDecision[] { const rows=(nationalTeamId?this.db.prepare("SELECT * FROM national_team_management_decisions WHERE national_team_id=? ORDER BY decision_date,id").all(nationalTeamId):this.db.prepare("SELECT * FROM national_team_management_decisions ORDER BY national_team_id,decision_date,id").all()) as any[]; return rows.map(r=>({id:r.id,federationId:r.federation_id,nationalTeamId:r.national_team_id,managerPersonId:r.manager_person_id??undefined,decisionDate:r.decision_date,programme:r.programme,selectedPlayerIds:JSON.parse(r.selected_player_ids_json),captainPlayerId:r.captain_player_id??undefined,tacticalSetupId:r.tactical_setup_id??undefined,tacticalStyle:r.tactical_style??undefined,competitionEditionId:r.competition_edition_id??undefined,status:r.status,provenanceStatus:r.provenance_status})); }
  upsertCampaign(x: NationalTeamCampaign): void { this.db.prepare(`INSERT INTO national_team_campaigns (id,federation_id,national_team_id,competition_edition_id,name,started_on,matches_played,wins,draws,losses,qualification_status,status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET matches_played=excluded.matches_played,wins=excluded.wins,draws=excluded.draws,losses=excluded.losses,qualification_status=excluded.qualification_status`).run(x.id,x.federationId,x.nationalTeamId,x.competitionEditionId??null,x.name,x.startedOn,x.matchesPlayed,x.wins,x.draws,x.losses,x.qualificationStatus,x.status); }
  campaigns(nationalTeamId?: EntityId): NationalTeamCampaign[] { const rows=(nationalTeamId?this.db.prepare("SELECT * FROM national_team_campaigns WHERE national_team_id=? ORDER BY started_on,id").all(nationalTeamId):this.db.prepare("SELECT * FROM national_team_campaigns ORDER BY national_team_id,started_on,id").all()) as any[]; return rows.map(r=>({id:r.id,federationId:r.federation_id,nationalTeamId:r.national_team_id,competitionEditionId:r.competition_edition_id??undefined,name:r.name,startedOn:r.started_on,matchesPlayed:r.matches_played,wins:r.wins,draws:r.draws,losses:r.losses,qualificationStatus:r.qualification_status,status:r.status})); }
}
