import type { EntityId, NationalTeamCompensationPayment, NationalTeamCompensationPolicy } from "@nepal-football-sim/shared-types";
import type { GameDatabase } from "./connection.js";
const policy=(r:any):NationalTeamCompensationPolicy=>({id:r.id,federationId:r.federation_id,programme:r.programme,version:r.version,effectiveFrom:r.effective_from,effectiveTo:r.effective_to??undefined,monthlyRetainer:r.monthly_retainer,appearanceFee:r.appearance_fee,winBonus:r.win_bonus,drawBonus:r.draw_bonus,qualificationBonus:r.qualification_bonus,tournamentParticipationBonus:r.tournament_participation_bonus,tournamentPerformanceBonus:r.tournament_performance_bonus,travelAllowance:r.travel_allowance,campAllowance:r.camp_allowance,status:r.status,provenanceStatus:r.provenance_status});
const payment=(r:any):NationalTeamCompensationPayment=>({id:r.id,policyId:r.policy_id,federationId:r.federation_id,nationalTeamId:r.national_team_id,playerId:r.player_id,paymentType:r.payment_type,amount:r.amount,eventId:r.event_id,paidOn:r.paid_on,status:r.status,federationLedgerEntryId:r.federation_ledger_entry_id??undefined,provenanceStatus:r.provenance_status});
export class NationalTeamCompensationRepository{constructor(private readonly db:GameDatabase){db.exec(`CREATE TABLE IF NOT EXISTS national_team_compensation_policies (id TEXT PRIMARY KEY,federation_id TEXT NOT NULL,programme TEXT NOT NULL,version INTEGER NOT NULL,effective_from TEXT NOT NULL,effective_to TEXT,monthly_retainer INTEGER NOT NULL,appearance_fee INTEGER NOT NULL,win_bonus INTEGER NOT NULL,draw_bonus INTEGER NOT NULL,qualification_bonus INTEGER NOT NULL,tournament_participation_bonus INTEGER NOT NULL,tournament_performance_bonus INTEGER NOT NULL,travel_allowance INTEGER NOT NULL,camp_allowance INTEGER NOT NULL,status TEXT NOT NULL,provenance_status TEXT NOT NULL,UNIQUE(federation_id,programme,version));CREATE TABLE IF NOT EXISTS national_team_compensation_payments (id TEXT PRIMARY KEY,policy_id TEXT NOT NULL,federation_id TEXT NOT NULL,national_team_id TEXT NOT NULL,player_id TEXT NOT NULL,payment_type TEXT NOT NULL,amount INTEGER NOT NULL,event_id TEXT NOT NULL,paid_on TEXT NOT NULL,status TEXT NOT NULL,federation_ledger_entry_id TEXT,provenance_status TEXT NOT NULL,UNIQUE(policy_id,player_id,payment_type,event_id));`);}
upsertPolicy(v:NationalTeamCompensationPolicy):void{this.db.prepare(`INSERT INTO national_team_compensation_policies (id,federation_id,programme,version,effective_from,effective_to,monthly_retainer,appearance_fee,win_bonus,draw_bonus,qualification_bonus,tournament_participation_bonus,tournament_performance_bonus,travel_allowance,camp_allowance,status,provenance_status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=excluded.status,effective_to=excluded.effective_to`).run(v.id,v.federationId,v.programme,v.version,v.effectiveFrom,v.effectiveTo??null,v.monthlyRetainer,v.appearanceFee,v.winBonus,v.drawBonus,v.qualificationBonus,v.tournamentParticipationBonus,v.tournamentPerformanceBonus,v.travelAllowance,v.campAllowance,v.status,v.provenanceStatus);}
policies(federationId?:EntityId):NationalTeamCompensationPolicy[]{const rows=(federationId?this.db.prepare("SELECT * FROM national_team_compensation_policies WHERE federation_id=? ORDER BY programme,version").all(federationId):this.db.prepare("SELECT * FROM national_team_compensation_policies ORDER BY federation_id,programme,version").all()) as any[];return rows.map(policy);}
policy(id:EntityId):NationalTeamCompensationPolicy|undefined{const r=this.db.prepare("SELECT * FROM national_team_compensation_policies WHERE id=?").get(id) as any;return r?policy(r):undefined;}
insertPayment(v:NationalTeamCompensationPayment):void{this.db.prepare(`INSERT INTO national_team_compensation_payments (id,policy_id,federation_id,national_team_id,player_id,payment_type,amount,event_id,paid_on,status,federation_ledger_entry_id,provenance_status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(policy_id,player_id,payment_type,event_id) DO NOTHING`).run(v.id,v.policyId,v.federationId,v.nationalTeamId,v.playerId,v.paymentType,v.amount,v.eventId,v.paidOn,v.status,v.federationLedgerEntryId??null,v.provenanceStatus);}
payments(policyId?:EntityId):NationalTeamCompensationPayment[]{const rows=(policyId?this.db.prepare("SELECT * FROM national_team_compensation_payments WHERE policy_id=? ORDER BY paid_on,id").all(policyId):this.db.prepare("SELECT * FROM national_team_compensation_payments ORDER BY policy_id,paid_on,id").all()) as any[];return rows.map(payment);}}
