import type { EntityId, OwnershipAcquisitionOffer, OwnershipAcquisitionTransaction } from "@nepal-football-sim/shared-types";
import type { GameDatabase } from "./connection.js";

const offer = (r: any): OwnershipAcquisitionOffer => ({ id:r.id,clubId:r.club_id,buyerPersonId:r.buyer_person_id,sellerHolderId:r.seller_holder_id??undefined,percentage:r.percentage,offerAmount:r.offer_amount,counterAmount:r.counter_amount??undefined,status:r.status,createdOn:r.created_on,decidedOn:r.decided_on??undefined,rationale:r.rationale??undefined,provenanceStatus:r.provenance_status });
const transaction = (r: any): OwnershipAcquisitionTransaction => ({ id:r.id,offerId:r.offer_id,clubId:r.club_id,buyerPersonId:r.buyer_person_id,sellerHolderId:r.seller_holder_id??undefined,date:r.transaction_date,amount:r.amount,percentage:r.percentage,status:r.status,provenanceStatus:r.provenance_status });
export class OwnershipRepository {
  constructor(private readonly db: GameDatabase) {}
  upsertOffer(value: OwnershipAcquisitionOffer): void { this.db.prepare(`INSERT INTO ownership_acquisition_offers (id,club_id,buyer_person_id,seller_holder_id,percentage,offer_amount,counter_amount,status,created_on,decided_on,rationale,provenance_status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET percentage=excluded.percentage,offer_amount=excluded.offer_amount,counter_amount=excluded.counter_amount,status=excluded.status,decided_on=excluded.decided_on,rationale=excluded.rationale`).run(value.id,value.clubId,value.buyerPersonId,value.sellerHolderId??null,value.percentage,value.offerAmount,value.counterAmount??null,value.status,value.createdOn,value.decidedOn??null,value.rationale??null,value.provenanceStatus); }
  offer(id: EntityId): OwnershipAcquisitionOffer | undefined { const row=this.db.prepare("SELECT * FROM ownership_acquisition_offers WHERE id=?").get(id) as any; return row?offer(row):undefined; }
  offers(clubId?: EntityId): OwnershipAcquisitionOffer[] { const rows=(clubId?this.db.prepare("SELECT * FROM ownership_acquisition_offers WHERE club_id=? ORDER BY created_on,id").all(clubId):this.db.prepare("SELECT * FROM ownership_acquisition_offers ORDER BY created_on,id").all()) as any[]; return rows.map(offer); }
  insertTransaction(value: OwnershipAcquisitionTransaction): void { this.db.prepare("INSERT OR IGNORE INTO ownership_acquisition_transactions (id,offer_id,club_id,buyer_person_id,seller_holder_id,transaction_date,amount,percentage,status,provenance_status) VALUES (?,?,?,?,?,?,?,?,?,?)").run(value.id,value.offerId,value.clubId,value.buyerPersonId,value.sellerHolderId??null,value.date,value.amount,value.percentage,value.status,value.provenanceStatus); }
  transactions(clubId?: EntityId): OwnershipAcquisitionTransaction[] { const rows=(clubId?this.db.prepare("SELECT * FROM ownership_acquisition_transactions WHERE club_id=? ORDER BY transaction_date,id").all(clubId):this.db.prepare("SELECT * FROM ownership_acquisition_transactions ORDER BY transaction_date,id").all()) as any[]; return rows.map(transaction); }
}
