import type { EntityId, RefereeDevelopmentPathway, RefereeDevelopmentProfile, VarProgramme } from "@nepal-football-sim/shared-types";
import type { GameDatabase } from "./connection.js";
const profile=(r:any):RefereeDevelopmentProfile=>({id:r.id,refereeProfileId:r.referee_profile_id,currentQuality:r.current_quality,fitness:r.fitness,experience:r.experience,consistency:r.consistency,disciplinaryTendency:r.disciplinary_tendency,developmentPotential:r.development_potential,status:r.status,updatedOn:r.updated_on,provenanceStatus:r.provenance_status});
const programme=(r:any):RefereeDevelopmentPathway=>({id:r.id,federationId:r.federation_id,programmeType:r.programme_type,refereeProfileIds:JSON.parse(r.referee_profile_ids_json),startDate:r.start_date,endDate:r.end_date,funding:r.funding,staffingQuality:r.staffing_quality,status:r.status,provenanceStatus:r.provenance_status});
const vari=(r:any):VarProgramme=>({id:r.id,federationId:r.federation_id,name:r.name,scope:r.scope,stadiumIds:JSON.parse(r.stadium_ids_json),competitionIds:JSON.parse(r.competition_ids_json),funding:r.funding,trainedOfficials:r.trained_officials,compatibleStadiums:r.compatible_stadiums,operationsCapacity:r.operations_capacity,annualOperatingCost:r.annual_operating_cost,status:r.status,updatedOn:r.updated_on,provenanceStatus:r.provenance_status});
export class RefereeDevelopmentRepository { constructor(private readonly db:GameDatabase){db.exec(`CREATE TABLE IF NOT EXISTS referee_development_profiles (id TEXT PRIMARY KEY,referee_profile_id TEXT NOT NULL UNIQUE,current_quality INTEGER NOT NULL,fitness INTEGER NOT NULL,experience INTEGER NOT NULL,consistency INTEGER NOT NULL,disciplinary_tendency INTEGER NOT NULL,development_potential INTEGER NOT NULL,status TEXT NOT NULL,updated_on TEXT NOT NULL,provenance_status TEXT NOT NULL); CREATE TABLE IF NOT EXISTS referee_development_programmes (id TEXT PRIMARY KEY,federation_id TEXT NOT NULL,programme_type TEXT NOT NULL,referee_profile_ids_json TEXT NOT NULL,start_date TEXT NOT NULL,end_date TEXT NOT NULL,funding INTEGER NOT NULL,staffing_quality INTEGER NOT NULL,status TEXT NOT NULL,provenance_status TEXT NOT NULL); CREATE TABLE IF NOT EXISTS var_programmes (id TEXT PRIMARY KEY,federation_id TEXT NOT NULL,name TEXT NOT NULL,scope TEXT NOT NULL,stadium_ids_json TEXT NOT NULL,competition_ids_json TEXT NOT NULL,funding INTEGER NOT NULL,trained_officials INTEGER NOT NULL,compatible_stadiums INTEGER NOT NULL,operations_capacity INTEGER NOT NULL,annual_operating_cost INTEGER NOT NULL,status TEXT NOT NULL,updated_on TEXT NOT NULL,provenance_status TEXT NOT NULL);`);}
 upsertProfile(v:RefereeDevelopmentProfile):void{this.db.prepare(`INSERT INTO referee_development_profiles (id,referee_profile_id,current_quality,fitness,experience,consistency,disciplinary_tendency,development_potential,status,updated_on,provenance_status) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(referee_profile_id) DO UPDATE SET current_quality=excluded.current_quality,fitness=excluded.fitness,experience=excluded.experience,consistency=excluded.consistency,disciplinary_tendency=excluded.disciplinary_tendency,development_potential=excluded.development_potential,status=excluded.status,updated_on=excluded.updated_on`).run(v.id,v.refereeProfileId,v.currentQuality,v.fitness,v.experience,v.consistency,v.disciplinaryTendency,v.developmentPotential,v.status,v.updatedOn,v.provenanceStatus);}
 profiles():RefereeDevelopmentProfile[]{return (this.db.prepare("SELECT * FROM referee_development_profiles ORDER BY id").all() as any[]).map(profile);}
 upsertProgramme(v:RefereeDevelopmentPathway):void{this.db.prepare(`INSERT INTO referee_development_programmes (id,federation_id,programme_type,referee_profile_ids_json,start_date,end_date,funding,staffing_quality,status,provenance_status) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=excluded.status,funding=excluded.funding,staffing_quality=excluded.staffing_quality`).run(v.id,v.federationId,v.programmeType,JSON.stringify(v.refereeProfileIds),v.startDate,v.endDate,v.funding,v.staffingQuality,v.status,v.provenanceStatus);}
 programmes(federationId?:EntityId):RefereeDevelopmentPathway[]{const rows=(federationId?this.db.prepare("SELECT * FROM referee_development_programmes WHERE federation_id=? ORDER BY start_date,id").all(federationId):this.db.prepare("SELECT * FROM referee_development_programmes ORDER BY federation_id,start_date,id").all()) as any[];return rows.map(programme);}
 upsertVar(v:VarProgramme):void{this.db.prepare(`INSERT INTO var_programmes (id,federation_id,name,scope,stadium_ids_json,competition_ids_json,funding,trained_officials,compatible_stadiums,operations_capacity,annual_operating_cost,status,updated_on,provenance_status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET scope=excluded.scope,funding=excluded.funding,trained_officials=excluded.trained_officials,compatible_stadiums=excluded.compatible_stadiums,operations_capacity=excluded.operations_capacity,annual_operating_cost=excluded.annual_operating_cost,status=excluded.status,updated_on=excluded.updated_on`).run(v.id,v.federationId,v.name,v.scope,JSON.stringify(v.stadiumIds),JSON.stringify(v.competitionIds),v.funding,v.trainedOfficials,v.compatibleStadiums,v.operationsCapacity,v.annualOperatingCost,v.status,v.updatedOn,v.provenanceStatus);}
 vars(federationId?:EntityId):VarProgramme[]{const rows=(federationId?this.db.prepare("SELECT * FROM var_programmes WHERE federation_id=? ORDER BY updated_on,id").all(federationId):this.db.prepare("SELECT * FROM var_programmes ORDER BY federation_id,updated_on,id").all()) as any[];return rows.map(vari);}
 var(id:EntityId):VarProgramme|undefined{const r=this.db.prepare("SELECT * FROM var_programmes WHERE id=?").get(id) as any;return r?vari(r):undefined;}
}
