import type { DistrictDevelopmentProject, DistrictFootballUnit, EntityId, ProvinceFootballUnit, TerritorialRepresentativeTeam } from "@nepal-football-sim/shared-types";
import type { GameDatabase } from "./connection.js";

const j = (value: unknown) => JSON.stringify(value);
const district = (r: any): DistrictFootballUnit => ({ id:r.id,name:r.name,provinceId:r.province_id,locationId:r.location_id??undefined,remoteness:r.remoteness,developmentStatus:r.development_status,affiliationStatus:r.affiliation_status,developmentReputation:r.development_reputation,registeredClubCount:r.registered_club_count,schoolParticipation:r.school_participation,girlsParticipation:r.girls_participation,youthParticipation:r.youth_participation,coachSupply:r.coach_supply,refereeSupply:r.referee_supply,groundAvailability:r.ground_availability,scoutingVisibility:r.scouting_visibility,governanceCompliance:r.governance_compliance,history:JSON.parse(r.history_json),provenanceStatus:r.provenance_status});
const province = (r:any):ProvinceFootballUnit=>({...JSON.parse(r.data_json),id:r.id,name:r.name});
const project = (r:any):DistrictDevelopmentProject=>({id:r.id,districtId:r.district_id,provinceId:r.province_id,projectType:r.project_type,requestedBudget:r.requested_budget,districtContribution:r.district_contribution,provinceContribution:r.province_contribution,municipalityContribution:r.municipality_contribution,federationContribution:r.federation_contribution,restrictedGrantId:r.restricted_grant_id??undefined,durationMonths:r.duration_months,milestones:JSON.parse(r.milestones_json),conditions:JSON.parse(r.conditions_json),reportingStatus:r.reporting_status,outcome:r.outcome??undefined,status:r.status,createdOn:r.created_on,provenanceStatus:r.provenance_status});
const team=(r:any):TerritorialRepresentativeTeam=>({...JSON.parse(r.data_json),id:r.id,name:r.name,territoryId:r.territory_id,territoryType:r.territory_type});
export class TerritorialFootballRepository {
  constructor(private readonly db:GameDatabase){db.exec(`CREATE TABLE IF NOT EXISTS territorial_districts (id TEXT PRIMARY KEY,name TEXT NOT NULL,province_id TEXT NOT NULL,location_id TEXT,remoteness INTEGER NOT NULL,development_status TEXT NOT NULL,affiliation_status TEXT NOT NULL,development_reputation INTEGER NOT NULL,registered_club_count INTEGER NOT NULL,school_participation INTEGER NOT NULL,girls_participation INTEGER NOT NULL,youth_participation INTEGER NOT NULL,coach_supply INTEGER NOT NULL,referee_supply INTEGER NOT NULL,ground_availability INTEGER NOT NULL,scouting_visibility INTEGER NOT NULL,governance_compliance INTEGER NOT NULL,history_json TEXT NOT NULL,provenance_status TEXT NOT NULL); CREATE TABLE IF NOT EXISTS territorial_provinces (id TEXT PRIMARY KEY,name TEXT NOT NULL,data_json TEXT NOT NULL); CREATE TABLE IF NOT EXISTS district_development_projects (id TEXT PRIMARY KEY,district_id TEXT NOT NULL,province_id TEXT NOT NULL,project_type TEXT NOT NULL,requested_budget INTEGER NOT NULL,district_contribution INTEGER NOT NULL,province_contribution INTEGER NOT NULL,municipality_contribution INTEGER NOT NULL,federation_contribution INTEGER NOT NULL,restricted_grant_id TEXT,duration_months INTEGER NOT NULL,milestones_json TEXT NOT NULL,conditions_json TEXT NOT NULL,reporting_status TEXT NOT NULL,outcome TEXT,status TEXT NOT NULL,created_on TEXT NOT NULL,provenance_status TEXT NOT NULL); CREATE TABLE IF NOT EXISTS territorial_representative_teams (id TEXT PRIMARY KEY,name TEXT NOT NULL,territory_type TEXT NOT NULL,territory_id TEXT NOT NULL,data_json TEXT NOT NULL);`);}
  upsertDistrict(v:DistrictFootballUnit){this.db.prepare(`INSERT INTO territorial_districts VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET province_id=excluded.province_id,location_id=excluded.location_id,development_status=excluded.development_status,affiliation_status=excluded.affiliation_status,development_reputation=excluded.development_reputation,registered_club_count=excluded.registered_club_count,school_participation=excluded.school_participation,girls_participation=excluded.girls_participation,youth_participation=excluded.youth_participation,coach_supply=excluded.coach_supply,referee_supply=excluded.referee_supply,ground_availability=excluded.ground_availability,scouting_visibility=excluded.scouting_visibility,governance_compliance=excluded.governance_compliance,history_json=excluded.history_json`).run(v.id,v.name,v.provinceId,v.locationId??null,v.remoteness,v.developmentStatus,v.affiliationStatus,v.developmentReputation,v.registeredClubCount,v.schoolParticipation,v.girlsParticipation,v.youthParticipation,v.coachSupply,v.refereeSupply,v.groundAvailability,v.scoutingVisibility,v.governanceCompliance,j(v.history),v.provenanceStatus);}
  districts(){return (this.db.prepare("SELECT * FROM territorial_districts ORDER BY name").all() as any[]).map(district)} district(id:EntityId){const r=this.db.prepare("SELECT * FROM territorial_districts WHERE id=?").get(id) as any;return r?district(r):undefined}
  upsertProvince(v:ProvinceFootballUnit){this.db.prepare("INSERT INTO territorial_provinces VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,data_json=excluded.data_json").run(v.id,v.name,j(v));} provinces(){return (this.db.prepare("SELECT * FROM territorial_provinces ORDER BY name").all() as any[]).map(province)} province(id:EntityId){const r=this.db.prepare("SELECT * FROM territorial_provinces WHERE id=?").get(id) as any;return r?province(r):undefined}
  upsertProject(v:DistrictDevelopmentProject){this.db.prepare("INSERT INTO district_development_projects VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=excluded.status,reporting_status=excluded.reporting_status,outcome=excluded.outcome,federation_contribution=excluded.federation_contribution").run(v.id,v.districtId,v.provinceId,v.projectType,v.requestedBudget,v.districtContribution,v.provinceContribution,v.municipalityContribution,v.federationContribution,v.restrictedGrantId??null,v.durationMonths,j(v.milestones),j(v.conditions),v.reportingStatus,v.outcome??null,v.status,v.createdOn,v.provenanceStatus);} projects(districtId?:EntityId){return (districtId?this.db.prepare("SELECT * FROM district_development_projects WHERE district_id=? ORDER BY created_on,id").all(districtId):this.db.prepare("SELECT * FROM district_development_projects ORDER BY created_on,id").all() as any[]).map(project)} project(id:EntityId){const r=this.db.prepare("SELECT * FROM district_development_projects WHERE id=?").get(id) as any;return r?project(r):undefined}
  upsertTeam(v:TerritorialRepresentativeTeam){this.db.prepare("INSERT INTO territorial_representative_teams VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET data_json=excluded.data_json,name=excluded.name").run(v.id,v.name,v.territoryType,v.territoryId,j(v));} teams(){return (this.db.prepare("SELECT * FROM territorial_representative_teams ORDER BY id").all() as any[]).map(team)} team(id:EntityId){const r=this.db.prepare("SELECT * FROM territorial_representative_teams WHERE id=?").get(id) as any;return r?team(r):undefined}
}
