import type { EntityId, TrainingCamp, TrainingCampParticipant } from "@nepal-football-sim/shared-types";
import type { GameDatabase } from "./connection.js";
const camp=(r:any):TrainingCamp=>({id:r.id,ownerType:r.owner_type,ownerId:r.owner_id,programmeType:r.programme_type,destination:r.destination==="NEPAL"?"HOME_COUNTRY":r.destination,destinationCountryId:r.destination_country_id??undefined,startDate:r.start_date,endDate:r.end_date,cost:r.cost,facilityQuality:r.facility_quality,climateFit:r.climate_fit,oppositionAccess:r.opposition_access,travelBurden:r.travel_burden,logisticsDifficulty:r.logistics_difficulty,commercialExposure:r.commercial_exposure,scoutingExposure:r.scouting_exposure,status:r.status,participantIds:JSON.parse(r.participant_ids_json),provenanceStatus:r.provenance_status});
const participant=(r:any):TrainingCampParticipant=>({id:r.id,campId:r.camp_id,participantId:r.participant_id,participantType:r.participant_type,role:r.role??undefined,effectSummary:JSON.parse(r.effect_summary_json),provenanceStatus:r.provenance_status});
export class TrainingCampRepository{constructor(private readonly db:GameDatabase){db.exec(`CREATE TABLE IF NOT EXISTS training_camps (id TEXT PRIMARY KEY,owner_type TEXT NOT NULL,owner_id TEXT NOT NULL,programme_type TEXT NOT NULL,destination TEXT NOT NULL,start_date TEXT NOT NULL,end_date TEXT NOT NULL,cost INTEGER NOT NULL,facility_quality INTEGER NOT NULL,climate_fit INTEGER NOT NULL,opposition_access INTEGER NOT NULL,travel_burden INTEGER NOT NULL,logistics_difficulty INTEGER NOT NULL,commercial_exposure INTEGER NOT NULL,scouting_exposure INTEGER NOT NULL,status TEXT NOT NULL,participant_ids_json TEXT NOT NULL,provenance_status TEXT NOT NULL);CREATE TABLE IF NOT EXISTS training_camp_participants (id TEXT PRIMARY KEY,camp_id TEXT NOT NULL,participant_id TEXT NOT NULL,participant_type TEXT NOT NULL,role TEXT,effect_summary_json TEXT NOT NULL,provenance_status TEXT NOT NULL,UNIQUE(camp_id,participant_id));`);if(!(db.prepare("PRAGMA table_info(training_camps)").all() as Array<{name:string}>).some((c)=>c.name==="destination_country_id"))db.exec("ALTER TABLE training_camps ADD COLUMN destination_country_id TEXT REFERENCES countries(id)");}
upsert(v:TrainingCamp):void{this.db.prepare(`INSERT INTO training_camps (id,owner_type,owner_id,programme_type,destination,destination_country_id,start_date,end_date,cost,facility_quality,climate_fit,opposition_access,travel_burden,logistics_difficulty,commercial_exposure,scouting_exposure,status,participant_ids_json,provenance_status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=excluded.status,participant_ids_json=excluded.participant_ids_json`).run(v.id,v.ownerType,v.ownerId,v.programmeType,v.destination,v.destinationCountryId??null,v.startDate,v.endDate,v.cost,v.facilityQuality,v.climateFit,v.oppositionAccess,v.travelBurden,v.logisticsDifficulty,v.commercialExposure,v.scoutingExposure,v.status,JSON.stringify(v.participantIds),v.provenanceStatus);}
camp(id:EntityId):TrainingCamp|undefined{const r=this.db.prepare("SELECT * FROM training_camps WHERE id=?").get(id) as any;return r?camp(r):undefined;}
camps(ownerId?:EntityId):TrainingCamp[]{const rows=(ownerId?this.db.prepare("SELECT * FROM training_camps WHERE owner_id=? ORDER BY start_date,id").all(ownerId):this.db.prepare("SELECT * FROM training_camps ORDER BY start_date,owner_id,id").all()) as any[];return rows.map(camp);}
insertParticipant(v:TrainingCampParticipant):void{this.db.prepare("INSERT INTO training_camp_participants (id,camp_id,participant_id,participant_type,role,effect_summary_json,provenance_status) VALUES (?,?,?,?,?,?,?) ON CONFLICT(camp_id,participant_id) DO UPDATE SET effect_summary_json=excluded.effect_summary_json,role=excluded.role").run(v.id,v.campId,v.participantId,v.participantType,v.role??null,JSON.stringify(v.effectSummary),v.provenanceStatus);}
participants(campId:EntityId):TrainingCampParticipant[]{return (this.db.prepare("SELECT * FROM training_camp_participants WHERE camp_id=? ORDER BY participant_id").all(campId) as any[]).map(participant);}}
